### ISSUE TITLE
Allow pinning of downloads/downloading by hash

### ISSUE THREAD

**Issue by bobobo1618** [mholt/caddy#992] opened 2016-08-02 22:27 UTC
Certain things like building distro packages of Caddy require having a hash (e.g. MD5, SHA256) of a build in order to verify that the "source" is the same that the package description was intended for.

At the moment, https://caddyserver.com/download seems to build the latest version of Caddy (git?) on the fly and serve it to users, presumably with a local cache of some kind.

Would it be possible to allow downloads of a particular version of Caddy (git commit hash? release number?), and to ensure that downloading them results in a file that's bit exact the same each time?

**Comment by mholt** [comment] 2016-08-02 23:36
Yes, this is planned for a future build server. The current one will eventually be scrapped for one with reproducible builds and checksums. So thanks for the request! I'm just going to close this since there's not anything to do with Caddy, and it's already on the roadmap.

**Closed by mholt** 2016-08-02 23:36 UTC
