### ISSUE TITLE
Improve local build instructions

### ISSUE THREAD

**Issue by alex** [mholt/caddy#1843] opened 2017-08-27 13:08 UTC
The instructions found at https://github.com/mholt/caddy#install indicate that to build locally you should:

1. `go get github.com/mholt/caddy/caddy`
2. `cd $GOPATH/src/github.com/mholt/caddy/caddy`
3. `go run build.go`

Here's what happens when I do that:

```
ubuntu@ip-172-26-11-136:~/src$ go get github.com/mholt/caddy/caddy
ubuntu@ip-172-26-11-136:~$ cd go/
ubuntu@ip-172-26-11-136:~/go$ cd src/github.com/mholt/caddy/caddy
ubuntu@ip-172-26-11-136:~/go/src/github.com/mholt/caddy/caddy$ go run build.go
build.go:27:2: cannot find package "github.com/caddyserver/buildworker" in any of:
	/home/ubuntu/go/src/github.com/mholt/caddy/vendor/github.com/caddyserver/buildworker (vendor tree)
	/snap/go/727/src/github.com/caddyserver/buildworker (from $GOROOT)
	/home/ubuntu/go/src/github.com/caddyserver/buildworker (from $GOPATH)
```

**Comment by mholt** [comment] 2017-08-27 14:58
Oops. Kind of surprising `go get` doesn't get the dependency for build.go. 🤔 I'll set up a VM and experiment with this.

**Comment by alex** [comment] 2017-08-27 15:02
For reproduction, this was on a fresh Ubuntu 16.04 AWS instance. All I'd done was `sudo apt update && sudo apt upgrade` and then `sudo snap install --classic go`.

**Comment by mholt** [comment] 2017-08-27 20:56
Ohhh it's because of the build tag on build.go: `// +build dev`

Now, to figure out what to do about this. `go get -tags dev` won't work because there are two `main` functions in that package.

**Comment by arahmanhamdy** [comment] 2017-09-12 14:30
Even when run `go get github.com/caddyserver/buildworker` explicitly, the repo isn't found!
seems that there is a problem with caddyserver/buildworker repo

**Comment by mholt** [comment] 2017-09-12 14:57
@arahmanhamdy Yeah, that's a different issue that's already fixed on master, it was fixed a day or two ago. Still need to figure out what to do about build tag though.

**Comment by centminmod** [comment] 2017-09-13 18:14
I believe i git the same issue

```
go run build.go -goos=linux .
build.go:27:2: cannot find package "github.com/caddyserver/builds" in any of:
        /usr/local/go/src/github.com/caddyserver/builds (from $GOROOT)
        /root/golang/packages/src/github.com/caddyserver/builds (from $GOPATH)
```

* CentOS 7.3
* Go 1.9

```
go env 
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/golang/packages"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="ccache"
GOGCCFLAGS="gcc -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build841778279=/tmp/go-build -gno-record-gcc-switches"
CXX="ccache"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by mholt** [comment] 2017-09-13 18:41
Yeah, the problem is that `go get` only gets dependencies for files included by the build tag, and the "dev" build tag is not a default tag. I need to think this through some more :) but for now, `go run build.go` will build Caddy. I might have to move it to a different folder all by itself... sigh. We'll see.

**Comment by centminmod** [comment] 2017-09-14 14:16
k that works though we loose the version

```
caddy -version
Caddy (untracked dev build)
```

**Comment by centminmod** [comment] 2017-09-14 14:44
not a GO programmer so not sure but couldn't you add another flag to build.go so it could override the `dev` tag ? i.e. `-gobuild=`

```
// build.go automates proper versioning of caddy binaries.
// Use it like:   go run build.go
// You can customize the build with the -goos, -goarch, and
// -goarm CLI options:   go run build.go -goos=windows
```

**Comment by fakeid30** [comment] 2017-09-16 16:47
We can now close this issue since the build instructions are current now, right?

**Comment by mholt** [comment] 2017-09-16 19:05
They are current, but I think I want a better solution.

**Closed** 2017-11-06 16:44 UTC
Labels: deferred, documentation

**Comment by mholt** [comment] 2020-03-20 13:04
This is now resolved thanks to Go modules and new build instructions for v2.
