### ISSUE TITLE
websocket connect failure over https proxy

### ISSUE THREAD

**Issue by sanderhahn** [mholt/caddy#1292] opened 2016-12-09 01:42 UTC
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.3

### 2. What are you trying to do?
Accessing a websocket over an https proxy.

### 3. What is your entire Caddyfile?
```text
# works okay
http://echo.codevelop.nl {
    root /var/www/echo.codevelop.nl
    websocket /echo cat
}
# works okay
https://echo.codevelop.nl {
    root /var/www/echo.codevelop.nl
    websocket /echo cat
}
# works okay
http://proxy.codevelop.nl {
    proxy / http://echo.codevelop.nl {
        header_upstream Connection {>Connection}
        header_upstream Upgrade {>Upgrade}
    }
}
# gives an error
https://proxy.codevelop.nl {
    proxy / https://echo.codevelop.nl {
        header_upstream Connection {>Connection}
        header_upstream Upgrade {>Upgrade}
    }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Using `caddy.service` file and added the -http2=false flag:
ExecStart=/usr/local/bin/caddy -http2=false -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp

### 5. What did you expect to see?
`https://proxy.codevelop.nl` should connect to websocket in the browser like the other domains.

### 6. What did you see instead (give full error messages and/or log)?
javascript console gives an error:
WebSocket connection to `wss://proxy.codevelop.nl/echo` failed: Error during WebSocket handshake: Invalid status line

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Tried to make the example as minimal as possible using the Caddyfile. The websocket code has been taken from http://www.websocket.org/echo.html.

Thank you for making Caddy so user friendly :-)
Best regards,
Sander Hahn

**Comment by sanderhahn** [comment] 2016-12-11 16:12
Tried to debug the websocket through curl:

Access the echo domain directly gives a 101 status:
```
curl -i -N 'https://echo.codevelop.nl/echo' \
   -H 'Pragma: no-cache' \
   -H 'Origin: https://echo.codevelop.nl' \
   -H 'Accept-Encoding: gzip, deflate, sdch, br' \
   -H 'Sec-WebSocket-Version: 13' \
   -H 'Accept-Language: en-US,en;q=0.8,nl;q=0.6' \
   -H 'Sec-WebSocket-Key: k/4jRbqzG0C0nFQIYMyF/A==' \
   -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36' \
   -H 'Upgrade: websocket' \
   -H 'Cache-Control: no-cache' \
   -H 'Connection: Upgrade' \
   -H 'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits' --compressed
```

Response:
```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: WLKA2kHzZ8Z1klITuYYna+d8mIU=
```

Accessing the proxy domain using curl seems to returns binary including the certificates of the `echo.codevelop.nl` domain. Maybe the binary is an encrypted response?

```
curl -i -N 'https://proxy.codevelop.nl/echo' \
  -H 'Pragma: no-cache' \
  -H 'Origin: https://proxy.codevelop.nl' \
  -H 'Accept-Encoding: gzip, deflate, sdch, br' \
  -H 'Sec-WebSocket-Version: 13' \
  -H 'Accept-Language: en-US,en;q=0.8,nl;q=0.6' \
  -H 'Sec-WebSocket-Key: Byp6Y7INJQgdgxBi4FAy7w==' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36' \
  -H 'Upgrade: websocket' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: Upgrade' \
  -H 'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits' --compressed
```

Not sure if i am trying to do something that is not supported by Caddy or if i made a mistake in the configuration.

**Comment by mholt** [comment] 2016-12-23 19:22
Looks like we may have a lead on this, thanks to @lhecker.

**Comment by lhecker** [comment] 2016-12-24 14:03
Alright so the issue is basically that caddy "monkey patches" a `net.Conn`'s `Read()` method to capture the HTTP response headers from the backend and replays those to the client.
The response capturing is done [here](https://github.com/mholt/caddy/blob/a3aa414ff35294f539ca3d900f20dc66ead627c5/caddyhttp/proxy/reverseproxy.go#L317-L321), and the hijacker is returned [here](https://github.com/mholt/caddy/blob/a3aa414ff35294f539ca3d900f20dc66ead627c5/caddyhttp/proxy/reverseproxy.go#L362-L366).

**BUT** in case of TLS connections this won't work, because we hook the `net.Conn` and not the `tls.Conn`.

As I see it this can only be fixed by implementing `transport.DialTLS` and returning a patched `tls.Conn`, or by simply not recording the HTTP headers directly, but doing it the "normal way" just like regular connections already do it (they are not hijacking the connections right?).

P.S. @mholt: I found another bug! 😅 [This](https://github.com/mholt/caddy/blob/a3aa414ff35294f539ca3d900f20dc66ead627c5/caddyhttp/proxy/reverseproxy.go#L264) is broken and suboptimal. It should pass a `but[:cap(buf)]` (note the `cap`!), because `io.CopyBuffer` panics `if len(buf) == 0` and furthermore only uses the buffer up to it's length.

**Comment by mholt** [comment] 2016-12-24 17:48
Great finds @lhecker. I agree, look into the former way first; I think the second way may introduce unintended behavior as I mentioned on your PR a few minutes ago, about duplicate connections.

Feel free to open as many PRs as needed -- we're happy to review them with you!

**Comment by lhecker** [comment] 2016-12-26 15:29
@sanderhahn @mholt I believe I fixed this particular issue today and I'll submit a PR in the coming days after I fixed #1300 and end-to-end tested it on one of our staging servers.

I basically simply took [this code](https://github.com/golang/go/blob/230a376b5a67f0e9341e1fa47e670ff762213c83/src/net/http/transport.go#L1017-L1052) (which is what `net/http` does if no `DialTLS` method is given) and adopted it as the `DialTLS` method for the `connHijackerTransport`. So yea… It turned out to be rather easy to fix. (Still no clue how to fix the #1300 HTTP/2 issue tho.)

**Comment by sanderhahn** [comment] 2016-12-28 00:47
Hello @lhecker and @mholt thank you for your efforts :) Have tried to rebuild Caddy at 9f9ad21 and added an extra init with a log line to ensure i am indeed running your modified version of `reverseproxy.go`. However on the vps the websocket still seems to result in an error if i try to connect on https://proxy.codevelop.nl/. My go version is go1.7.3 linux/amd64 and not the 1.8 beta2 version, however this should not be relevant or does it?

**Comment by lhecker** [comment] 2016-12-28 01:02
Thanks for testing my PR! Really appreciate that. It should work fine on 1.7.3 though…

@mholt I'll try to replicate @sanderhahn's issues with the using his above Caddyfile early tomorrow (CET) and post my findings here (or in the PR if it turns out to be an issue with my code).

**Closed** 2017-01-01 02:51 UTC
Labels: bug, help wanted

**Comment by yingshaoxo** [comment] 2020-01-26 12:07
I've been spending a whole night to solve this problem when I start to use `https` or `wss` or `ssl`. It always says `connection stopped before establish` with `400` error code.

Just a minutes ago, I found a solution for that:

### 1. Make sure you have a right proxy configuration.
```
ai-tools-online.xyz {
    proxy / 127.0.0.1:5000 {
        except /socket.io
        transparent
    }

    proxy /socket.io 127.0.0.1:5000 { 
        websocket 
        transparent
    } 
}
import sites/*
```

or

```
ai-tools-online.xyz {
    proxy / 127.0.0.1:5000 {
        except /socket.io
    }
    proxy /socket.io 127.0.0.1:5000 { 
        header_upstream Host {host} 
        header_upstream X-Real-IP {remote} 
        header_upstream X-Forwarded-For {remote} 
        websocket 
    } 
}
import sites/*
```

`ai-tools-online.xyz` is your domain, `http://127.0.0.1:5000` is your socket server.

### 2. Make sure your server `Cross-Origin Controls` is set to `'*'` to allow `Cross-Origin Access`

For `flask-socketio`, is to use `flask_socketio.SocketIO(app, cors_allowed_origins = '*')`

### 3. You must restart the caddy to let the new config work
I don't know how to restart caddy, but `reboot` may do that job

### 4. For more details about how to set `nginx`, see the following links:
https://github.com/yingshaoxo/Web-Math-Chat#reverse-proxy-configuration-for-https
https://www.nginx.com/blog/nginx-nodejs-websockets-socketio/
https://caddy.community/t/using-caddy-0-9-1-with-socket-io-and-flask-socket-io/508/6
