### ISSUE TITLE
Caddy won't start after upgrade to the 0.11.2 due to the issue with Cloudflare

### ISSUE THREAD

**Issue by UniverseXXX** [mholt/caddy#2436] opened 2019-01-20 09:07 UTC
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.2

### 2. What are you trying to do?
Caddy won't start on Raspberry Pi 2 after upgrade to the 0.11.2 due to the issue with Cloudflare. All the Cloudflare env parameters are in place and haven't been changed. Previous version working fine.

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
[Unit]
Description=Caddy HTTP/2 web server
Documentation=https://caddyserver.com/docs
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service

[Service]
Restart=on-abnormal

; User and group the process will run as.
User=www-data
Group=www-data

; Letsencrypt-issued certificates will be written to this directory.
Environment=CADDYPATH=/etc/ssl/caddy
Environment=ACME_AGREE=true
Environment=CLOUDFLARE_API_KEY=xxxxxxxxxxxxxxxx
Environment=CLOUDFLARE_EMAIL=xxxxxxxxx
Environment=JWT_SECRET=xxxxxxxxxxxx

; Always set "-root" to something safe in case it gets forgotten in the Caddyfile.
ExecStart=/usr/local/bin/caddy -quic -log=syslog -agree=true -http-port=89 -https-port=449 -conf=/etc/caddy/Caddyfile -root=/var/tmp
ExecReload=/bin/kill -USR1 $MAINPID

; Use graceful shutdown with a reasonable timeout
KillMode=mixed
KillSignal=SIGQUIT
TimeoutStopSec=5s

; Limit the number of file descriptors; see `man systemd.exec` for more limit settings.
LimitNOFILE=1048576
; Unmodified caddy is not expected to use more than that.
LimitNPROC=512

; Use private /tmp and /var/tmp, which are discarded after caddy stops.
PrivateTmp=true
; Use a minimal /dev (May bring additional security if switched to 'true', but it may not work on Raspberry Pi's or other devices, so it has been disabled$
PrivateDevices=false
; Hide /home, /root, and /run/user. Nobody will steal your SSH-keys.
ProtectHome=true
; Make /usr, /boot, /etc and possibly some more folders read-only.
ProtectSystem=full
; … except /etc/ssl/caddy, because we want Letsencrypt-certificates there.
;   This merely retains r/w access rights, it does not add any new. Must still be writable on the host!
ReadWriteDirectories=/etc/ssl/caddy

; The following additional security directives only work with systemd v229 or later.
; They further restrict privileges that can be gained by caddy. Uncomment if you like.
; Note that you may have to add capabilities required by any plugins in use.
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
;AmbientCapabilities=CAP_NET_BIND_SERVICE
;NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
```

### 7. What did you see instead (give full error messages and/or log)?
>Jan 19 23:53:04 RPi systemd[1]: caddy.service: Failed with result 'exit-code'.
Jan 19 23:53:04 RPi systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE 
Jan 19 23:53:04 RPi caddy[32430]:   Email address: registration error: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:rateLimited :: Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/, url:
Jan 19 23:53:02 RPi caddy[32430]: in case of issues. You can leave it blank, but we don't recommend it.
Jan 19 23:53:02 RPi caddy[32430]: Please enter your email address to signify agreement and to be notified
Jan 19 23:53:02 RPi caddy[32430]:   https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Jan 19 23:53:02 RPi caddy[32430]: By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
Jan 19 23:53:02 RPi caddy[32430]: Your sites will be served over HTTPS automatically using Let's Encrypt.
Jan 19 23:53:02 RPi caddy[32430]: Activating privacy features...
Jan 19 23:53:01 RPi systemd[1]: Started Caddy HTTP/2 web server.

Output of the env command:
>root@RPi /Dockers# env
ACME_AGREE=true
CADDYPATH=/etc/ssl/caddy
CADDY_TELEMETRY=on
CLOUDFLARE_API_KEY=xxxxxxx
CLOUDFLARE_EMAIL=xxxxxx

Thanks.

**Comment by LouisMT** [comment] 2019-01-20 12:06
I think this is an issue with Let's Encrypt, not CloudFlare. Please take a look at #2400, your issue looks exactly the same. It appears there was a bug in Caddy 0.11.2 that causes Caddy to request a new Let's Encrypt account for every certificate, whether it was already obtained or not. After 10 requests you'll get rate limited for 3 hours and Caddy will exit.

I'm having the exact same problem after upgrading my Docker from Caddy 0.11.1 to 0.11.2. I think this has already been fixed with f3a4f46, 78455c7 and 01f2b85, but this hasn't been released yet.

**Comment by UniverseXXX** [comment] 2019-01-20 12:30
> In my case I could simply downgrade to Caddy 0.11.1 to get my sites up & running again. The `.caddy` directory seems to be intact. 😄

I had a copy of the previous version, just rolled back.

**Comment by francislavoie** [comment] 2019-01-20 15:45
I'll close this as a duplicate of #2400. Thanks @LouisMT

**Closed by francislavoie** 2019-01-20 15:45 UTC
