### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by coleplx** [mholt/caddy#1450] opened 2017-02-18 01:43 UTC
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.5

### 2. What are you trying to do?
Running caddy as a reverse proxy to nginx, with quic support enabled

### 3. What is your entire Caddyfile?
```text
st2.xxxxxxx.net {
        proxy   /       st2-nginx.xxxxxxx.net:8080
}

stream-st2.xxxxxxx.net {
        proxy   /       stream-st2-nginx.xxxxxxx.net:8080
        cors / {
                allowed_headers Access-Control-Allow-Headers,Authorization,X-Requested-With,Content-Range,Range
        }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy -quic &
`
Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz, 32gb ram, CentOS Linux release 7.2.1511 (Core) 

### 5. What did you expect to see?
Caddy running fine

### 6. What did you see instead (give full error messages and/or log)?
After few hours running, I get the following error.
(In another server, I got the same error after few minutes (~20m), but I blamed the poor VPS it was running on.)
```
[root@st2 data]# panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x8ada58]

goroutine 2114010 [running]:
panic(0x9d1320, 0xc42000e080)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/lucas-clemente/quic-go.(*stream).AddStreamFrame(0x0, 0xc42060b4a0, 0x0, 0x0)
        /home/caddy/go/src/github.com/lucas-clemente/quic-go/stream.go:238 +0x48
github.com/lucas-clemente/quic-go.(*stream).CloseRemote(0x0, 0x0)
        /home/caddy/go/src/github.com/lucas-clemente/quic-go/stream.go:255 +0x79
github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest(0xc420211820, 0xd2e420, 0xc42113e000, 0xd33380, 0xc421544ea0, 0xc422266e00, 0xc420225520, 0xc4202255f0, 0x0, 0x0)
        /home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:159 +0x753
github.com/lucas-clemente/quic-go/h2quic.(*Server).handleStream.func1(0xc420211820, 0xd2e420, 0xc42113e000, 0xd33380, 0xc421544ea0, 0xc420225520, 0xc4202255f0)
        /home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:108 +0xa9
created by github.com/lucas-clemente/quic-go/h2quic.(*Server).handleStream
        /home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:118 +0x116

[1]+  Exit 2                  caddy -quic

```

**Comment by mholt** [comment] 2017-02-18 02:05
Hey, thanks for filing an issue. I think this is a duplicate of #1415 which will be fixed in the next release. (A little searching goes a long way!)

**Closed by mholt** 2017-02-18 02:05 UTC
