### ISSUE TITLE
Websockets not working in 0.9 but did work in 0.8.3 with same Caddyfile

### ISSUE THREAD

**Issue by schollz** [mholt/caddy#953] opened 2016-07-21 16:52 UTC
#### 1. What version of Caddy are you running (`caddy -version`)?

I tested using the new Caddy 0.9.0, and the previous Caddy 0.8.3.

#### 2. What are you trying to do?

In version 0.8.3 I was able to reverse proxy the websocket connection. This doesn't seem to work anymore in 0.9.0 - unless I'm missing some breaking change for websockets. 

#### 3. What is your entire Caddyfile?
```text
127.0.0.1:80 {
        gzip
        proxy / 127.0.0.1:8003 {
			except /static
			proxy_header Host {host}
			proxy_header X-Real-IP {remote}
			proxy_header X-Forwarded-For {remote}
			proxy_header X-Forwarded-Proto {scheme}
			proxy_header  Connection {>Connection}
			proxy_header  Upgrade    {>Upgrade}
        }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

I downloaded both the 0.8.3 version and the 0.9 version and ran in the directory of the Caddyfile with `sudo ./caddy09` or `sudo ./caddy083`. Using Ubuntu 14.0.4.

#### 5. What did you expect to see?

The websockets work fine with 0.8.3, but it doesn't work in 0.9.

#### 6. What did you see instead (give full error messages and/or log)?

Firefox gives the following when using 0.9:

```
GET http://127.0.0.1/ws [HTTP/1.1 400 Bad Request 3ms]
Firefox can't establish a connection to the server at ws://127.0.0.1/ws.
```

while 0.8.3 gives no error in Firefox. Caddy itself doesn't give any error in either case, it just seems the websockets don't work on 0.9.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Here's a complete set of commands that will emulate exactly what I did (down to running my program):

```
git clone https://github.com/schollz/cowyo.git
cd cowyo
go build
wget https://github.com/mholt/caddy/releases/download/v0.8.3/caddy_linux_amd64.tar.gz
tar -xvzf caddy_linux_amd64.tar.gz
mv caddy_linux_amd64 caddy083
wget https://github.com/mholt/caddy/releases/download/v0.9.0/caddy_linux_amd64.tar.gz
tar -xvzf caddy_linux_amd64.tar.gz.1
mv caddy_linux_amd64 caddy09
```

Then on one terminal type `./cowyo 127.0.0.1` and on another load up either version of Caddy `sudo ./caddy09` or `sudo ./caddy083` using the Caddyfile above. Then open up a webrowser to `127.0.0.1` and you check the console for errors.

**Comment by mholt** [comment] 2016-07-21 16:56
What if you remove the gzip directive, just to see if it starts working?

**Comment by schollz** [comment] 2016-07-21 17:03
Removing the gzip directive does not change the behaviour for either version (0.9.0 still can't connect to websocket).

**Comment by mholt** [comment] 2016-07-21 17:08
Wonder if this is the same as #886.

**Comment by mholt** [comment] 2016-07-22 19:12
Sorry, but I'm still unable to reproduce this. Everything works fine following your instructions.

<img width="695" alt="screen shot 2016-07-22 at 1 10 56 pm" src="https://cloud.githubusercontent.com/assets/1128849/17068382/e9de74be-500d-11e6-9db4-0f7a5ec73c19.png">

<img width="744" alt="screen shot 2016-07-22 at 1 11 03 pm" src="https://cloud.githubusercontent.com/assets/1128849/17068381/e8e7a15c-500d-11e6-9f0a-bb3976eb6ad6.png">

**Comment by schollz** [comment] 2016-07-22 19:51
Haha okay. I've gone back and tried on three different machines using real IPs/DNS names and still get `websocket: could not find connection header with token 'upgrade'` server-side and the problems in the client-side mentioned above. So I'm confused, but its definitely possible I'm doing something dumb so let me see if I can figure it out before you spend more time on this. Thanks!

**Comment by mholt** [comment] 2016-07-22 20:32
Okay! I'm going to close this and we'll concentrate all the discussion into #886. Thanks.

**Closed by mholt** 2016-07-22 20:32 UTC
