### ISSUE TITLE
How do hide header info in 404 status?

### ISSUE THREAD

**Issue by iscraft** [mholt/caddy#1277] opened 2016-11-29 02:33 UTC
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.9.3

### 2. What are you trying to do?

hide header info in the 404 status
### 3. What is your entire Caddyfile?
```text
.........
gzip
fastcgi / 127.0.0.1:9000 php {
ext .php
index index.php index.html
}
header / {
-Server
}
..........
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

service caddy start
### 5. What did you expect to see?

hide "server"
### 6. What did you see instead (give full error messages and/or log)?

server:caddy display
### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
status 200 ok
![snipaste20161129_102734](https://cloud.githubusercontent.com/assets/5448825/20694191/85eb7b7e-b61e-11e6-9f6b-e5e8ab7d7d3e.png)
![snipaste20161129_102824](https://cloud.githubusercontent.com/assets/5448825/20694199/93ec0dce-b61e-11e6-9e95-d9308f38cc06.png)
status 404
![snipaste20161129_102912](https://cloud.githubusercontent.com/assets/5448825/20694228/b33fa8a2-b61e-11e6-91bb-460f52044698.png)
![snipaste20161129_102938](https://cloud.githubusercontent.com/assets/5448825/20694239/c3d21a56-b61e-11e6-8ee5-977637998279.png)
![snipaste20161129_103008](https://cloud.githubusercontent.com/assets/5448825/20694251/d3c642de-b61e-11e6-9373-4b6fad2c8af1.png)

**Comment by wendigo** [comment] 2016-12-05 20:13
Can't confirm it on master. Can you test it yourself @iscraft and show a way to reproduce it?

**Comment by mholt** [comment] 2016-12-06 15:01
Gonna remove the bug label until we confirm it actually is a bug. :)

**Comment by mholt** [comment] 2017-01-01 03:49
Might be a duplicate of #1183 -- closing; please try upgrading to 0.9.4. Thanks!

**Closed by mholt** 2017-01-01 03:49 UTC
