### ISSUE TITLE
Unable to bypass letsencrypt when using a domain name and port 80.

### ISSUE THREAD

**Issue by ianwalter** [mholt/caddy#487] opened 2016-01-04 17:48 UTC
My domain got rate-limited by letsencrypt so I've been trying to use http for the time-being.
I have something similar to the following in my Caddyfile:
```
http://foobar.com {
#  tls myemail@address.com
  root /www/foobar.com
}
```
I've also tried `http://foobar.com:80` and I think I've tried `foobar.com:80`, but Caddy still tries to get me a cert and I get the following error message:
```
[foobar.com] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for: foobar.com
```
I also noticed that this scenario isn't covered in `letsencrypt_test.go`. I tried adding this to TestHostQualifies and the test failed:
```go
// ...
{"foobar.com:80", false},
{"http://foobar.com", false},
//...
```
Is this handled somewhere else?

**Comment by mholt** [comment] 2016-01-04 17:49
Yes, upstream in the letsencryptfix branch. :smile: Hang tight for version 0.8.1 which fixes a few of these edge cases. But for now, `tls off` should do the trick.

**Comment by mholt** [comment] 2016-01-04 17:55
Duplicate of #391 and #450.

**Closed by mholt** 2016-01-04 17:55 UTC

**Comment by ianwalter** [comment] 2016-01-04 17:57
Thanks, sorry for the duplicate, I really did search for those issues haha.

**Comment by mholt** [comment] 2016-01-04 18:07
No problem - I know it's frustrating, sorry about that. Just stay tuned for the update. ;)
