### ISSUE TITLE
https://localhost works, but https://LOCAL_IP shows ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by kalitine** [mholt/caddy#2423] opened 2019-01-11 18:49 UTC
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.1

### 2. What are you trying to do?
Serve a static website on `https://localhost:443` and `https://192.168.0.15:443`.

### 3. What is your entire Caddyfile?
```text
localhost:443, 192.168.0.15:443

root dist/

log caddy.log
errors caddy.err

tls ssl/localhost+1.pem ssl/localhost+1-key.pem
```
### 4. How did you run Caddy (give the full command and describe the execution environment)?
With command: `caddy -conf caddy.conf`

### 5. Please paste any relevant HTTP request(s) here.
Tried in Chrome and Firefox: `https://localhost` and `https://192.168.0.15`

### 6. What did you expect to see?
Static website served for both requests.

### 7. What did you see instead (give full error messages and/or log)?
`https://localhost` works just fine, but `https://192.168.0.15` results in ERR_SSL_PROTOCOL_ERROR for Chrome and for Firefox in:
```
An error occurred during a connection to 192.168.0.15. Peer reports it experienced an internal error. 

Error code: SSL_ERROR_INTERNAL_ERROR_ALERT

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
I generated self-signed certificates with help of [mkcert](https://github.com/FiloSottile/mkcert). And the point is that I've also tried to serve the same website with `http-server` (based on NodeJS) server with the following command (by default it serves from all available interfaces, thus on localhost and 192.168.0.15 included):
```
http-server dist/ --ssl --cert sslocalhost+1.pem --key ssl/localhost+1-key.pem
```
And it worked well for both requests (localhost and 192.168.0.15). That's why I thought that it might be a bug in Caddy and I haven't found anything related to this bug.

**Comment by mholt** [comment] 2019-01-11 19:13
Duplicate of #2356

**Closed by mholt** 2019-01-11 19:13 UTC
