### ISSUE TITLE
[bug] multiple values for proxy_header templates

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#341] opened 2015-11-14 03:08 UTC
I'm receiving quadruple values for templated headers of `proxy_header`:

Incoming Headers
```
X-Forwarded-Proto: https, https, https, https
X-Forwarded-Host: hellabit.com, hellabit.com, hellabit.com, hellabit.com
```

Caddyfile
```Caddyfile
https://hellabit.com {
  gzip
  tls /srv/walnut/certs/live/hellabit.com/fullchain.pem /srv/walnut/certs/live/hellabit.com/privkey.pem
  root /srv/walnut/sites-enabled/hellabit.com/
  proxy /api http://localhost:4080 {
    proxy_header Host {host}
    proxy_header X-Forwarded-Host {host}
    proxy_header X-Forwarded-Proto {scheme}
  }
}
```

**Comment by mholt** [comment] 2015-11-14 06:12
Uhhh that's cool... I'll see if I can reproduce it.

**Comment by mholt** [comment] 2015-11-15 15:21
But it doesn't happen for the Host header?

**Comment by coolaj86** [comment] 2015-11-15 20:04
My guess is that it does but node's http parser ignores the illegal ',' and all trailing characters.

**Comment by coolaj86** [comment] 2015-11-15 20:06
Also, I had 4 entries in my Caddyfile. It would be interesting to test with 3 or 5 entries and see if the multiple changes accordingly.

**Comment by mholt** [comment] 2015-11-15 20:11
Yes, please do and let me know.

By "entries" you mean server blocks?

**Comment by coolaj86** [comment] 2015-11-17 04:30
Yes, server blocks.

Confirmed that the number of times that a value exists is the number of server blocks.

**Comment by tw4452852** [comment] 2015-11-17 06:22
Just upload a fix, it makes http header block scoped instead global share.
BTW, we may also set a default global one, it may be used when proxy block
doesn't set its own one.

**Comment by mholt** [comment] 2015-11-17 06:39
@tw4452852 That's awesome - thank you! And that's true, we'll keep that in mind if it turns out we need a default global header map for the proxy.

**Comment by mholt** [comment] 2015-11-17 15:21
@coolaj86 I've merged in Tw's fix - if you pull the latest from master it should be working now. Thanks for the report, and the fix, both of you!

**Closed by mholt** 2015-11-17 15:21 UTC
Labels: bug

**Comment by coolaj86** [comment] 2015-11-21 12:55
Haven't tested yet, but wanted to say thank you all the same.

:-)
