### ISSUE TITLE
Caddy as a Forward proxy?

### ISSUE THREAD

**Issue by manojlds** [mholt/caddy#700] opened 2016-03-28 09:29 UTC
Can I use Caddy to load balance / rotate across a bunch of proxies that I use?

Essentially, I would like the following curl request:

```
curl -x localhost:2015 http://www.google.com
```

to use my set of proxies, rotated behind `localhost:2015`, which is my Caddy instance.

**Comment by arthurwhite** [comment] 2016-03-28 13:10
The [`proxy`](https://caddyserver.com/docs/proxy) directive does it.

Your `Caddyfile`:
```Caddyfile
localhost:2015
proxy / yourproxyone yourproxytwo yourproxythree
```

**Comment by manojlds** [comment] 2016-03-29 11:57
@arthurwhite that's something I tried before asking this. It doesn't work, and in my case I get a 400 Bad Request from proxy servers I am using.

My `Caddyfile` is exactly what you mentioned, and I did a 

```
curl -Lvx localhost:2015 http://www.google.com
```

My working haproxy configuration:

```
frontend rotatingproxies
        bind *:3000
        default_backend rotateproxy

backend rotateproxy
        server proxy1 yourproxyone:80

        balance roundrobin
```

**Comment by arthurwhite** [comment] 2016-03-29 13:02
In Caddy, only `websocket` and `browse` middlewares can potentially send a `400 Bad Request` code.
So I suppose it comes from your proxies.

Did you enable error logs in your `Caddyfile` to see that clearly?

```Caddyfile
localhost:2015
proxy / yourproxyone yourproxytwo yourproxythree
errors proxieserrors.log
```

**Comment by mholt** [comment] 2016-03-29 13:30
@manojlds I don't really understand what the `-x` flag does under the hood, but yeah, enable error logging as Arthur suggests and let's see if we can figure this out. (Caddy isn't meant to be a "forward" proxy but I wonder if it's not that different.)

**Comment by arthurwhite** [comment] 2016-03-29 16:03
> Caddy isn't meant to be a "forward" proxy […].

That's the answer!

As described in [RFC 2616, Section 5.1.2](https://tools.ietf.org/html/rfc2616#section-5.1.2), a proxy needs to receive an absolute URI in the HTTP request line. That's what the `-x` flag does.

But since the Caddy's *proxy* middleware is a **reverse** proxy and not a **forward** proxy as you said, it does nothing with the with the `RequestURI` field from the original `*http.Request`.
See [middleware/proxy/reverseproxy.go#L163](https://github.com/mholt/caddy/blob/master/middleware/proxy/reverseproxy.go#L163).

So while @manojlds `curl -x localhost:2015 http://www.google.com` and the original request is
```
> GET http://www.google.com/ HTTP/1.1
```
, the @manojlds's proxies receive 
```curl
> GET / HTTP/1.1
```

**Comment by manojlds** [comment] 2016-03-30 06:32
@mholt Based on @arthurwhite 's response, Caddy doesn't seem to support forward proxying scenarios. I guess this can be a useful feature to have in Caddy. We can keep this issue open? I am just beginning to learn Go, but myself or someone else can probably submit a PR for this.

**Comment by arthurwhite** [comment] 2016-03-30 09:19
Mmm, it was a premature conclusion…
The [next line](https://github.com/mholt/caddy/blob/master/middleware/proxy/reverseproxy.go#L164) copies the `RequestURI`. :sweat_smile: 

The problem is somewhere else.
Can you post your error log please?

**Comment by manojlds** [comment] 2016-03-30 11:50
@arthurwhite There are no error logs. The 400 does come from my proxy severs.

Access logs:

```
::1 - [30/Mar/2016:12:01:56 +0530] "GET / HTTP/1.1" 400 12
```

**Comment by manojlds** [comment] 2016-03-30 12:00
Using some public proxies:

Direct:

```
curl -Lvx 52.36.247.10:8083 http://www.google.com
```

Via Caddy. Caddyfile:

```
:2015

log stdout
errors stdout

proxy / 52.36.247.10:8083

```

Request:

```
curl -Lvx localhost:2015 http://www.google.com
```

Curl verbose output:

```
* Rebuilt URL to: http://www.google.com/
*   Trying ::1...
* Connected to localhost (::1) port 2015 (#0)
> GET http://www.google.com/ HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.43.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 400 Bad Request
< Content-Language: en
< Content-Length: 3161
< Content-Type: text/html
< Date: Wed, 30 Mar 2016 11:59:22 GMT
< Mime-Version: 1.0
< Server: Caddy
< Server: squid/3.3.8
< Vary: Accept-Language
< Via: 1.1 ip-172-31-22-69 (squid/3.3.8)
< X-Cache: MISS from ip-172-31-22-69
< X-Cache-Lookup: NONE from ip-172-31-22-69:8083
< X-Squid-Error: ERR_INVALID_URL 0
```

Does this help @arthurwhite ?

**Comment by manojlds** [comment] 2016-03-30 12:05
And it is problem between sending `/` and `http://www.google.com` in the request. The proxy receives `/` instead of a absolute url and says invalid url.

**Comment by mholt** [comment] 2016-03-30 15:15
Would it be as simple as changing the Request with our [custom Director](https://github.com/mholt/caddy/blob/b3a5b725db068296fd39dbf102c18ce386d57d1b/middleware/proxy/reverseproxy.go#L82)?

**Comment by arthurwhite** [comment] 2016-03-30 18:04
No, we see that the request structure remains correct (the `RequestURI` value is kept) all along.

But in our case, the [`http.DefaultTransport` is used](https://github.com/mholt/caddy/blob/master/middleware/proxy/reverseproxy.go#L160).
And this `http.RoundTripper` doesn't seem to transfer to original request URI in its own request.

It is simply testable with a client, a server, and proxy CURL:

```Go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.ListenAndServe("localhost:8080", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Println(r.RequestURI)
	}))
}
```
```Go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.ListenAndServe("localhost:8080", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Println(r.RequestURI)
	}))
}
```

**Comment by arthurwhite** [comment] 2016-03-30 18:10
No, we see that the request structure remains correct (the `RequestURI` value is kept) all along.

But in our case, the [`http.DefaultTransport` is used](https://github.com/mholt/caddy/blob/master/middleware/proxy/reverseproxy.go#L160).
And this `http.RoundTripper` doesn't seem to transfer to original request URI in its own request.

**Comment by nemothekid** [comment] 2016-04-22 23:54
I believe this will work if your Caddyfile is setup like so:

```
proxy / proxyone proxytwo proxythree {
	policy round_robin
	proxy_header Host {host}
}
```

My guess is, as the screenshot in @manojlds shows, Caddy isn't forwarding the `Host` header. Because of this, Host header may get sent as "proxythree", which will confuse the final destination server if they are using virtual hosts (which almost every host does).

**Comment by nemothekid** [comment] 2016-04-23 00:01
Actually I may be wrong, reading this thread a little closer, it looks like you need golang's http to not strip out the hostname when making the GET request. 

To make this work you would need to edit [https://github.com/mholt/caddy/blob/master/middleware/proxy/reverseproxy.go#L229](reverseproxy.go#L229) and change `.Write()` to `.WriteProxy()` ([(*Request) WriteProxy](https://golang.org/pkg/net/http/#Request.WriteProxy)).

This seems like a pretty special/limited case, that AFAICT serves one use case (load balancing amongst proxies) so I'm not sure if its worth baking into Caddy - however the "solution" is pretty easy.

**Comment by mholt** [comment] 2016-08-12 22:31
Since this is not likely to work its way into Caddy's HTTP server in the foreseeable future, I'm going to close this. Good discussion!

**Closed by mholt** 2016-08-12 22:31 UTC

**Comment by sergeyfrolov** [comment] 2018-06-27 17:51
Hey folks,
Accidentally found this issue, and would like to let you know that `http.forwardproxy` plugin has been supported in Caddy for almost a year.
[Source code and documentation](https://github.com/caddyserver/forwardproxy)
