### ISSUE TITLE
proxy_header Host doesn't appear to work

### ISSUE THREAD

**Issue by kaihendry** [mholt/caddy#854] opened 2016-05-28 05:33 UTC
#### 1. What version of Caddy are you running (`caddy -version`)?

238250e

#### 2. What are you trying to do?

Reverse proxy to a site with a Host: defined

#### 3. What is your entire Caddyfile?
```text
localhost
proxy / testserver:8080 {
    proxy_header Host foobar.com
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy`

```
$ hostnamectl
   Static hostname: teefour
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: 08fa83b18a364e11aa225f5b23ff3a19
           Boot ID: 1460ab922a064e10b811bf38c03282bd
  Operating System: Arch Linux
            Kernel: Linux 4.5.1-1-t460s
      Architecture: x86-64
```

#### 5. What did you expect to see?

Request on _testsever_ with **Host: foobar.com**

#### 6. What did you see instead (give full error messages and/or log)?

Wrong site server since **Host: localhost:2015** is sent over

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

http://s.natalian.org/2016-05-28/debug.go is how I setup _testserver_

Btw this is how I've done a reverse proxy with golang in my own tests: https://github.com/kaihendry/go-rproxy-test/blob/master/main.go which works well.

**Comment by abiosoft** [comment] 2016-05-29 06:32
I've reproduced this. Working on a fix.

**Comment by abiosoft** [comment] 2016-05-29 07:12
Fixed in https://github.com/mholt/caddy/commit/a0e6eb3ba950e94eb0d061c0c7697d3f8005f975

**Closed by abiosoft** 2016-05-29 07:12 UTC

**Comment by mholt** [comment] 2016-05-29 13:21
Oops. Thanks :smile: I think I broke this a few weeks ago when fixing proxy for something else.

**Comment by wesm-outreach** [comment] 2018-01-29 21:07
Where is the docs for `proxy_header`? I don't see that here: https://caddyserver.com/docs/proxy

**Comment by francislavoie** [comment] 2018-01-29 22:19
@wesm-outreach it's now called `header_upstream` and `header_downstream`. This issue is from nearly two years ago, things have changed a bunch since then.

**Comment by wesm-outreach** [comment] 2018-01-30 00:37
@francislavoie ya they have! Lol. I was doing some google searches around converting from nginx to Caddy, and this issue popped up. I didn't quite equate the `header_downstream` from the docs to my use case until now. Thanks for the reply! Sorry for resurrecting an old issue.
