### ISSUE TITLE
Caddy cannot handle mixed-case paths in server addresses

### ISSUE THREAD

**Issue by pjeby** [mholt/caddy#1849] opened 2017-08-30 03:56 UTC
### 1. What version of Caddy are you using (`caddy -version`)?
 0.10.7

### 2. What are you trying to do?
Use a mixed-case path prefix

### 3. What is your entire Caddyfile?
```text
http://test3.pjeby.com/XXX-foo {
    proxy / http://fpm_server_1/xxx {
        transparent
    }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy --conf /etc/Caddyfile --log stdout`

### 6. What did you expect to see?

Caddy should recognize requests to test3.pjeby.com/XXX-foo -- but it lowercases `XXX-foo` to `xxx-foo` and only accepts the lowercase version of the path.

### 7. What did you see instead (give full error messages and/or log)?
`caddy_1    | 2017/08/30 03:36:51 https://test3.pjeby.com/xxx-foo `

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Create a caddyfile with an address ending with a mixed-case path, then try to access that path.  Caddy's log shows a lowercased version, and responds to the mixed case version with a 404, saying that the site "is not served on this interface".

The relevant code is likely [here](https://github.com/mholt/caddy/blob/4b1b329edb014f1064570d3aa77de9e7e48666e6/caddyhttp/httpserver/plugin.go#L106), where `key` is lowercased before passing it to `standardizeAddress()`, instead of standardizing the original path as given.

**Comment by francislavoie** [comment] 2017-08-30 04:39
I think this is a duplicate of https://github.com/mholt/caddy/issues/1517 ?

**Comment by mholt** [comment] 2017-08-30 05:30
^ Yep, looks like it.

**Closed by mholt** 2017-08-30 05:30 UTC

**Comment by pjeby** [comment] 2017-08-30 05:58
My bad; I searched for "lowercase" and didn't find it.

**Comment by francislavoie** [comment] 2017-08-30 06:01
Haha! I searched for "uppercase".

**Comment by francislavoie** [comment] 2017-08-30 06:03
If you didn't spot it, there was this PR https://github.com/mholt/caddy/pull/1522 which was a proposed fix, but it got closed due to inactivity. If you'd like to work on continuing that fix, would be awesome 😄
