### ISSUE TITLE
Caddy restart loop after hitting Let's Encrypt rate limit on a single vhost

### ISSUE THREAD

**Issue by pgporada** [mholt/caddy#1713] opened 2017-06-15 04:11 UTC
### 1. What version of Caddy are you using (`caddy -version`)?
`Caddy 0.10.3`

### 2. What are you trying to do?
Configure a bunch of vhosts into a single `Caddyfile`.

### 3. What is your entire Caddyfile? 
Currently this is my file. It's working as intended for me. However, I did notice that if you have a misconfigured vhost and you restart caddy enough trying to test your config that you will trigger a rate limit from Let's Encrypt. This is no fault of Let's Encrypt, it's a fault of my own for continuously restarting and having a broken vhost. However, I think it might be a good idea to warn the user something along the lines of, `"Your vhost is broken and you should feel bad. Your daemon is going to stop wanting to restart because your broken vhost couldn't get validated causing you much "fun" on a Thursday night!"` It might be useful to even stop trying to get a cert validated if the caddy daemon could somehow detect that it's restarted far too many times so as to avoid triggering the Let's Encrypt rate limit for any domain(s) that don't yet have a certificate.
```text
www.philporada.com, www.mytallguy.com, mytallguy.com, www.mitallguy.com, mitallguy.com {
    redir https://philporada.com{uri}
}

philporada.com {
    root /var/www/domains/philporada.com/www/htdocs/
    tls philporada@gmail.com
}

www.c6h12o6.sh {
    redir https://c6h12o6.sh{uri}
}

c6h12o6.sh {
    root /var/www/domains/c6h12o6.sh/www/htdocs/
    tls philporada@gmail.com
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`systemctl start caddy`

### 6. What did you expect to see?
My webpage :D

### 7. What did you see instead (give full error messages and/or log)?
```
[root@leadskeleton /etc/caddy]# systemctl status caddy
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/usr/lib/systemd/system/caddy.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-06-14 23:57:47 EDT; 3s ago
     Docs: https://caddyserver.com/docs
 Main PID: 14478 (caddy)
   CGroup: /system.slice/caddy.service
           └─14478 /usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp

Jun 14 23:57:47 leadskeleton systemd[1]: Started Caddy HTTP/2 web server.
Jun 14 23:57:47 leadskeleton systemd[1]: Starting Caddy HTTP/2 web server...
Jun 14 23:57:48 leadskeleton caddy[14478]: Activating privacy features...2017/06/14 23:57:48 [INFO][www.c6h12o6.sh] acme: Obtaining bundled SAN certificate
Jun 14 23:57:49 leadskeleton caddy[14478]: 2017/06/14 23:57:49 error on 'service' hook: [www.c6h12o6.sh] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimite...ns recently.
Jun 14 23:57:50 leadskeleton caddy[14478]: Activating privacy features...2017/06/14 23:57:50 [INFO][www.c6h12o6.sh] acme: Obtaining bundled SAN certificate

[root@leadskeleton /etc/caddy]# systemctl status caddy
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/usr/lib/systemd/system/caddy.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Wed 2017-06-14 23:57:51 EDT; 815ms ago
     Docs: https://caddyserver.com/docs
  Process: 14478 ExecStart=/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp (code=exited, status=1/FAILURE)
 Main PID: 14478 (code=exited, status=1/FAILURE)

Jun 14 23:57:50 leadskeleton systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Jun 14 23:57:50 leadskeleton systemd[1]: Unit caddy.service entered failed state.
Jun 14 23:57:50 leadskeleton systemd[1]: caddy.service failed.
Jun 14 23:57:51 leadskeleton systemd[1]: caddy.service holdoff time over, scheduling restart.
Jun 14 23:57:51 leadskeleton systemd[1]: start request repeated too quickly for caddy.service
Jun 14 23:57:51 leadskeleton systemd[1]: Failed to start Caddy HTTP/2 web server.
Jun 14 23:57:51 leadskeleton systemd[1]: Unit caddy.service entered failed state.
Jun 14 23:57:51 leadskeleton systemd[1]: caddy.service failed.

[root@leadskeleton /etc/caddy]# systemctl status caddy
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/usr/lib/systemd/system/caddy.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Wed 2017-06-14 23:57:51 EDT; 1s ago
     Docs: https://caddyserver.com/docs
  Process: 14478 ExecStart=/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp (code=exited, status=1/FAILURE)
 Main PID: 14478 (code=exited, status=1/FAILURE)

Jun 14 23:57:50 leadskeleton systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Jun 14 23:57:50 leadskeleton systemd[1]: Unit caddy.service entered failed state.
Jun 14 23:57:50 leadskeleton systemd[1]: caddy.service failed.
Jun 14 23:57:51 leadskeleton systemd[1]: caddy.service holdoff time over, scheduling restart.
Jun 14 23:57:51 leadskeleton systemd[1]: start request repeated too quickly for caddy.service
Jun 14 23:57:51 leadskeleton systemd[1]: Failed to start Caddy HTTP/2 web server.
Jun 14 23:57:51 leadskeleton systemd[1]: Unit caddy.service entered failed state.
Jun 14 23:57:51 leadskeleton systemd[1]: caddy.service failed.
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Misconfigure your vhost such that Let's Encrypt is unable to validate your domain. Restart caddy to pick up the changes in the Caddyfile. Then watch the caddy service status tailspin into a fail state.

**Comment by mholt** [comment] 2017-06-15 04:24
Thanks for answering the issue template. In this case, as you said, the problem is squarely on the user for using Let's Encrypt's production endpoint for testing. The [Caddy docs](https://caddyserver.com/docs/automatic-https#testing) *and* the Let's Encrypt docs clearly recommend using the LE staging endpoint for testing, especially when using init systems or process managers.

> a fault of my own for continuously restarting

... yeah... never do that ...

Sorry, but this is not something broken in Caddy, so I'm closing this.

**Closed by mholt** 2017-06-15 04:24 UTC
