### ISSUE TITLE
linux arm: Invalid memory address or null pointer dereference panic when using fastcgi

### ISSUE THREAD

**Issue by Flameborn** [mholt/caddy#1788] opened 2017-07-28 11:18 UTC
This is via vanilla Caddy 0.10.5 on a Raspberry pi 3 (arm v7), running a 32 bit Arch linux. Earlier versions, such as 0.10.4 work fine.

PHP version: 7.1.7

When using FastCGI with php-fm, Caddy generates an Internal server error (http 500). Additionally, a panic is logged:

[PANIC /] /usr/local/go/src/sync/atomic/asm_linux_arm.s:109 - runtime error: invalid memory address or nil pointer dereference

Caddy file:

```text
mysite.com {
gzip
root /var/www/mysite.com
fastcgi / /run/php-fpm/php-fpm.sock php
}
```

**Comment by abiosoft** [comment] 2017-07-28 11:36
Can you enable error logs and share the log output.

**Comment by Rurik19** [comment] 2017-07-28 12:03
duplicate of https://github.com/mholt/caddy/issues/1786

**Comment by Flameborn** [comment] 2017-07-28 13:55
@abiosoft Other than the panic, nothing else is logged.

**Comment by abiosoft** [comment] 2017-07-28 14:00
If that is indeed your entire Caddyfile, you need to add the following line to see error logs.
```
errors stdout
```

**Comment by Flameborn** [comment] 2017-07-28 14:03
I did. Other than the panic, which I have posted earlier, nothing else is logged.

**Comment by abiosoft** [comment] 2017-07-28 15:23
What does your php source code looks like. Does it fail for even a basic `echo "Hello world"` ?
Trying to get necessary info to reproduce this.

**Comment by Flameborn** [comment] 2017-07-28 15:27
I put a simple test.php with an echo at the web root and indeed, Caddy panics with it as well.

**Comment by abiosoft** [comment] 2017-07-28 15:47
This has been successfully reproduced. A fix should follow.

**Comment by Flameborn** [comment] 2017-07-28 15:59
Thank you very much. Out of curiosity, is this ARM specific?

**Comment by abiosoft** [comment] 2017-07-28 16:11
@Flameborn @Rurik19 Can you build from source? If yes, kindly verify if this patch fixes it.
https://github.com/mholt/caddy/pull/1789
Otherwise, I can produce a binary for you to test.

**Comment by Flameborn** [comment] 2017-07-28 17:35
It still breaks for me, however it is possible that ‘go get’ is not updating my packages properly, via the -u flag.

**Comment by mholt** [comment] 2017-07-28 17:35
You'll have to checkout the branch with the fix and build that.

**Comment by abiosoft** [comment] 2017-07-28 17:43
You may need to `rm -r $GOPATH/src/github.com/mholt/caddy` if it exists. Then do the following.
```
git clone https://github.com/abiosoft/caddy $GOPATH/src/github.com/mholt/caddy
go get -v github.com/mholt/caddy
```

**Comment by Flameborn** [comment] 2017-07-28 17:43
Confirmed, this works here. Thank you very much!

**Comment by Flameborn** [comment] 2017-07-28 17:46
Thank you! It took me a while 🙁

**Comment by mholt** [comment] 2017-07-28 17:52
Excellent! No problem @Flameborn, I really, really appreciate that you confirmed it! Will issue a release soon.

**Closed** 2017-07-28 17:53 UTC
Labels: bug

**Comment by Rurik19** [comment] 2017-07-30 15:38
I cannot build from sources yet, and I stay with 0.10.4 and wait for release.

**Comment by mholt** [comment] 2017-07-30 15:40
@Rurik19 It's already released, 0.10.6 ;)

**Comment by Rurik19** [comment] 2017-07-30 15:42
Thanks! going to test it.

**Comment by Rurik19** [comment] 2017-07-31 04:46
It works! Thanks again!
