### ISSUE TITLE
quic_go update?

### ISSUE THREAD

**Issue by neilstuartcraig** [mholt/caddy#1895] opened 2017-09-29 08:33 UTC
Hi all

I'm just wondering if there's a plan to update `quic_go` such that we get a version of quic (39) which works with Chrome stable? 

Fully realise that quic support is experimental and i'm not hassling, just keen to see when it's likely.

Cheers :-)

**Comment by lbguilherme** [comment] 2017-09-29 13:24
`quic_go` 0.6.0 is still unreleased: https://github.com/lucas-clemente/quic-go/blob/master/Changelog.md

Duplicate of #1858

**Closed** 2017-09-29 13:43 UTC
