### ISSUE TITLE
does caddy(as a proxy) support quic when it  connect to upstream  

### ISSUE THREAD

**Issue by keith2008** [mholt/caddy#1439] opened 2017-02-16 03:48 UTC
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.4

### 2. What are you trying to do?
client->proxy server (caddy)->origin server(caddy)
to test  caddy(as a proxy) whether support quic when it  connect to upstream 

### 3. What is your entire Caddyfile?
proxy server Caddyfile
cxdtest.com:443 {
  tls nginx.crt nginx.key
   proxy / https://192.168.98.181 { 
     header_upstream Host cxdtest.com
     insecure_skip_verify 
   }
  #  root /var/www/html
    log    /var/log/access.log
    errors {
    log /var/log/error.log
    }
}
------------------
origin server Caddyfile
cxdtest.com:443 {
  tls nginx.crt nginx.key
    root /var/www/html
    log    /var/log/access.log
    errors {
    log /var/log/error.log
    }
}
### 4. How did you run Caddy (give the full command and describe the execution environment)?
proxy server
caddy -quic
-------------
origin server
caddy -quic

### 5. What did you expect to see?
proxy to upstream communication with quic

### 6. What did you see instead (give full error messages and/or log)?
when i pick up the communication packets between proxy and origin,i can't see any packet with  quic protocol.

**Comment by mholt** [comment] 2017-02-16 04:32
No, I think right now Caddy is only a QUIC server. But I see the QUIC client was recently implemented upstream, so we could look into adding this feature. I'm not quite sure how to go about it right now...

**Comment by mholt** [comment] 2017-02-16 05:48
Oh, this is a duplicate of #999. Let's redirect to that.

**Closed by mholt** 2017-02-16 05:48 UTC
Labels: feature request
