### ISSUE TITLE
HTTP-01, failed to get certificate: acme ; [..]/.well-known/acme-challenge not handled

### ISSUE THREAD

**Issue by Alex131089** [mholt/caddy#2121] opened 2018-04-17 18:37 UTC
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.12

### The story
I'm using Caddy as a reverse-proxy (no tricky configuration).
Today, using 0.10.4, I wanted to try to use the `-https-port` option with a forwarding for 443 (using `sslh`, which does a rewrite of the source ip if that matters) and I was going to report an issue because the HTTP to HTTPS redirect was using this port instead of the standard/forwarded port, but it seems that's what https://github.com/mholt/caddy/commit/a03eba6fbc2770ef6bbe7defa184ec4a6817f0c2 is trying to fix. 

So I updated from 0.10.4 to 0.10.12 to test, but the server won't start anymore as the certificat retrieval fails: 
```
Apr 17 20:03:50 host systemd[1]: Starting Caddy HTTP/2 web server...
Apr 17 20:03:50 host systemd[1]: Started Caddy HTTP/2 web server.
Apr 17 20:03:51 host caddy[25494]: Activating privacy features... 2018/04/17 20:03:51 [INFO][--] acme: Obtaining bundled SAN certificate
Apr 17 20:03:52 host caddy[25494]: 2018/04/17 20:03:52 [INFO][--] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/--
Apr 17 20:03:52 host caddy[25494]: 2018/04/17 20:03:52 [INFO][--] acme: Trying to solve HTTP-01
Apr 17 20:03:57 host caddy[25494]: [--] failed to get certificate: acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Invalid response from http://--/.well-known/acme-challenge/--: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
Apr 17 20:03:57 host caddy[25494]: <html><head>
Apr 17 20:03:57 host caddy[25494]: <title>404 Not Found</title>
Apr 17 20:03:57 host caddy[25494]: </head><body>
Apr 17 20:03:57 host caddy[25494]: <h1>Not Found</h1>
Apr 17 20:03:57 host caddy[25494]: <p"
Apr 17 20:03:57 host systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
```

It seems that the challenge fails because Caddy forwards it to the destination server, instead of handling it (maybe because of the source ip rewrite ?). If I remove the forwarding and the `-https-port` option, the retrieval works again.

**Comment by elcore** [comment] 2018-04-17 18:44
Hello,

please take a few minutes to carefully answer our issue template! We need those informations to help you!

**Comment by mholt** [comment] 2018-04-17 18:49
I only have a moment as I go out the door, but I'll just real quickly remind you to use the staging endpoint or risk getting rate-limited ❗️ -- my only other thought is that Caddy will only solve challenges for domains it knows it is serving. But yes, please fill out the issue template.

**Comment by Alex131089** [comment] 2018-04-17 19:08
I was a bit fast by affirming `If I remove the forwarding and the -https-port option, the retrieval works again` it seems; it doesn't and I get really weird logs:
```
Apr 17 20:49:46 host caddy[4236]: Activating privacy features... 2018/04/17 20:49:46 [INFO][dom1.tld] acme: Obtaining bundled SAN certificate
Apr 17 20:49:46 host caddy[4236]: 2018/04/17 20:49:46 [INFO][] Certificate written to disk: /etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/.crt
Apr 17 20:49:46 host caddy[4236]: 2018/04/17 20:49:46 [INFO][dom2.tld] acme: Obtaining bundled SAN certificate
Apr 17 20:49:47 host caddy[4236]: 2018/04/17 20:49:47 [INFO][] Certificate written to disk: /etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/.crt
Apr 17 20:49:47 host caddy[4236]: 2018/04/17 20:49:47 [INFO][sub2.dom2.tld] acme: Obtaining bundled SAN certificate
Apr 17 20:49:47 host caddy[4236]: 2018/04/17 20:49:47 [INFO][] Certificate written to disk: /etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/.crt
Apr 17 20:49:48 host caddy[4236]: 2018/04/17 20:49:48 [INFO][sub1.dom2.tld] acme: Obtaining bundled SAN certificate
Apr 17 20:49:48 host caddy[4236]: 2018/04/17 20:49:48 [INFO][] Certificate written to disk: /etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/.crt
Apr 17 20:49:48 host caddy[4236]: open /etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/dom1.tld/dom1.tld.crt: no such file or directory
```

The part of the conf related to thoses domains:
```
dom1.tld,
dom3.tld,
sub1.dom3.tld,
sub2.dom3.tld,
sub3.dom3.tld,
sub4.dom3.tld,
dom2.tld,
sub1.dom2.tld,
sub2.dom2.tld,
*.dom1.tld:80, # No ssl for wildcards
*.dom2.tld:80,
*.sub1.dom2.tld:80,
*.*.dom2.tld:80
{
        tls (email)
        gzip
        header / -Server
        proxy / (dst) {
                transparent
                websocket
        }
        log / syslog "{hostonly} {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\""
}
```

Env is debian 8.8, systemd, started with `/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp`

**Comment by Alex131089** [comment] 2018-04-17 19:16
And that's not consistent, I can have the previous error again (maybe related to the fact I tried to add `except .well-known/acme-challenge` / `except /.well-known/acme-challenge` to the proxy block .. or not, I'm not sure, need to try again):
```
Apr 17 21:06:29 host caddy[7872]: Activating privacy features... 2018/04/17 21:06:29 [INFO][dom1.tld] acme: Obtaining bundled SAN certificate
Apr 17 21:06:30 host caddy[7872]: 2018/04/17 21:06:30 [INFO][dom1.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/--
Apr 17 21:06:30 host caddy[7872]: 2018/04/17 21:06:30 [INFO][dom1.tld] acme: Could not find solver for: dns-01
Apr 17 21:06:30 host caddy[7872]: 2018/04/17 21:06:30 [INFO][dom1.tld] acme: Trying to solve HTTP-01
Apr 17 21:06:35 host caddy[7872]: [dom1.tld] failed to get certificate: acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Invalid response from http://dom1.tld/.well-known/acme-challenge/--: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
Apr 17 21:06:35 host caddy[7872]: <html><head>
Apr 17 21:06:35 host caddy[7872]: <title>404 Not Found</title>
Apr 17 21:06:35 host caddy[7872]: </head><body>
Apr 17 21:06:35 host caddy[7872]: <h1>Not Found</h1>
Apr 17 21:06:35 host caddy[7872]: <p"
Apr 17 21:06:35 host systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
```

Well, I rolled back and I give up for today.

**Comment by mholt** [comment] 2018-04-17 19:17
Ah, you've hit a bug that was fixed last night in an upstream dependency. We'll be rolling out an update soon that fixes it! Sorry for the trouble.

(Closing, as this is basically a duplicate issue)

**Closed by mholt** 2018-04-17 19:17 UTC

**Comment by Alex131089** [comment] 2018-04-17 19:53
Thank you! I'll follow that.
Sorry about the template.

**Comment by Alex131089** [comment] 2018-04-25 10:57
Can the issue be reopened? @mholt

The initial issue (not the empty domain) is still present, and that's not related to `-https-port`. I just upgraded from `0.10.4` (working) to `0.10.14` without touching the configuration nor the command line.

I'll update the first post following the template (and move the logs from here to the first post).

Here's the full log & config:
```
# systemctl daemon-reload; service caddy restart; journalctl -fu caddy
-- Logs begin at Sat 2018-04-21 00:46:38 CEST. --
Apr 25 12:40:29 my-host systemd[1]: Stopping Caddy HTTP/2 web server...
Apr 25 12:40:29 my-host caddy[1734]: 2018/04/25 12:40:29 [INFO] SIGTERM: Terminating process
Apr 25 12:40:29 my-host systemd[1]: Starting Caddy HTTP/2 web server...
Apr 25 12:40:30 my-host systemd[1]: Started Caddy HTTP/2 web server.
Apr 25 12:40:31 my-host caddy[32189]: Activating privacy features... 2018/04/25 12:40:31 [INFO][dom1.tld] acme: Obtaining bundled SAN certificate
Apr 25 12:40:31 my-host caddy[32189]: 2018/04/25 12:40:31 [INFO][dom1.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/ClgNW33NvJr5v2Qg_p4IeEPY2I16LGIQ4i9SrPO8q9g
Apr 25 12:40:31 my-host caddy[32189]: 2018/04/25 12:40:31 [INFO][dom1.tld] acme: Could not find solver for: dns-01
Apr 25 12:40:31 my-host caddy[32189]: 2018/04/25 12:40:31 [INFO][dom1.tld] acme: Trying to solve HTTP-01
Apr 25 12:40:37 my-host caddy[32189]: [dom1.tld] failed to get certificate: acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Invalid response from http://dom1.tld/.well-known/acme-challenge/1S-gGV6h_Gn8idF3pegoPVlMjjaRG1I3eNJd7PbeY3Q: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
Apr 25 12:40:37 my-host caddy[32189]: <html><head>
Apr 25 12:40:37 my-host caddy[32189]: <title>404 Not Found</title>
Apr 25 12:40:37 my-host caddy[32189]: </head><body>
Apr 25 12:40:37 my-host caddy[32189]: <h1>Not Found</h1>
Apr 25 12:40:37 my-host caddy[32189]: <p"
Apr 25 12:40:37 my-host systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Apr 25 12:40:37 my-host systemd[1]: Unit caddy.service entered failed state.
Apr 25 12:40:37 my-host systemd[1]: caddy.service holdoff time over, scheduling restart.
Apr 25 12:40:37 my-host systemd[1]: Stopping Caddy HTTP/2 web server...
Apr 25 12:40:37 my-host systemd[1]: Starting Caddy HTTP/2 web server...
Apr 25 12:40:37 my-host systemd[1]: Started Caddy HTTP/2 web server.
Apr 25 12:40:38 my-host caddy[32215]: Activating privacy features... 2018/04/25 12:40:38 [INFO][dom1.tld] acme: Obtaining bundled SAN certificate
Apr 25 12:40:38 my-host caddy[32215]: 2018/04/25 12:40:38 [INFO][dom1.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/8P1FoEoiQXB7Kd9bPej2hVCn-h2yYQcuNQkMqHVbWFM
Apr 25 12:40:38 my-host caddy[32215]: 2018/04/25 12:40:38 [INFO][dom1.tld] acme: Trying to solve HTTP-01
Apr 25 12:40:44 my-host caddy[32215]: [dom1.tld] failed to get certificate: acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Invalid response from http://dom1.tld/.well-known/acme-challenge/KvRG3dchdo1YLAWGBBuMxgweWEb7G7AB45qGHcSsr3A: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
Apr 25 12:40:44 my-host caddy[32215]: <html><head>
Apr 25 12:40:44 my-host caddy[32215]: <title>404 Not Found</title>
Apr 25 12:40:44 my-host caddy[32215]: </head><body>
Apr 25 12:40:44 my-host caddy[32215]: <h1>Not Found</h1>
Apr 25 12:40:44 my-host caddy[32215]: <p"
Apr 25 12:40:44 my-host systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Apr 25 12:40:44 my-host systemd[1]: Unit caddy.service entered failed state.
Apr 25 12:40:44 my-host systemd[1]: caddy.service holdoff time over, scheduling restart.
Apr 25 12:40:44 my-host systemd[1]: Stopping Caddy HTTP/2 web server...
Apr 25 12:40:44 my-host systemd[1]: Starting Caddy HTTP/2 web server...
Apr 25 12:40:44 my-host systemd[1]: Started Caddy HTTP/2 web server.
Apr 25 12:40:45 my-host caddy[32253]: Activating privacy features... 2018/04/25 12:40:45 [INFO][dom1.tld] acme: Obtaining bundled SAN certificate
Apr 25 12:40:45 my-host caddy[32253]: 2018/04/25 12:40:45 [INFO][dom1.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/KIawtrYgbMprt5DnzLcFDEEDOKaVvxiV_Bo7PqrT3uI
Apr 25 12:40:45 my-host caddy[32253]: 2018/04/25 12:40:45 [INFO][dom1.tld] acme: Could not find solver for: dns-01
Apr 25 12:40:45 my-host caddy[32253]: 2018/04/25 12:40:45 [INFO][dom1.tld] acme: Trying to solve HTTP-01
Apr 25 12:40:51 my-host caddy[32253]: [dom1.tld] failed to get certificate: acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Invalid response from http://dom1.tld/.well-known/acme-challenge/Mf3048BQrPFtz4p7MeeEgRjh9e5BcNEGAQBLAIWx1WY: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
Apr 25 12:40:51 my-host caddy[32253]: <html><head>
Apr 25 12:40:51 my-host caddy[32253]: <title>404 Not Found</title>
Apr 25 12:40:51 my-host caddy[32253]: </head><body>
Apr 25 12:40:51 my-host caddy[32253]: <h1>Not Found</h1>
Apr 25 12:40:51 my-host caddy[32253]: <p"
Apr 25 12:40:51 my-host systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Apr 25 12:40:51 my-host systemd[1]: Unit caddy.service entered failed state.
Apr 25 12:40:51 my-host systemd[1]: caddy.service holdoff time over, scheduling restart.
Apr 25 12:40:51 my-host systemd[1]: Stopping Caddy HTTP/2 web server...
Apr 25 12:40:51 my-host systemd[1]: Starting Caddy HTTP/2 web server...
Apr 25 12:40:51 my-host systemd[1]: Started Caddy HTTP/2 web server.
Apr 25 12:40:52 my-host caddy[32278]: Activating privacy features... 2018/04/25 12:40:52 [INFO][dom1.tld] acme: Obtaining bundled SAN certificate
Apr 25 12:40:52 my-host caddy[32278]: 2018/04/25 12:40:52 [INFO][dom1.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/Zu8LdQ6Um02NJOeCpQE8i3wir-D5a19GMjdvuYlqQF4
Apr 25 12:40:52 my-host caddy[32278]: 2018/04/25 12:40:52 [INFO][dom1.tld] acme: Trying to solve HTTP-01
Apr 25 12:40:58 my-host caddy[32278]: [dom1.tld] failed to get certificate: acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Invalid response from http://dom1.tld/.well-known/acme-challenge/Np-irffM3ng1MfLxxUJnFXI43536V0_388jOhftRLww: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
Apr 25 12:40:58 my-host caddy[32278]: <html><head>
Apr 25 12:40:58 my-host caddy[32278]: <title>404 Not Found</title>
Apr 25 12:40:58 my-host caddy[32278]: </head><body>
Apr 25 12:40:58 my-host caddy[32278]: <h1>Not Found</h1>
Apr 25 12:40:58 my-host caddy[32278]: <p"
Apr 25 12:40:58 my-host systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Apr 25 12:40:58 my-host systemd[1]: Unit caddy.service entered failed state.
Apr 25 12:40:58 my-host systemd[1]: caddy.service holdoff time over, scheduling restart.
Apr 25 12:40:58 my-host systemd[1]: Stopping Caddy HTTP/2 web server...
Apr 25 12:40:58 my-host systemd[1]: Starting Caddy HTTP/2 web server...
Apr 25 12:40:58 my-host systemd[1]: Started Caddy HTTP/2 web server.
Apr 25 12:40:59 my-host caddy[32310]: Activating privacy features... 2018/04/25 12:40:59 [INFO][dom1.tld] acme: Obtaining bundled SAN certificate
Apr 25 12:40:59 my-host caddy[32310]: 2018/04/25 12:40:59 [INFO][dom1.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/6hvybDwINHUcTR4BaNAk5Mo4hRgskarB3w15WAM362c
Apr 25 12:40:59 my-host caddy[32310]: 2018/04/25 12:40:59 [INFO][dom1.tld] acme: Could not find solver for: dns-01
Apr 25 12:40:59 my-host caddy[32310]: 2018/04/25 12:40:59 [INFO][dom1.tld] acme: Trying to solve HTTP-01
Apr 25 12:41:05 my-host caddy[32310]: [dom1.tld] failed to get certificate: acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Invalid response from http://dom1.tld/.well-known/acme-challenge/Nd4iuoMgDSAk-i9u1kHJ-IqZQ77tsaYL_Sv92QYJbg0: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
Apr 25 12:41:05 my-host caddy[32310]: <html><head>
Apr 25 12:41:05 my-host caddy[32310]: <title>404 Not Found</title>
Apr 25 12:41:05 my-host caddy[32310]: </head><body>
Apr 25 12:41:05 my-host caddy[32310]: <h1>Not Found</h1>
Apr 25 12:41:05 my-host caddy[32310]: <p"
Apr 25 12:41:05 my-host systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Apr 25 12:41:05 my-host systemd[1]: Unit caddy.service entered failed state.
Apr 25 12:41:05 my-host systemd[1]: caddy.service holdoff time over, scheduling restart.
Apr 25 12:41:05 my-host systemd[1]: Stopping Caddy HTTP/2 web server...
Apr 25 12:41:05 my-host systemd[1]: Starting Caddy HTTP/2 web server...
Apr 25 12:41:05 my-host systemd[1]: caddy.service start request repeated too quickly, refusing to start.
Apr 25 12:41:05 my-host systemd[1]: Failed to start Caddy HTTP/2 web server.
Apr 25 12:41:05 my-host systemd[1]: Unit caddy.service entered failed state.
^C
```

```
dom1.tld,
dom2.tld,
sub1.dom2.tld,
sub2.dom2.tld,
sub3.dom2.tld,
sub4.dom2.tld,
dom3.tld,
sub1.dom3.tld,
sub2.dom3.tld,
*.dom1.tld:80, # No ssl for wildcards
*.dom3.tld:80,
*.sub1.dom3.tld:80,
*.*.dom3.tld:80
{
        tls my@email.tld
        gzip
        header / -Server
        proxy / 10.11.12.13 {
                transparent
                websocket
        }
        log / syslog "{hostonly} {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\""
}

s1.s1.dom4.tld,
s2.s1.dom4.tld
{
        tls my@email.tld {
                clients /etc/caddy/my-host.pem
        }
        gzip
        proxy / 10.11.12.13 {
                transparent
                websocket
        }
        log / syslog "{hostonly} {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\""
}


s3.s1.dom4.tld {
        tls my@email.tld {
                clients /etc/caddy/my-host.pem
        }
        gzip
        proxy / https://10.11.12.14:8006 {
                insecure_skip_verify
                transparent
                websocket
        }
        log / syslog "{hostonly} {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\""
}

s4.s1.dom4.tld {
        tls my@email.tld {
                clients /etc/caddy/my-host.pem
        }
        gzip
        proxy / http://10.11.12.15:8000 {
                transparent
                websocket
        }
        log / syslog "{hostonly} {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\""
}

s5.s1.dom4.tld {
        tls my@email.tld {
                clients /etc/caddy/my-host.pem
        }
        gzip
        proxy / http://10.11.12.16:9000 {
                transparent
                websocket
        }
        log / syslog "{hostonly} {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\""
}

s6.s1.dom4.tld {
        tls my@email.tld {
                clients /etc/caddy/my-host.pem
        }
        gzip
        proxy / http://10.11.12.17:9091 {
                transparent
                websocket
        }
        log / syslog "{hostonly} {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\""
}

s7.s1.dom4.tld,
*.s7.s1.dom4.tld {
        tls my@email.tld {
                max_certs 10
        }
        gzip
        ipfilter / {
                rule allow
                ip 10.12.13.14
                ip 10.12.13.15
                ip 10.12.13.16
        }
        proxy / http://10.11.12.18 {
                transparent
                websocket
        }
        log / syslog "{hostonly} {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\""
}
```

**Comment by Alex131089** [comment] 2018-04-25 11:37
The same with just the `http.ipfilter` plugin. I also updated the systemd unit file with the latest one.
However this last try happily gave me a nice ban for one week 🎉 (yep, you warned me)

**Comment by mholt** [comment] 2018-04-25 14:56
Without knowing your actual domain names, it's going to be near-impossible to debug. 99.99% of the time, these exact errors are caused by an infrastructure misconfiguration, not a bug in Caddy.

**Comment by Alex131089** [comment] 2018-04-25 15:30
> Without knowing your actual domain names, it's going to be near-impossible to debug.

The names are replaced (correctly & coherently in the last config+log I posted) but they are simple [a-z0-9]{3,8} names and the structure (dots/subs) is not touched. This is the full configuration file.
The first domain `dom1.tld`, the (first?) failing one, is like `1m9.de`, if the fact it start&end by a number can be important.

> 99.99% of the time, these exact errors are caused by an infrastructure misconfiguration, not a bug in Caddy.

Caddy is running as a service on a proxmox hypervisor, acting as a reverse-proxy for the VMs (and proxmox itself). It is receiving the requests directly (I mentionned `sslh` last week, I got things mixed up in the hurry, today I tried a simple update from an old, known, working configuration), it is the "head", so I can't see what could be interfering :/

Eventually, did I missed an evolution in the configuration, causing Caddy to forward the `/.well-known/acme-challenge/` requests to the backend server instead of handling them?

**Comment by mholt** [comment] 2018-04-25 15:43
> The names are replaced (correctly & coherently in the last config+log I posted) but they are simple [a-z0-9]{3,8} names and the structure (dots/subs) is not touched. This is the full configuration file.
The first domain dom1.tld, the (first?) failing one, is like 1m9.de, if the fact it start&end by a number can be important.

Thanks, but that's not the point: to be helpful in diagnosing issues, it is often required to look up DNS configuration or other information about a _specific_ domain name, not the regex it matches. :) This is why we are so often unable to help people and people complain that our community is unhelpful: they don't fill out the issue template correctly, because everyone insists on redacting their domain names that go into public CT logs anyway, and we can't help them.

In this case, I need to be able to go to your domain in my browser and ensure that Caddy is the server that is responding to requests. If it's not for me, then it's not for LE either, and that is 99% of the time the problem that people have.
