### ISSUE TITLE
Log duplicated to ./access.log

### ISSUE THREAD

**Issue by PetterS** [mholt/caddy#1529] opened 2017-03-21 21:28 UTC
https://forum.caddyserver.com/t/caddy-runs-out-of-file-descriptors/1659/7 has the Caddyfile and configuration.

Caddy logs everything to ./access.log as well, even though it is not in the Caddyfile.

**Comment by mholt** [comment] 2017-03-21 21:29
@julianvmodesto Would you have a moment to look at this? I was able to reproduce this behavior.

**Comment by Baughn** [comment] 2017-03-23 00:08
Can confirm. This leads to failure on startup if CWD isn't inside a writeable directory, even if nothing in the configuration file writes to CWD.

**Comment by Tweenagedream** [comment] 2017-03-28 07:43
Pretty sure this is caused by the nested rotate, flattening those options with #1379 I believe fixes the issue (kinda)

Technically you can still put
rotate {
}
tags in there even if they don't do anything and cause this behavior. 

unknown whats seem to be silently ignored: https://github.com/mholt/caddy/blob/60415c8d0e365189a6014b610ef72c8a8a84b2e7/caddyhttp/log/setup.go#L44

You can actually add any block at all inside of log on two separate lines:
log ./log/stuff.log {
  thisblockwillmakeitlogtocwd {
  }
}

If interested in fixing this patch would look something like:
diff --git a/caddyhttp/log/setup.go b/caddyhttp/log/setup.go
index 2366aec..e5e5e09 100644
--- a/caddyhttp/log/setup.go
+++ b/caddyhttp/log/setup.go
@@ -30,11 +30,11 @@ func logParse(c *caddy.Controller) ([]*Rule, error) {
 
        for c.Next() {
                args := c.RemainingArgs()

                var logRoller *httpserver.LogRoller
                logRoller = httpserver.DefaultLogRoller()

+               wasNested := false
                for c.NextBlock() {
+                       wasNested = true
                        what := c.Val()
                        if !c.NextArg() {
                                return nil, c.ArgErr()
@@ -49,7 +49,9 @@ func logParse(c *caddy.Controller) ([]*Rule, error) {
                                }
                        }
                }

+               if wasNested {
+                       c.Next()
+               }
                if len(args) == 0 {
                        // Nothing specified; use defaults
                        rules = appendEntry(rules, "/", &Entry{

I can make a PR if it's worth it...

**Comment by Baughn** [comment] 2017-03-28 12:01
My (autogenerated) Caddyfile looks like this: http://sprunge.us/DOLA

...but this still produces an access.log. In fact, all requests to any server defined there gets logged *three times* to access.log, so it looks like this:
```
104.132.8.77 - [28/Mar/2017:13:00:51 +0100] "GET / HTTP/2.0" 200 10442
104.132.8.77 - [28/Mar/2017:13:00:51 +0100] "GET / HTTP/2.0" 200 10442
104.132.8.77 - [28/Mar/2017:13:00:51 +0100] "GET / HTTP/2.0" 200 10442
104.132.8.77 - [28/Mar/2017:13:00:51 +0100] "GET /favicon.ico HTTP/2.0" 404 14
104.132.8.77 - [28/Mar/2017:13:00:51 +0100] "GET /favicon.ico HTTP/2.0" 404 14
104.132.8.77 - [28/Mar/2017:13:00:51 +0100] "GET /favicon.ico HTTP/2.0" 404 14
```

...it's a bit concerning. The log entries also end up in the INFO-log I asked Caddy to log to, non-duplicated.

**Comment by tobya** [comment] 2017-03-28 14:48
@Tweenagedream a PR would be great and then we can work on getting it merged if it fixes the issue.

**Comment by Tweenagedream** [comment] 2017-03-30 01:49
It looks like @Baughn 's issue is also fixed with #1379

The Caddyfile would look similar, the errors section would be replaced with something like:
errors {
     * /var/log/caddy/ar-innna.brage.info.ERROR
       rotate_size 100
       rotate_age 365
       rotate_keep 20
   }

I checked and no access log gets opened with the above config

**Comment by julianvmodesto** [comment] 2017-03-30 02:19
Gonna guess that the bug is that there's an append(rule) in a for loop that's reading directives, if that makes sense.

**Comment by tw4452852** [comment] 2017-04-17 09:00
Because we have use the new roller related options (`rotate_*`), the old one (` rotate { ... }`) should be forbidden.

**Comment by mholt** [comment] 2017-04-17 16:01
I believe this is now fixed. Thanks @tw4452852!

**Closed by mholt** 2017-04-17 16:01 UTC
Labels: bug, help wanted
