### ISSUE TITLE
When i use quic protocol to connect between two caddys, the distal caddy frequently crashed. After restart the distal caddy, how ever the proximal caddy can't connetct to the distal one.I was frustrated，who can tell me how to do?

### ISSUE THREAD

**Issue by neil88** [mholt/caddy#2365] opened 2018-11-22 14:34 UTC
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.1

### 2. What are you trying to do?
Deploy two Caddy
The proximal caddy receives the HTTP request, turns it into quic and sends it to the distal caddy

### 3. What is your entire Caddyfile?
distal caddy
replica.yjp211.com

log ./access.log
errors ./error.log

tls /data/www/cert/fullchain.pem /data/www/cert/privkey.pem
proximal caddy:

10.10.3.202

log ./access.log
errors ./error.log

proxy /quic quic://replica.yjp211.com

### 4. How did you run Caddy (give the full command and describe the execution environment)?
distal caddy
./caddy -conf ./Caddyfile -quic -port 443 &   
 
proximal caddy:
./caddy -conf ./Caddyfile -quic & 

### 5. Please paste any relevant HTTP request(s) here.
curl replica.yjp211.com

### 6. What did you expect to see?
the caddys can run normally

### 7. What did you see instead (give full error messages and/or log)?
the distal caddy frequently crashed. and then restart the distal caddy how ever the proximal caddy can't connetct to the distal one.I was frustrated，who can tell me how to do?
detail:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8b734c]

goroutine 95 [running]:
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto.(*certChain).getCertForSNI(0xc00000c010, 0xc0001d9fa0, 0x10, 0xc0000aeea0, 0x41bc0528, 0x1202eb557d07f300)
    /tmp/gopath_11-13-2001.745329082/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_chain.go:66 +0x6c
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto.(*certChain).GetLeafCert(0xc00000c010, 0xc0001d9fa0, 0x10, 0xc000000000, 0xc0001d9f00, 0x10, 0xc0000aef90, 0x10)
    /tmp/gopath_11-13-2001.745329082/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto/cert_chain.go:51 +0x43
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetupServer).handleMessage(0xc0003ce000, 0xc00019ab00, 0x410, 0x518, 0xc0003b8ab0, 0x1, 0x0, 0x0)
    /tmp/gopath_11-13-2001.745329082/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup_server.go:162 +0x18f
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake.(*cryptoSetupServer).HandleCryptoStream(0xc0003ce000, 0x0, 0x0)
    /tmp/gopath_11-13-2001.745329082/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup_server.go:119 +0x21a
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go.(*session).run.func1(0xc0001ce600)
    /tmp/gopath_11-13-2001.745329082/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/session.go:452 +0x3a
created by github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go.(*session).run
    /tmp/gopath_11-13-2001.745329082/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/session.go:451 +0x8a
^C
[1]+  Exit 2                  ./caddy -conf /usr/local/bin/Caddyfile -quic -port 443

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
According to above message，it's easy to reproduce

**Comment by francislavoie** [comment] 2018-11-22 15:56
I suggest you ask in https://github.com/lucas-clemente/quic-go since this seems to be an issue with QUIC. I'll close this for now, but it can be reopened if new information comes to light.

**Closed by francislavoie** 2018-11-22 15:56 UTC

**Comment by francislavoie** [comment] 2018-11-22 16:00
Actually, this seems to be a duplicate of #2346
