### ISSUE TITLE
Critical informations not recorded to the log file

### ISSUE THREAD

**Issue by hubertbanas** [mholt/caddy#512] opened 2016-01-15 17:56 UTC
Command:

```
/opt/caddy/caddy -agree=true -conf=/etc/caddy/Caddyfile -pidfile=/var/run/caddy/caddy.pid -log=/var/log/caddy/caddy.log
```

This is how the log file looks like:

```
2016/01/15 12:37:01 [WARNING] TLS disabled for http://0.0.0.0:80.
2016/01/15 12:37:01 [WARNING] TLS disabled for http://111.222.333.444:80.
2016/01/15 12:37:07 [INFO] Checking certificates for 28 hosts
```

And the following never makes it to the log file:

```
Activating privacy features...done.
0.0.0.0:80
111.222.333.444:80
aaaaa.com:80
bbbbb.com:80
ccccc.com:80
ddddd.com:80
eeeee.com:80
ffffff.com:80
www.ffffff.com:80
ggggg.com:80
hhhhh.com:80
www.hhhhh.com:80
iiiii.com:80
www.iiiii.com:80
jjjjj.com:80
aaaaa.com:443
bbbbb.com:443
ccccc.com:443
ddddd.com:443
eeeee.com:443
ffffff.com:443
www.ffffff.com:443
ggggg.com:443
hhhhh.com:443
www.hhhhh.com:443
iiiii.com:443
www.iiiii.com:443
jjjjj.com:443

```

Let me know if there is some additional flag I could use to have it in the log with the appropriate time stamp.

**Comment by mholt** [comment] 2016-01-15 18:16
The addresses are normally printed to stdout (not to the log) anyway just to inform the user what sites are up and running. I admit this can probably be improved with regards to logging. And on thinking on #507 I'm considering sending you a modified binary with a LOT more log entries to help pinpoint the cause. If I send that to you and you run it, it will not only help identify the cause of the problem, but also will help you and me know which log lines you find most helpful and informative to add to Caddy. Sound good?

I can send you a modified binary this weekend I think.

**Comment by hubertbanas** [comment] 2016-01-15 18:26
Sounds good.

**Comment by hubertbanas** [comment] 2016-01-16 18:11
I think it would be beneficial to have additional log flag added to Caddy.

Example:
```
-log-detail=low
-log-detail=medium
-log-detail=high
-log-detail=debug
```

**Comment by mholt** [comment] 2016-01-16 18:31
I was thinking this after debugging your issue, although [I share Dave Cheney's sentiment about log levels](http://dave.cheney.net/2015/11/05/lets-talk-about-logging). Ultimately -- and this has been verified after our experience debugging this together -- there are two log levels: logs the user wants to read to stay informed, and logs a developer wants to read to debug. There is nothing particularly useful in between.

So I will probably consider adding a `-debug` flag or something like that.

**Comment by Xe** [comment] 2016-01-16 18:35
:+1:

**Comment by mholt** [comment] 2016-01-18 03:55
So, upon inspection, this is trickier than it sounds. A lot of Go programs just use the default log package -- and justifiably so (I'd rather not use a third party package for something as simple as two log levels). Even net/http uses log, and so does lego/acme, and others. These don't have any notion of 'debug' logs vs. any other kind of log entries, rendering any `-debug` flag useless. Sure, I can control my own log entries, but anything outside of Caddy is counted as... debug? informational? It may not be safe to assume one or the other.

Until we can figure out a good way to solve this -- or introduce better reasoning, at least -- I am not inclined to introduce another log level.

**Comment by tpng** [comment] 2016-01-18 06:15
In my opinion, packages used by Caddy is an implementation detail, and the log output of 3rd party packages can be grouped into the debug category.

So maybe something like
Caddy log: handle as the log flag specified, using a new `log.Logger`
Debug log: using default `log.Logger`, logging to nothing (i.e. `log.SetOutput(os.DevNull)`) or to the stdout if debug flag is on

**Comment by tobya** [comment] 2017-01-15 19:01
@tpng #1210 fixes your original issue by logging the sites started to the log.

There are a couple of other places in the code where items are logged to stdout but not logged to -log destination.  

@mholt would it be of interest to replace these calls ([such as here](https://github.com/mholt/caddy/blob/bedad34b25cfcc67620fa5b854fed020547efbdf/rlimit_posix.go#L19)) to `fmt.PrintLn` or `fmt.Printf` with calls to also `log.PrintLn`  etc so users get all output written to their log.

**Comment by mholt** [comment] 2017-01-15 19:29
I am still thinking about improving/overhauling logging, or at least adding an optional debug log. And I'm not sure we want to conflate fmt and log output...

**Comment by tobya** [comment] 2017-12-20 21:19
I think since #1210 fixes the original issue I will close this.

**Closed by tobya** 2017-12-20 21:19 UTC
Labels: discussion, feature request
