### ISSUE TITLE
PHP error logs

### ISSUE THREAD

**Issue by kaihendry** [mholt/caddy#426] opened 2015-12-12 01:40 UTC
Made a video running through the issue: http://s.natalian.org/2015-12-12/caddy-php-error-log.mp4 @abiosoft 

Currently they appear in `/var/log/php-fpm.log` with a configuration like so: http://s.natalian.org/2015-12-11/Caddyfile

This is my [php-fpm.conf](http://s.natalian.org/2015-12-12/php-fpm.conf) and I only changed two lines from the [Archlinux default config](https://projects.archlinux.org/svntogit/packages.git/tree/trunk/php-fpm.conf.in.patch?h=packages/php).

**Comment by abiosoft** [comment] 2015-12-12 05:45
Thanks for the video :+1: 

I'm looking into the cause and a possible fix. Hopefully, there'll be good news soon.

**Comment by abiosoft** [comment] 2015-12-14 17:47
The fix has been merged.

**Closed by abiosoft** 2015-12-14 17:47 UTC
