### ISSUE TITLE
proxy option `without` is ignored

### ISSUE THREAD

**Issue by tstorch** [mholt/caddy#1631] opened 2017-04-29 17:58 UTC
### 1. What version of Caddy are you using (`caddy -version`)?

Bug in version 0.10 (0.8.3 working just fine)

### 2. What are you trying to do?

Use the 'without' option in the proxy module

### 3. What is your entire Caddyfile?
```text
127.0.0.1:8000 {
	tls off

	browse
	log stdout

	proxy /wikipedia/wiki https://de.wikipedia.org {
		without /wikipedia
	}
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy -conf Caddyfile` on basic Ubuntu 16.04 (x64)

### 5. Please paste any relevant HTTP request(s) here.

No Curl, but browser: `http://127.0.0.1:8000/wikipedia/wiki/Hans_Zimmer`

### 6. What did you expect to see?

The german wikipedia site of Hans Zimmer

### 7. What did you see instead (give full error messages and/or log)?

Wikipedia responding with its 404 page

```
Page not found
/wikipedia/wiki/Hans_Zimmer

We could not find the above page on our servers.
```

Error being the `/wikipedia` not being stripped.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Nothing but the supplied Caddyfile and a browser

**Comment by mholt** [comment] 2017-04-29 18:08
Hi @tstorch - thank you for using the issue template! And I like what you're using Caddy for. :+1: 

This is a duplicate of #1604 I believe. (Definitely don't keep using 0.8.3 though! That's oollldddd.)

**Closed** 2017-04-29 18:09 UTC

**Comment by tstorch** [comment] 2017-04-29 18:55
You're absolutely correct. It's a duplicate.

I'm just starting a new project and thought: Why not update...
I'll just resort to 0.9.5 :cry: 

Thanks for the quick answer and keep up the good work! :+1:
