### ISSUE TITLE
Improve Test Coverage

### ISSUE THREAD

**Issue by j-mcnally** [mholt/caddy#61] opened 2015-05-07 20:28 UTC
Looking at https://travis-ci.org/mholt/caddy it seems a lot of middleware is currently untested?

Is this true?

I am currently learning go, and this could be a good way to cut my teeth.

**Comment by mholt** [comment] 2015-05-07 20:37
Yes indeed. You are _more_ than welcome to write tests. I'm actually writing an example test file for the rewrite middleware right now (because it's simple, a good starting point).

**Comment by mholt** [comment] 2015-05-07 20:56
@j-mcnally See b2ee6638e46973e6d0cf00ece0dbbc08947557fd

**Comment by Karthic-Hackintosh** [comment] 2015-06-04 05:05
I'm keen on writing tests ..What would the best place to start writing tests ?

**Comment by mholt** [comment] 2015-06-04 05:33
@Karthic-Hackintosh Welcome! Any of the middlewares here: https://github.com/mholt/caddy/tree/master/middleware

Each middleware has an associated "setup" file that also needs testing: https://github.com/mholt/caddy/tree/master/config/setup - all these do is parse the configuration and set up the middleware so it's ready to use.

Those would be great places to start.

**Comment by miko-code** [comment] 2015-07-06 18:19
Hi ,
Are you still need help to test stuff ?
Where i can find the example test you wrote ?

**Comment by mholt** [comment] 2015-07-06 18:27
@miko-code We've made lots of progress, but still need help. For example, https://github.com/mholt/caddy/blob/master/config/setup/root.go needs tests. You can see an example of similar tests here (though these are more complicated): https://github.com/mholt/caddy/blob/master/config/setup/tls_test.go

root.go is super-easy to test and only needs one or a few assertions I think.

**Comment by Makpoc** [comment] 2015-10-08 08:54
Hi,
As with everyone before me in this thread I would also like to help with some tests. I saw that the root.go is still without test so I'll take a look at it whenever I have time and try to write some. I'll need to get familiar with the functionallity first, but hopefully it won't take long..

**Comment by mholt** [comment] 2015-10-08 15:37
@Makpoc We'd totally welcome your help :) Feel free to join us in Slack if you have any questions!

**Comment by mholt** [comment] 2016-01-06 06:40
I'm closing this since we have tests in every package now and have vastly improved from having no tests at all. Thanks to all who have got us this far.

Tests will _always_ be changing and needing improvements and more thorough coverage, so if you see this issue later, please don't hesitate to jump in to help with tests. Even though the issue is closed, we are always working on improving tests and test coverage. Feel free to ask if you want to get some pointers to get started contributing!

**Closed by mholt** 2016-01-06 06:40 UTC
Labels: help wanted, in progress
