### ISSUE TITLE
Caddy rewrite not working correctly !!

### ISSUE THREAD

**Issue by Tester98** [mholt/caddy#1452] opened 2017-02-18 11:33 UTC
### 1. What version of Caddy are you running (`caddy -version`)?
Latest release

### 2. What are you trying to do?
Redirecting old url to new url

### 3. What is your entire Caddyfile?
The relevant part is here from here https://caddyserver.com/docs/rewrite
```
rewrite /app {
    r  (.*)
    to /index?path={1}
}
```

### 5. What did you expect to see?
All uris containing /app should internally redirect to new page. 

### 6. What did you see instead (give full error messages and/or log)?
Some random requests do NOT get redirected and the the old page is served. Still investigating but definitely caddy problem.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Still finding out, since my organization doesn't allow me post internal uris or anything else.

**Comment by mholt** [comment] 2017-02-18 13:22
Hey @Tester98  -- thanks for filing an issue. Are you sure it's not a browser cache problem? Have you tried with curl?

We're getting ready to announce a private support option for companies who can't post details publicly, like yours. Is this something you'd be interested in? We don't have the new site up yet but I could email you the pricing information and we could help your company better that way.

**Comment by Tester98** [comment] 2017-02-18 14:32
@mholt This is not a support request. I just happen to inherit caddy. All the bugs that i report are on my risk, if something gets leaked, i get fired and loose my job. I cannot comment on my company policies or anything.  As i am just an admin, any experience i get, i try to share so as caddy or anything else gets improved, hoping its easy for other admins or my future.

Now, on the bug.  I am sure this is not a browser cache problem. Did not try using curl. But, i have discovered something ugly. The problem is not in caddy. It looks like the problem lies in golang. The regexp package seems to behave odd. The problem must be affecting all software using regexp. The issue is when regexp sees a certain binary byte, it marks as regexp match failed.  I am putting the code below so you can test it and confirm it. Please ignore my mistakes,as i am new to go.
```
// regex issue showcase
package main

import (
	"fmt"
	"regexp"
)

func main() {
	test_data := []byte{0x03, 0x65, 0xd0}
	pattern1 := regexp.MustCompile(`\x03\x65`)
	pattern2 := regexp.MustCompile(`\x03\x65\xd0`)

	// both pattern can be compiled annd both should match
	if pattern1.Match(test_data) {
		fmt.Printf("Pattern1 matched\n")
	} else {
		fmt.Printf("Pattern1 failed\n")
	}

	if pattern2.Match(test_data) {
		fmt.Printf("Pattern2 matched\n")
	} else {
		fmt.Printf("Pattern2 failed\n")
	}
}
```

The code above should match both the patterns, you can see it visually. However, as soon as the regexp package see the \xd0, it marks the string as not matching. patterns compile without error.

**Comment by mholt** [comment] 2017-02-18 16:07
Wow, nice find -- I think your string contains an invalid UTF-8 sequence, but that definitely looks like an implementation quirk/bug in Go. In fact, here's what looks appears to be a relevant issue in the Go project: https://github.com/golang/go/issues/11185

Oh, and I put your snippet in the Go playground for testing: https://play.golang.org/p/5X4yiZrUza

I am not sure what to do about this. :confused: I will file a new issue with Go, since I think/wonder if MustCompile should panic if the regex is invalid UTF-8 like this. For now we just have to hope/ask for valid UTF-8 input.

... I hope you do not lose your job! You are obviously good at it.

I will close this issue now, since I don't think there's anything to do in Caddy for now.

**Closed by mholt** 2017-02-18 16:07 UTC

**Comment by mholt** [comment] 2017-02-18 17:13
@Tester98 By changing the backticks around the string in MustCompile to double quotes, you get the expected result (a panic): https://play.golang.org/p/qJMgs0xFxU - I missed this detail earlier.

Backticks mean raw string; no interpretation to convert `\x...` to a code point.

Anyway, we will be happy to help as soon as we can get enough information to reproduce the issue. As far as I can tell it is working properly...
