### ISSUE TITLE
Rewrite does not work after 0.10.3

### ISSUE THREAD

**Issue by drzero42** [mholt/caddy#1886] opened 2017-09-19 10:44 UTC
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.3
0.10.4
0.10.9

### 2. What are you trying to do?
I have a config which uses rewrite that works fine in 0.10.3, but not in 0.10.4 or any other version up to (and including) 0.10.9

### 3. What is your entire Caddyfile?
```
:80 {
    status 200 /healthz
    rewrite {
        if {path} not /healthz
        to {path} index.html
    }
    log / stdout "{remote} - [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\" {latency}"
    errors stdout
    root /app
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Using docker image abiosoft/caddy for all versions checked. Caddy is executed as "/usr/bin/caddy --conf /etc/Caddyfile --log stdout".

### 5. Please paste any relevant HTTP request(s) here.
With Caddy 0.10.3:
```
$ curl -v localhost:8080/foo
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /foo HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 4742
< Content-Type: text/html; charset=utf-8
< Etag: "owiryk3nq"
< Last-Modified: Tue, 19 Sep 2017 09:06:20 GMT
< Server: Caddy
< Date: Tue, 19 Sep 2017 10:38:02 GMT
< 
<!DOCTYPE html>
<html>
... Content excluded for this ticket.
```

With Caddy 0.10.9:
```
$ curl -v localhost:8080/foo
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /foo HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Caddy-Sponsors: This free web server is made possible by its sponsors: Minio, Uptime Robot, and Sourcegraph
< Location: .
< Server: Caddy
< Date: Tue, 19 Sep 2017 10:36:59 GMT
< Content-Length: 36
< Content-Type: text/html; charset=utf-8
< 
<a href=".">Moved Permanently</a>.

* Connection #0 to host localhost left intact
```

### 6. What did you expect to see?
I expected Caddy to serve the content of index.html when accessing /foo

### 7. What did you see instead (give full error messages and/or log)?
In 0.10.3 it works correctly. In 0.10.4-0.10.9 it gives 301 with a Location of "."

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Make a docker image with this Dockerfile:

FROM abiosoft/caddy:0.10.9
RUN mkdir /app
COPY Caddyfile /etc/Caddyfile
COPY index.html /app/index.html

Replace 0.10.9 with 0.10.3 to make it work.

**Comment by mholt** [comment] 2017-09-19 14:51
Thanks for filling out the whole issue template; this is a duplicate of several other issues: #1737 and #1732 for example; we fixed a bug; remove the index.html from your destination and use the canonical URL instead.

**Closed by mholt** 2017-09-19 14:51 UTC

**Comment by drzero42** [comment] 2017-09-20 08:13
Thank you. I searched the issues, but did not think to check already closed ones. It works with the suggested change.
