### ISSUE TITLE
QUIC Error with PUT Request (ARMv6)

### ISSUE THREAD

**Issue by ubergesundheit** [mholt/caddy#1413] opened 2017-02-08 10:39 UTC
### 1. What version of Caddy are you running (`caddy -version`)?
`Caddy 0.9.5` on Raspberry Pi v1 ARMv6 downloaded using `?os=linux&arch=arm&features=&arm=6` parameters.
Plugins are: filemanager and cors

### 2. What are you trying to do?
Build a webdav server for keeweb.info

### 3. What is your entire Caddyfile?
```text
<my-host-redacted>/pwdav {
  tls <my-address-redacted>
  root /srv/keepass

  #cors / { 
  #  origin https://app.keeweb.info
  #  allow_credentials true
  #  methods POST,GET,OPTIONS,PUT,DELETE,HEAD,OPTIONS,PROPFIND
  #}

  header / {
    Access-Control-Allow-Origin "https://app.keeweb.info"
    Access-Control-Allow-Methods "POST,GET,OPTIONS,PUT,DELETE,HEAD,OPTIONS,PROPFIND"
    Access-Control-Allow-Headers "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Authorization"
  }

  status 200 /ok

  rewrite / {
    if {method} is OPTIONS
    r \.kdbx
    to /ok
  }

  rewrite / {
    if {method} is PUT
    r \.kdbx
    to _fm/{uri}
  }


  basicauth /privat.kdbx <my-user-redacted> <my-pass-redacted>

  filemanager /_fm {
    show /srv/keepass
    webdav /srv/keepass
  }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Provided systemd unit file. I only added the `-quic` flag

### 5. What did you expect to see?
Just wanted to report this issue. I simply can deactivate quic and it works.

### 6. What did you see instead (give full error messages and/or log)?
From `journalctl -f -u caddy`
```
Feb 08 10:33:16 <my-host-redacted> caddy[14719]: panic: interface conversion: io.ReadCloser is struct { io.Reader; io.Closer }, not *h2quic.requestBody
Feb 08 10:33:16 <my-host-redacted> caddy[14719]: goroutine 43 [running]:
Feb 08 10:33:16 <my-host-redacted> caddy[14719]: panic(0x785ed0, 0x114e4e60)
Feb 08 10:33:16 <my-host-redacted> caddy[14719]: /usr/local/go/src/runtime/panic.go:500 +0x33c
Feb 08 10:33:16 <my-host-redacted> caddy[14719]: github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest.func1(0x111654c0, 0x114b1530, 0x114de280, 0x114e4a00, 0xaaf978, 0x11047960)
Feb 08 10:33:16 <my-host-redacted> caddy[14719]: /home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:193 +0x1a0
Feb 08 10:33:16 <my-host-redacted> caddy[14719]: created by github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest
Feb 08 10:33:16 <my-host-redacted> caddy[14719]: /home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:202 +0x83c
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Download caddy on a raspberry pi v1, use my caddyfile and put a kdbx file in /srv/keepass and try to save in https://app.keeweb.info

**Comment by Henrocker** [comment] 2017-02-08 11:49
You can simply recompile caddy from here by:

`go get -u github.com/mholt/caddy/caddy`

`cd $GOPATH/src/github.com/mholt/caddy/caddy`

`./build.bash {newBinaryName}`

Now copy the binary from `cd $GOPATH/bin/{newBinaryName}`
to your running directory and start caddy again with the usual service file and the quic flag.

**Comment by mholt** [comment] 2017-02-08 14:09
I think this is a duplicate of #1393 and #1406. The build server needs to be updated but I need to do it manually which takes some time, so... I'll get around to it eventually. For now you can build from source and make sure your dependencies are up to date and it will work!

**Closed by mholt** 2017-02-08 14:09 UTC
