### ISSUE TITLE
Error when proxying to `oauth2_proxy` using Github

### ISSUE THREAD

**Issue by fern4lvarez** [mholt/caddy#596] opened 2016-02-11 13:09 UTC
I want to deploy this architecture:

### The setup

This is my Caddyfile:

```
my.domain.net
log caddy.log
proxy / 0.0.0.0:4180
```

Then, I created a OAuth2 Github application on https://github.com/settings/developers, with _Authorization callback URL_ as `https://my.domain.net/oauth2/callback`, as specified in the `oauth2_proxy` documentation: https://github.com/bitly/oauth2_proxy#github-auth-provider

Last, but not least, I executed my `oauth2_proxy` server, which will run between Caddy and Kibana[5601], providing Github authentication:

`oauth2_proxy --provider="github" --email-domain=* --client-id="..." --client-secret="..." --upstream=http://127.0.0.1:5601 --cookie-secret="..."`

### The execution

When I try to request https://my.domain.net, I see that Caddy proxies successfully to `oauth2_proxy`, this one asks me for my Github credentials, but then gives me a `403 Permission Denied redirect_uri_mismatch`. As explained [here](https://developer.github.com/v3/oauth/#redirect-uri-mismatch), the URL I created the application with, and the one provided by `oauth2_proxy` don't match (https://my.domain.net/oauth2/callback). But they really do, so I have the feeling that Caddy is somehow changing the host or the incoming address so it doesn't match.

These are the logs:

```
x - [11/Feb/2016:12:51:02 +0000] "GET / HTTP/2.0" 403 2244
x - [11/Feb/2016:12:51:03 +0000] "GET /oauth2/start?rd=%2F HTTP/2.0" 302 246
x - [11/Feb/2016:12:51:04 +0000] "GET /oauth2/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=%2F HTTP/2.0" 403 296
```

For the record, this is the nginx configuration that `oauth2_auth` recommends to use for the same architecture, switching caddy by nginx:

```
server {
    listen 443 default ssl;
    server_name internal.yourcompany.com;
    ssl_certificate /path/to/cert.pem;
    ssl_certificate_key /path/to/cert.key;
    add_header Strict-Transport-Security max-age=2592000;

    location / {
        proxy_pass http://127.0.0.1:4180;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_connect_timeout 1;
        proxy_send_timeout 30;
        proxy_read_timeout 30;
    }
}
```

### Why I think this is a problem in caddy, not in `oauth2_proxy`

`oauth2_proxy` can be used in two different architectures: the one I proposed, or using it as first line proxy, providing the SSL certificates directly on execution. I did the latter with:

`oauth2_proxy --provider="github" --email-domain=* --client-id="..." --client-secret="..." --upstream=http://127.0.0.1:5601 --cookie-secret="test" --tls-cert=/root/.caddy/letsencrypt/sites/my.domain.net/my.domain.net.crt --tls-key=/root/.caddy/letsencrypt/sites/my.domain.net/my.domain.net.key`

And everything worked as expected, my request to https://my.domain.net was proxied to the Github authentication and then to Kibana.

###

Apparently caddy fails on this architecture with this configuration to proxy requests to `oauth2_proxy` server without breaking the process. I might be missing setting some headers as in the nginx example. Or maybe caddy does something in the background that I'm missing. Any idea?

**Comment by raphink** [comment] 2016-02-22 14:52
I have the same issue with haproxy. It seems to me that it's a problem with https/http in oauth2_proxy.

In the provided example, Nginx is setup with `proxy_set_header X-Scheme $scheme;` to let oauth2_proxy know that the scheme is https. In haproxy however, another header is passed instead with `http-request add-header X-Forwarded-Proto https if { ssl_fc }`. I'm guessing oauth2_proxy doesn't understand that header.

**Comment by raphink** [comment] 2016-02-22 15:11
I just confirmed the hypothesis this way:

* Clean existing oauth2_proxy cookies
* Setup the LB to accept both 80 and 443
* Setup github application for http://<service> with http:// callback URL
* Access page at https://<service>
* Get a login page => redirected to http://<service> (no HTTPS)
* Access page at https://<service> again => no redirection

This shows that oauth2_proxy does not know about the HTTPS scheme used on the service page, and thus requests an HTTP callback.

**Comment by raphink** [comment] 2016-02-22 15:32
An option that worked for me is to pass the `-redirect-url` parameter to oauth2_proxy, forcing it to use https://.

**Comment by mholt** [comment] 2016-02-25 07:23
@fern4lvarez Does that workaround do the trick for you?

Closing, since this doesn't seem to be an issue with Caddy. Although, I appreciate the details :wink:

**Closed by mholt** 2016-02-25 07:23 UTC
