### ISSUE TITLE
Allow revocation list for client cert auth

### ISSUE THREAD

**Issue by Alex131089** [mholt/caddy#1904] opened 2017-10-04 00:33 UTC
While Caddy allow to use client cert auth (https://caddyserver.com/docs/tls), it doesn't seems to allow to refuse a revoked client certificate (https://golang.org/pkg/crypto/tls/#Config, https://stackoverflow.com/questions/37058322/how-can-i-verify-client-certificates-against-a-crl-in-golang)

This may problematic, because if you deploy client certificates on multiple devices, if one of the devices is compromised, you cannot simply revoke this certificate, you would have to change the CA and all other emitted client certificates.

Could Caddy include revocation list verification ?

Btw, is the `Note that this setting applies to the entire listener, not just a single site.` statement in the documentation still correct ? Is a listener a definition block / what is a "listener" ?

**Comment by mholt** [comment] 2017-10-04 02:43
Ah, thanks for the suggestion. This isn't obvious, but this I think is kind of a duplicate of #1375 -- the last unchecked item is to take full advantage of Go 1.8's improved client certificate verification functionality. Which could possibly include not accepting revoked certificates.

This issue is now linked to that one, so I'll funnel the discussion to that one, which is also a #Hacktoberfest issue.

**Closed by mholt** 2017-10-04 02:43 UTC
