### ISSUE TITLE
Hiding HTTP error messages

### ISSUE THREAD

**Issue by OskarPersson** [mholt/caddy#567] opened 2016-02-02 14:16 UTC
How do I stop Caddy from printing anything when I get a HTTP error (404, 500, etc.)?

**Comment by abiosoft** [comment] 2016-02-02 14:29
You can use a custom error page. 
```
errors {
	404 404.html # Not Found
	500 500.html # Internal Server Error
}
```

**Comment by OskarPersson** [comment] 2016-02-02 14:32
Is that the best solution for when I want a blank page? The problem is that I'm using Caddy together with Laravel, and I make my error pages using Laravel. Using the default settings I then get both the custom page created in Laravel with the default message from Caddy below.

**Comment by abiosoft** [comment] 2016-02-02 14:55
You can not do that. I'd like to know if other webservers allow that and if this is a common or edge case.

As a workaround, set a blank page as the error page.

**Comment by OskarPersson** [comment] 2016-02-02 14:59
It is probably an edge case. With Apache, Laravel has its own .htaccess file that fixes that problem.

**Comment by abiosoft** [comment] 2016-02-02 15:07
Okay. Maybe we add a `hide` config to hide certain errors.
```
errors {
    ...
    hide 400 404 500
}
```
@mholt what's your opinion.

**Comment by mholt** [comment] 2016-02-02 16:29
Not a high priority right now, not sure I understand yet why this is a necessity.

**Comment by mholt** [comment] 2016-02-03 06:54
I suppose just use the error pages that were suggested earlier, and make them blank files. That should do the trick. :)

**Comment by stevepacker** [comment] 2016-02-12 06:26
I think I'm experiencing the same issue.  I don't think it's an edge case.

I'm building an API where the output is either JSON or XML.  In either case, PHP is properly returning an HTTP error code (for example 401 Unauthorized when login fails) in addition to additional information in JSON or XML format.  However, Caddy is additionally appending the string "401 Unauthorized" to the end of the response body, thereby breaking the serialized output.

For now the workaround prescribed here works (making a blank file, and pointing every 4xx and 5xx error code I expect to send back to the blank file), but it's ugly and seems contrary to simplicity and brevity that the Caddyfile seems to prescribe to.
```
errors  {
        400 /dev/null
        401 /dev/null
        402 /dev/null
        403 /dev/null
        404 /dev/null
        405 /dev/null
        406 /dev/null
        410 /dev/null
        500 /dev/null
    }
```
(and as a side-note; it's sad the paths MUST be relative and /dev/null can't be the server's actual /dev/null)

What I would expect is that if there is an HTTP error and there is a response body set, Caddy should not append its own content too.

**Comment by mholt** [comment] 2016-02-12 07:44
Now I understand the problem a little better.

> What I would expect is that if there is an HTTP error and there is a response body set, Caddy should not append its own content too.

I think I agree, `if len(resp.Body) > 0` then we do not write any more bytes to the body in handling the error. That would probably be the easiest way to fix this, although it involves buffering the response in a ResponseRecorder, and then copying the buffer down the pipe to the client after we check the length.

**Comment by alexandreteles** [comment] 2016-02-15 15:17
While we don't have a default solution for Caddy, maybe you can make a temporary workaround using a PHP script to write the headers for you. I don't know if it will work or if Caddy will just print the code on the screen. If it don't work I can actually try to write this patch.

```
...

internal /error/processError.php
errors {
  log ../error.log
  404 /error/processError.php?error=404
  403 /error/processError.php?error=403
  404 /error/processError.php?error=404
  500 /error/processError.php?error=500
  501 /error/processError.php?error=501
}
```

And the PHP code can be something on these lines:

```php
<?php
  $errorCode = filter_input(INPUT_GET, 'error', FILTER_SANITIZE_URL);
  if($errorCode >= 400 || $errorCode <= 415) {
    http_response_code($errorCode);
    fastcgi_finish_request();
    exit();
  } elseif($errorCode >= 500 || $errorCode <= 505) {
      http_response_code($errorCode);
      fastcgi_finish_request();
      exit();
  } else {
    exit('Unknown http status code "' . htmlentities($errorCode) . '"');
    fastcgi_finish_request();
  }
```

It should return the http header that you need with a empty body.

**Comment by mholt** [comment] 2016-02-17 17:23
Anybody is welcome to try to fix this. The log middleware uses a Recorder which you can use as a model; the idea is you want to record the response body, and if it's length is greater than zero, we don't write an error message. Otherwise we do. This change would occur in the `errors` middleware.

**Comment by humboldtux** [comment] 2016-02-17 17:37
Anyone working of this, i would like to?

**Comment by mholt** [comment] 2016-02-17 17:41
@humboldtux AFAIK it's all you :smile:

**Comment by joerx** [comment] 2016-02-18 07:09
+1

**Comment by joanhey** [comment] 2016-02-20 18:56
How make it nginx:
fastcgi_intercept_errors off;

**Comment by mholt** [comment] 2016-02-20 19:01
PR #614 takes care of this. Just waiting on the author for a couple changes before I merge it in.

**Comment by mholt** [comment] 2016-02-25 02:51
This turned out harder than I thought. :smile: Thanks to @humboldtux's help, I think we got this fixed on master. Will go out in the next release!

**Closed** 2016-02-25 02:50 UTC
Labels: bug, good-for-newbies

**Comment by slightfoot** [comment] 2016-08-07 17:35
This has regressed. Issue still exists since moving from older middleware system.
https://github.com/mholt/caddy/blob/master/caddyhttp/errors/errors.go#L53

Previous mholt patch:
https://github.com/mholt/caddy/commit/c37ad7f677b9122544ab2d2384ef8ef2b76bd970

Previous PR patch:
https://github.com/mholt/caddy/pull/614/files#diff-2133a138b5410dfb36af9638df4e783fL45

I noticed this when creating my own middleware sending back JSON body and having the default error handler injecting its error text. I'd also like to go on to say in simple error reporting from middleware you might not want to set a Content-Length header. So recording the number of bytes written to the http response would probably be better.

**Comment by mholt** [comment] 2016-08-08 17:37
Hmm, there's not enough information here to be sure, but I don't think this is a regression; if you write a response body, you have to write a status code also, so return 0.
