### ISSUE TITLE
Race condition when quitting caddy

### ISSUE THREAD

**Issue by SchumacherFM** [mholt/caddy#1371] opened 2017-01-24 20:26 UTC
### 1. What version of Caddy are you running (`caddy -version`)?

Checked out commit: ecf852ea43db136da5513da76f5f95bddd6aab04

### 2. What are you trying to do?

```
$ go run -race $GOPATH/src/github.com/mholt/caddy/caddy/main.go -conf ./Caddyfile
Activating privacy features... done.
http://127.0.0.1:2017
http://127.0.0.1:3017
WARNING: File descriptor limit 4864 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
```
And in another terminal window:
```
$ curl -i http://127.0.0.1:2017/page_1.html
$ curl -i http://127.0.0.1:2017/page_2.html
$ curl -i http://127.0.0.1:2017/page_N.html
$ echo "Just run a couple for normal GET requests"
```

### 3. What is your entire Caddyfile?
```text
# front facing webserver
http://127.0.0.1:2017 {
    tls off
    root ./www_root/
    # gzip
    browse
    ext    .html
    log    ./cdy_test_2017_access.log
    errors ./cdy_test_2017_errors.log
    #errors visible
}

# micro service (ms) end point
http://127.0.0.1:3017 {
    tls off
    root ./www_root/
    log    ./cdy_test_3017_access.log
    errors ./cdy_test_3017_errors.log
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Go 1.8 RC2

```
$ go version
go version devel +4cce27a3fa Sat Jan 21 03:20:55 2017 +0000 darwin/amd64
$ go run -race $GOPATH/src/github.com/mholt/caddy/caddy/main.go -conf ./Caddyfile

and press later CTRL+C then Caddy is shutting down and baaaaam:
```

### 5. What did you expect to see?

No Race Condition

### 6. What did you see instead (give full error messages and/or log)?

```
^C==================
WARNING: DATA RACE
Write at 0x00c4201dc440 by goroutine 10:
  os.(*file).close()
      /usr/local/opt/go/libexec/src/os/file_unix.go:143 +0x10a
  os.(*File).Close()
      /usr/local/opt/go/libexec/src/os/file_unix.go:132 +0x55
  github.com/mholt/caddy/caddyhttp/log.setup.func2()
      /Users/gopher/go/src/github.com/mholt/caddy/caddyhttp/log/setup.go:68 +0x185
  github.com/mholt/caddy.(*Instance).ShutdownCallbacks()
      /Users/gopher/go/src/github.com/mholt/caddy/caddy.go:124 +0xc0
  github.com/mholt/caddy.allShutdownCallbacks()
      /Users/gopher/go/src/github.com/mholt/caddy/sigtrap.go:75 +0xc4
  github.com/mholt/caddy.executeShutdownCallbacks.func1()
      /Users/gopher/go/src/github.com/mholt/caddy/sigtrap.go:55 +0x69
  sync.(*Once).Do()
      /usr/local/opt/go/libexec/src/sync/once.go:44 +0xe1
  github.com/mholt/caddy.executeShutdownCallbacks()
      /Users/gopher/go/src/github.com/mholt/caddy/sigtrap.go:62 +0xc9
  github.com/mholt/caddy.trapSignalsCrossPlatform.func1()
      /Users/gopher/go/src/github.com/mholt/caddy/sigtrap.go:45 +0x1ed

Previous read at 0x00c4201dc440 by goroutine 31:
  os.(*File).Write()
      /usr/local/opt/go/libexec/src/os/file.go:139 +0x70
  log.(*Logger).Output()
      /usr/local/opt/go/libexec/src/log/log.go:168 +0x39d
  log.(*Logger).Println()
      /usr/local/opt/go/libexec/src/log/log.go:184 +0x77
  github.com/mholt/caddy/caddyhttp/log.Logger.ServeHTTP()
      /Users/gopher/go/src/github.com/mholt/caddy/caddyhttp/log/log.go:57 +0x675
  github.com/mholt/caddy/caddyhttp/log.(*Logger).ServeHTTP()
      <autogenerated>:1 +0xbc
  github.com/mholt/caddy/caddyhttp/httpserver.(*Server).serveHTTP()
      /Users/gopher/go/src/github.com/mholt/caddy/caddyhttp/httpserver/server.go:281 +0x3cc
  github.com/mholt/caddy/caddyhttp/httpserver.(*Server).ServeHTTP()
      /Users/gopher/go/src/github.com/mholt/caddy/caddyhttp/httpserver/server.go:215 +0xf2
  net/http.serverHandler.ServeHTTP()
      /usr/local/opt/go/libexec/src/net/http/server.go:2568 +0xbc
  net/http.(*conn).serve()
      /usr/local/opt/go/libexec/src/net/http/server.go:1825 +0x71a

Goroutine 10 (running) created at:
  github.com/mholt/caddy.trapSignalsCrossPlatform()
      /Users/gopher/go/src/github.com/mholt/caddy/sigtrap.go:47 +0x42
  github.com/mholt/caddy.TrapSignals()
      /Users/gopher/go/src/github.com/mholt/caddy/sigtrap.go:16 +0x2f
  github.com/mholt/caddy/caddy/caddymain.init.1()
      /Users/gopher/go/src/github.com/mholt/caddy/caddy/caddymain/run.go:27 +0x33
  github.com/mholt/caddy/caddy/caddymain.init()
      /Users/gopher/go/src/github.com/mholt/caddy/caddy/caddymain/run.go:261 +0xe0
  main.init()
      /Users/gopher/go/src/github.com/mholt/caddy/caddy/main.go:15 +0x9f

Goroutine 31 (finished) created at:
  net/http.(*Server).Serve()
      /usr/local/opt/go/libexec/src/net/http/server.go:2668 +0x35f
  github.com/mholt/caddy/caddyhttp/httpserver.(*Server).Serve()
      /Users/gopher/go/src/github.com/mholt/caddy/caddyhttp/httpserver/server.go:190 +0x1c4
  github.com/mholt/caddy.startServers.func1.1()
      /Users/gopher/go/src/github.com/mholt/caddy/caddy.go:662 +0x56
==================
Found 1 data race(s)
exit status 66
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Reproducing possible but fixing impossible ....

**Comment by mholt** [comment] 2017-01-24 20:28
I just discovered this independently this morning. I had to go to class so I'm not sure what the issue is yet, need to play with it some more. Anyone want to tackle this?

**Comment by SchumacherFM** [comment] 2017-01-24 20:29
I can investigate but I think I'm not able to fix it ...

**Comment by mholt** [comment] 2017-01-25 00:20
I bet you could do it! ;) Last resort, we just stick a lock on it.

I feel like I would have encountered this before, if it was this unsafe to open a file in one goroutine and close it in another...

**Comment by mholt** [comment] 2017-01-25 01:44
Whatever -- I just stuck a lock on it. Fix inbound in a sec.

**Closed** 2017-01-25 01:48 UTC
Labels: bug

**Comment by SchumacherFM** [comment] 2017-01-25 04:41
Good morning! thanks for fixing!
