### ISSUE TITLE
Can't use let's encrypt staging environment with last version.

### ISSUE THREAD

**Issue by zaibon** [mholt/caddy#921] opened 2016-07-06 12:10 UTC
#### 1. What version of Caddy are you running (`caddy -version`)?
built from source

#### 2. What are you trying to do?
start caddy using the staging environment of let's encrypt

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
`./caddy  -ca https://acme-staging.api.letsencrypt.org/directory -conf Caddyfile`

#### 5. What did you expect to see?
caddy running properly

#### 6. What did you see instead (give full error messages and/or log)?
```
2016/07/06 14:11:03 error creating client: registration error: acme: Error 400 - urn:acme:error:malformed - ECDSA curve P-384 not allowed
```

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
```
go get github.com/mholt/caddy
$GOPATH/bin/caddy -ca -ca https://acme-staging.api.letsencrypt.org/directory
```

**Comment by mholt** [comment] 2016-07-11 13:58
That's strange. I noticed you omitted your Caddyfile; can you share at least your `tls` directives?

**Comment by mholt** [comment] 2016-07-13 12:11
Well, I'm unable to reproduce the problem without more information, so I'll close this for now.

**Closed by mholt** 2016-07-13 12:11 UTC
