### ISSUE TITLE
rotate_compress documentation needs updating

### ISSUE THREAD

**Issue by watermelonjuice** [mholt/caddy#1771] opened 2017-07-18 17:00 UTC
I have followed the log documentation here: https://caddyserver.com/docs/log and added the following to my Caddyfile: 

> 	log /var/log/caddy/access.log {
> 		rotate_size 50
> 		rotate_age  90
> 		rotate_keep 20
> 		rotate_compress
> 	}

caddy is throwing the following error:

> caddy[875]: 2017/07/18 16:50:28 /etc/caddy/Caddyfile:15 - Parse error: Wrong argument count or unexpected line ending after 'rotate_compress'

**Comment by mholt** [comment] 2017-07-18 17:16
Thanks for reporting, but I think this is a duplicate of #1761.

**Closed by mholt** 2017-07-18 17:16 UTC
