### ISSUE TITLE
really unstable php, simply crashes

### ISSUE THREAD

**Issue by nwgat** [mholt/caddy#930] opened 2016-07-13 19:06 UTC
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.8.2 x64
Ubuntu 16.04 x64

#### 2. What are you trying to do?
have a stable php working

#### 3. What is your entire Caddyfile?

```
nwgat.ninja {
	errors {
	404 /home/node/errors/error.html
	500 /home/node/errors/error.html
	502 /home/node/errors/error.html
}
    proxy / localhost:2368 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
	tls  
}

dev.nwgat.ninja {
	errors {
        404 /home/node/errors/error.html
        500 /home/node/errors/error.html
        502 /home/node/errors/error.html
}
    proxy / localhost:2366 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
	tls  
}

forum.nwgat.ninja nwgat.club {
    proxy / localhost:4567 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
        tls  
}

lounge.nwgat.ninja {
    proxy / localhost:9000 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-forwarded-Proto {scheme}
    }
        tls  
}

lftp.nwgat.ninja {
	root /var/www/lftp.nwgat.ninja
	browse
	gzip
	tls  
}

awesome.nwgat.ninja {
	root /var/www/awesome.nwgat.ninja
	gzip
	tls  
	fastcgi / /var/run/php5-fpm.sock php

        rewrite {
		if {path} ends_with /
		to {dir}/index.html {dir}/index.php /_h5ai/server/php/index.php
	}
}

status.nwgat.ninja {
	root /home/wiak/ServerStatus/status/
	gzip
	tls  
}

#nwgat.net www.nwgat.net www.nwgat.ninja nwgat.party www.nwgat.party nwgat.xyz {
#	redir {scheme}://nwgat.ninja{uri}
#}

```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -conf "Caddyfile"

#### 5. What did you expect to see?
a stable php?

#### 6. What did you see instead (give full error messages and/or log)?
unstable php that crashes

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
setup h5ai with caddy/php5 like in the  config and see for you self

**Comment by tboerger** [comment] 2016-07-13 20:29
And what do you mean with unstable PHP? It's not the fault of caddy if PHP-FPM is not configured stable/correctly. I don't have any issues with PHP through Caddy.

**Comment by mholt** [comment] 2016-07-13 22:47
Hi @nwgat,

> 6. What did you see instead (give full error messages and/or log)?
> unstable php that crashes

Can you please give the full error message and log and what generated it (Caddy or some other process)?

> setup h5ai with caddy/php5 like in the config and see for you self

We'll need more details than that, unfortunately; this isn't much to go on.

Also, as a bonus tip, you can remove the `tls` lines from your config. :) They're not necessary.

And I recommend upgrading to Caddy 0.8.3! :)

**Comment by MSF-Jarvis** [comment] 2016-07-14 02:38
@mholt, @nwgat has provided help with setting up h5ai on caddy at #819 earlier, please refer to that to understand his configuration

**Comment by abiosoft** [comment] 2016-07-14 06:51
@nwgat The title of this issue is misleading and too abstract. It would be better if it is more specific to the issue you are experiencing. 

Looks like you are a bit frustrated with what you are trying to set up, but consider those that have gone through probably more frustration in getting Caddy to support PHP. 

Do you have an equivalent nginx/apache config, we can compare it with your Caddyfile and see what possibly went wrong.

@MSF-Jarvis Are you experiencing anything similar with your h5ai and Caddy setup ?

**Comment by MSF-Jarvis** [comment] 2016-07-14 08:31
I have long since given in to the awesomeness that is `browse` but I'll set
it up again and see if I can reproduce it

**Comment by mholt** [comment] 2016-07-18 19:06
Closing until we have more information from @nwgat

**Closed by mholt** 2016-07-18 19:06 UTC

**Comment by ITSecMedia** [comment] 2016-11-07 18:55
I also experience some weird behaviour with PHP in Caddy.
sometimes, things just stop, no error message in the windows cmd but I have to kill caddy and restart it,
so that the PHP website works again...
