### ISSUE TITLE
Redirect with query string

### ISSUE THREAD

**Issue by dhannyz** [mholt/caddy#2336] opened 2018-11-09 12:50 UTC
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0

### 2. What are you trying to do?
redirect with a query string

### 3. Caddyfile example to reproduce?
```
first.site.com {
}

second.site.com {
  redir {scheme}://first.site.com/?query=string
}

```

Going to `second.site.com` fails to add the static query string defined in the redir
`second.site.com` becomes `first.site.com`
Add a single `?` and the static query is succesfully added
`second.site.com/?` becomes `first.site.com/?query=string`

**Comment by tobya** [comment] 2018-11-11 10:05
Thanks for the issue.

I am unable to reproduce this.  I have tried with latest code and compiled binary both on windows.  In both instances any call to 

    http://second.site.com 

redirects to

    http://first.site.com?query=string

I will close this issue, but if you can provide further information to allow it to be reproduced, we can reopen.

**Closed by tobya** 2018-11-11 10:05 UTC
