### ISSUE TITLE
Reloading via SIGUSR1 not working when started with exec

### ISSUE THREAD

**Issue by ionphractal** [mholt/caddy#1471] opened 2017-02-23 15:58 UTC
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.5 (+ccdc286 Thu Feb 23 15:09:08 UTC 2017)

### 2. What are you trying to do?
I'm using supervisord to start Caddy inside a container.
Because I have to set some command line parameter dynamically, I'm executing caddy binary inside a bash script.
Caddy needs to be executed with exec for supervisord to be able to control it.
I'm also using consul-template that should reload  Caddy when configuration changes and therefore sends a SIGUSR1 to the process.

### 3. What is your entire Caddyfile?
```text
:80 { 
        log stdout
        errors stderr
        redir https://{host}{uri}
}

:443 {
        log stdout
        errors stderr
        gzip

        tls {
                load /caddy/ssl
        }

        root /caddy/sites.d/0-default
        markdown /
}
{$BACKEND_DOMAIN} {     
        expvar /stats   
        log stdout
        errors stderr   
        gzip

        tls {$DEFAULT_EMAIL}

        basicauth / {$BACKEND_USER} {$BACKEND_PASSWORD}

        proxy / {$BACKEND_URL} {
                policy least_conn
                transparent
                insecure_skip_verify
                fail_timeout 10s
                max_fails 1
                try_duration 1s
        }
}

http://dev.local {
        log stdout
        errors stderr
        gzip 

        proxy / dockerhost.local:32793 {
                policy least_conn
                transparent
                insecure_skip_verify
                fail_timeout 10s
                max_fails 1
                try_duration 1s
        }
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
/go/bin/caddy -conf /caddy/Caddyfile -log stdout

### 5. What did you expect to see?
I would expect Caddy to be reloaded with messages like:
```text
2017/02/23 15:52:13 [INFO] SIGUSR1: Reloading
2017/02/23 15:52:13 [INFO] Reloading
2017/02/23 15:52:13 [INFO] Reloading complete
```

### 6. What did you see instead (give full error messages and/or log)?
Reloading does not complete and new configuration is not loaded. Even though Caddy got the event:
```text
2017/02/23 15:52:13 [INFO] SIGUSR1: Reloading
2017/02/23 15:52:13 [INFO] Reloading
```
It'll never report "Reloading complete".
Another SIGUSR1 sent to the process is completely ignored.
This only happens when I use "-conf" parameter.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
1. Build, e.g. like the following Docker image: ```docker build -t "caddy/minimal"``` .
Dockerfile
```text
FROM golang:1.8-alpine

ENV CADDY_VERSION="0.9.5-x" \
  CADDY_SRC_URL="https://github.com/mholt/caddy.git" \
  CADDY_COMMIT_SHA="ccdc28631aa6f398a24ab70cd6404a84ac1ae0c5" \
  CADDY_BINARY="caddy" \
  CA="https://acme-staging.api.letsencrypt.org/directory" \
  HOME="/caddy"
# Commit #1749 22.02.2017

RUN apk update && apk upgrade \
 && apk add libcap bash supervisor git unzip

RUN cd / \
 && git clone ${CADDY_SRC_URL} /tmp/build \
 && cd /tmp/build/ \
 && git checkout ${CADDY_COMMIT_SHA} \
 && cd ${CADDY_BINARY} \
 && go get -d \
 && bash build.bash \
 && mv ${CADDY_BINARY} ${GOPATH}/bin \
 && setcap cap_net_bind_service=+ep ${GOPATH}/bin/${CADDY_BINARY} \
 && mkdir -p "${HOME}" \
 && chown nobody:nogroup "${HOME}" \
 && rm -rf /var/cache/apk/* \
 && rm -Rf /tmp/build \
 && mkdir -p /caddy/sites.d/0-default /caddy/ssl

```
2. Start a container:
```
docker run -it caddy/minimal bash
```

3. Add above Caddyfile to /caddy
Create the following script
start.sh:
```bash
#!/bin/bash
exec /go/bin/caddy -conf /caddy/Caddyfile -log stdout
```
4. Start with:
```
bash start.sh &
```
5. Try to reload with:
```
pkill -SIGUSR1 /go/bin/caddy
```

**Comment by mholt** [comment] 2017-04-18 05:46
Any container gurus want to look into this?

**Comment by francislavoie** [comment] 2017-04-18 06:16
So, I think the solution is to use `trap` in the shell script to capture signals and pass them on. Funny, I was working on this exact issue (but not for Caddy) today!

Quick example:

```sh
# forward SIGUSR1 to the process
trap 'kill -USR1 $PID; echo "SIGUSR1"' USR1 INT

# change process state, specifies user
exec /go/bin/caddy -conf /caddy/Caddyfile -log stdout &

# get the PID and wait, see trap above and link below
# http://veithen.github.io/2014/11/16/sigterm-propagation.html
PID=$!
wait $PID
trap - USR1 INT
wait $PID
STATUS=$?
```

You might need to adapt this, I haven't tested it so no guarantees, but it'd be something to try.

**Comment by AndreKR** [comment] 2017-04-18 20:15
How sure are you about this?
> and new configuration is not loaded

The reason why you don't see `2017/02/23 15:52:13 [INFO] Reloading complete` has nothing to do with containers, bash or exec.

It is simply because during the reload the `onShutdown` function of the instance [is called](https://github.com/mholt/caddy/blob/master/caddy.go#L194) and that [closes](https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/logger.go#L142) the logger. When logging to stdout, that effectively [means](https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/logger.go#L96) `os.Stdout.Close()` which makes further log output to the console impossible.

This is reproducible with a minimal Caddyfile
```
:80 {
        log stdout
        errors stderr
        redir https://{host}{uri}
}
```
by starting caddy with `./caddy -conf Caddyfile -log stdout` and sending SIGUSR1 to the process from another shell.

**Comment by mholt** [comment] 2017-04-18 20:18
Ohh, I didn't even see that! Great point, @AndreKR. If there's no response from the OP after a while I'll close this.

**Comment by AndreKR** [comment] 2017-04-18 21:41
Closing `os.Stdout` does seem like a bug to me. :)

**Comment by ionphractal** [comment] 2017-04-18 21:45
> How sure are you about this?
I'm sure about this because I can observe 502 Bad Gateway after an app container is restarted.
The container gets assigned another port triggering Registrator to update Consul, generating a new config template (using consul-template) and finally reloading Caddy using SIGUSR1.
If I forcefully restart Caddy in that situation, the 502 resolves and everything works again.

@AndreKR Thanks for the explanation though. It explains the log behaviour of "reloading complete". Yet, stdout should be opened again when loading a new configuration? But I don't remember if this was the case for other log messages. I'll double check that (not today though).

I'll try @francislavoie 's suggestion first and if that doesn't work, maybe it would be possible to keep stdout / the logger open? I'd probably need help with that because I don't know Go. Open for any advice.

**Comment by mholt** [comment] 2017-04-18 21:57
Okay, looking into this (not closing the streams).

**Comment by mholt** [comment] 2017-04-18 22:02
@ionphractal Are you able to build from source and try again? Can you try https://github.com/mholt/caddy/pull/1596 (the `closinglogs` branch)?

**Closed** 2017-04-20 11:39 UTC
Labels: bug, help wanted

**Comment by ionphractal** [comment] 2017-04-21 12:58
@mholt I was just able to test the new commit, works like a charm! Great work, thank you!
