### ISSUE TITLE
Option to save self_signed certs

### ISSUE THREAD

**Issue by OmgImAlexis** [mholt/caddy#1509] opened 2017-03-11 04:41 UTC
Currently when you run caddy using the `tls self_signed` directive caddy regens the certs on restart meaning I then have to open each domain one by one in my browser and accept the warning. It'd be nice if Caddy had an option to just dump the certs into the path provided.

Maybe something like so? This way it can just reuse the certs the next time it starts.
```
tls self_signed /Users/xo/certs
```

**Comment by mholt** [comment] 2017-03-11 06:30
Is this for a localhost domain? In Chrome, you can set this flag: #allow_insecure_localhost

<img width="556" alt="screen shot 2017-03-10 at 11 29 34 pm" src="https://cloud.githubusercontent.com/assets/1128849/23821238/7b801a30-05e9-11e7-9b29-48593bd8fb54.png">

**Comment by OmgImAlexis** [comment] 2017-03-11 06:58
I'm using example.com as well as a load of subdomains of it as localhost isn't an actual domain so it doesn't allow subdomains.

**Comment by mhoIt** [comment] 2017-04-26 20:39
Feature requests are stupid just like caddyserver

**Comment by mholt** [comment] 2017-04-26 23:58
(Disregard any comment notifications you may have gotten from a user account that _looked like mine_ earlier today.)

**Comment by aaronellington** [comment] 2017-05-01 17:47
Would generating your own certs (and then point to those with the `tls` directive) work for you as a short term solution?

**Comment by OmgImAlexis** [comment] 2017-05-02 05:21
For the short term sure, that's what I ended up doing for now. In the long run this would fix the issue of needing to generate new certs myself every time I need to do testing across multiple subdomains.

**Comment by princemaple** [comment] 2017-08-11 07:06
Could this be implemented, please? This will save a lot of hassle for Firefox users.

**Comment by tobya** [comment] 2017-08-11 09:04
We are happy to accept a PR implementing this if someone wants to give it a try.  It should be quite straightforward.

Is it possible to explain why LetEncrypt certs are not a possibility here?  If you have a simple public domain you can create any number of subdomains on it internally.  Is there a specific reason why self_signed certs are required?

**Comment by princemaple** [comment] 2017-08-11 09:08
It's for dev only. Firefox only allows you to add exception for certs, no way like in chrome to allow insecure certs on all local connections. And the exception becomes stale as soon as you generate a different cert, which happens every time you restart caddy.

**Comment by OmgImAlexis** [comment] 2017-08-11 09:19
@tobya at the time I had hit the rate limit for let's encrypt on all my domains so I had to use self signed ones while testing.

**Comment by tobya** [comment] 2017-08-11 09:32
@princemaple you can still use letsencrypt for dev sites.  I still don't understand the issue that requires you to use self_signed certs.  I'm just trying to understand the real issue here.  Perhaps it is ratelimits, firewalls, company policy, but I would like to get to the real issue to see if this is the only way of solving it.

@OmgImAlexis if you use the staging environment for lets encrypt by starting caddy like this

    caddy -ca https://acme-staging.api.letsencrypt.org/directory

you essentially end up with the same as self_signed certs (untrusted certs) but they will be stored and reused by caddy.  The rate limits for lets encrypt when using their staging environment is much much higher, so I think this is a solution to your problem.  Self_signed certs are really for installations that do not allow access in on :443

**Comment by princemaple** [comment] 2017-08-11 10:08
Letsencrypt works for local dev? I did not know that. How? The domain practically does not exist.

**Comment by mholt** [comment] 2017-08-11 17:24
"Dev sites" _is_ a bit ambiguous, yes; I do use LE's staging endpoint for "local" development sometimes; it works if the domain's records point to your home machine and you configure your home network to forward ports. But for _purely local_ development, no, it will not work, unless you set up your own Boulder instance internally.

But that's a hassle. What if Caddy persists self-signed certs for 30 days in `$CADDYPATH/self_signed`?

**Comment by twdkeule** [comment] 2017-08-11 21:47
It does fit nicely with the "easy to use" objective of Caddy.
No need to create a self signed certificate yourself. If this feature existed a few months ago I would have used it :smile:

**Comment by mholt** [comment] 2017-08-11 22:01
@twdkeule To be clear, it does already exist (`tls self_signed`), but it's a different cert each time you run Caddy. (The intent was always to make the developer rely on self-signed certificates as seldom as possible.)

**Comment by princemaple** [comment] 2017-08-11 22:29
> What if Caddy persists self-signed certs for 30 days in $CADDYPATH/self_signed?

It would make my life much easier :) no longer need to click 3 times to add an exception every time I restart caddy. Doing it once a month is totally acceptable.

**Comment by francislavoie** [comment] 2017-08-12 01:05
@mholt I'm sure @twdkeule knows that, just that for persistence currently we have to generate the certificate separately and specify it with the `tls <cert> <key>` format.

Big 👍 from me to add persistence for self signed certs

**Comment by unquietwiki** [comment] 2017-09-29 02:52
I was talking with @mholt about this on the forums recently. We came to an agreement that the point of self-signed certs within Caddy, are by design temporary. However, I was able to modify https://github.com/openwisp/django-x509 to generate browser-friendly internal certs for my needs. We postulated if someone that knows Go could come up with a similar module for this.

**Comment by mholt** [comment] 2017-09-29 03:52
By way of update: This may become moot if localhost domains become trusted zones. There's a proposal along those lines. Until that is dismissed, I don't think I am interested in a change to Caddy that gives self-signed certs more weight than they're worth...

**Comment by OmgImAlexis** [comment] 2018-04-12 09:56
Another issue I've found is if you're using multiple sites with `self_signed` and you use `SIGUSR1` it will recreate all `self_signed` certs.

**Comment by tobya** [comment] 2018-04-12 13:42
@OmgImAlexis This is the intended behaviour.  Self Signed certs are meant as a temporary or interim solution rather than a permenant solution.

**Comment by tobya** [comment] 2018-04-12 13:43
I think I will close this issue as it is not currently planned for implementation.

**Closed by tobya** 2018-04-12 13:43 UTC
Labels: discussion, feature request

**Comment by mholt** [comment] 2020-03-16 04:19
Caddy 2 (starting with beta 17) solves this problem.
