### ISSUE TITLE
placeholder docs are incorrect: tls_version should be tls_protocol

### ISSUE THREAD

**Issue by augustoroman** [mholt/caddy#2263] opened 2018-08-10 03:47 UTC
https://caddyserver.com/docs/placeholders incorrect states:

> {tls_version} | The TLS protocol (version)

But the actual value is `{tls_protocol}`:

* https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/replacer.go#L427-L434

added recently by #2062 

I apologize that I don't know how to access the docs site, so I can't submit a PR.

**Comment by mholt** [comment] 2018-08-10 04:35
Thanks for reporting, but duplicate of #2146.

**Closed by mholt** 2018-08-10 04:35 UTC
