### ISSUE TITLE
--quic not work with the newest chrome 

### ISSUE THREAD

**Issue by liuyajun52** [mholt/caddy#1899] opened 2017-09-30 08:10 UTC
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.10.9
### 2. What are you trying to do?

I want to test quic protocol on my php website which deployed on may local computer.
### 3. What is your entire Caddyfile?
```text
localhost:443 10.97.182.96:443 {
    root /var/www/audio-label/public
    tls self_signed
    fastcgi / 127.0.0.1:9000 php
    rewrite {
        to {path} {path}/ /index.php?{query}
    }
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

sudo caddy  --quic --conf Caddyfile --log stdout
### 5. Please paste any relevant HTTP request(s) here.

for test ，I use chrome  59.0.3071.86 (64 bit) Linux stable
this host ip is 10.97.182.96
when I open a tab and vist https://10.97.182.96
I found in dev tools -- > Security tab

Secure connection
The connection to this site is encrypted and authenticated using TLS 1.2 (a strong protocol), ECDHE_ECDSA with X25519 (a strong key exchange), and AES_256_GCM (a strong cipher).

It seems like the connection is still tls,not quic.

I have tryed to start chrome like this
```bash
liuyajun@localhost ~> google-chrome \
                          --user-data-dir=/tmp/chrome \
                          --no-proxy-server \
                          --enable-quic \
                      -quic-host-whitelist="10.97.182.96" \
                      --origin-to-force-quic-on=10.97.182.96t:443
```
I just get ERR_QUIC_PROTOCOL_ERROR

I found this version of chrome does support QUIC_VERSION_35。When i visit google in 
chrome://net-internals/#quic I found it is show in QUIC sessions.
### 6. What did you expect to see?

page load in quic
### 7. What did you see instead (give full error messages and/or log)?

ERR_QUIC_PROTOCOL_ERROR

**Comment by francislavoie** [comment] 2017-09-30 08:22
Duplicate of https://github.com/mholt/caddy/issues/1858, it's coming once quic-go releases its update.

**Closed by francislavoie** 2017-09-30 08:22 UTC

**Comment by midzer** [comment] 2018-02-13 08:36
@luminais Latest Quic-go will be merged soon in https://github.com/mholt/caddy/pull/1968 for new caddy 0.10.11 release

**Comment by luminais** [comment] 2018-02-13 09:06
@midzer I'm playing with Caddy 0.10.10. Does caddy 0.10.10 not support QUIC_VERSION_39?

**Comment by luminais** [comment] 2018-02-13 12:42
@midzer 
I start chrome with switch --quic-version=QUIC_VERSION_38 and it works. 
The current version of QUIC chrome supported is 38.

The response headers from Caddy is : 
`accept-ranges:bytes
alt-svc:quic=":443"; ma=2592000; v="38,37,36,35"
content-encoding:gzip
content-length:389
content-type:text/html; charset=utf-8
date:Tue, 13 Feb 2018 12:30:20 GMT
etag:W/"p3yq94h0"
last-modified:Sun, 11 Feb 2018 01:46:16 GMT
server:Caddy
status:200
vary:Accept-Encoding`

Finally chrome still use HTTP2 to access the server.

**Comment by luminais** [comment] 2018-02-13 12:46
@midzer 
I start chrome with switch --quic-version=QUIC_VERSION_38 and it works. 
The current version of QUIC which chrome supported is 38.

The response headers from Caddy are : 
`accept-ranges:bytes
alt-svc:quic=":443"; ma=2592000; v="38,37,36,35"
content-encoding:gzip
content-length:389
content-type:text/html; charset=utf-8
date:Tue, 13 Feb 2018 12:30:20 GMT
etag:W/"p3yq94h0"
last-modified:Sun, 11 Feb 2018 01:46:16 GMT
server:Caddy
status:200
vary:Accept-Encoding`
which mean that Caddy support QUIC_VERSION_38,37,36,35, and chrome shuld use QUIC to access the server.
But finally, chrome still use HTTP2 to access the server.

**Comment by luminais** [comment] 2018-02-13 12:49
@midzer
I start chrome with switch --quic-version=QUIC_VERSION_38 and it works.
The current version of QUIC which chrome supported is 38.

The response headers from Caddy are :
`accept-ranges:bytes 
alt-svc:quic=":443"; ma=2592000; v="38,37,36,35" 
content-encoding:gzip 
content-length:389 
content-type:text/html; charset=utf-8 
date:Tue, 13 Feb 2018 12:30:20 GMT 
etag:W/"p3yq94h0" 
last-modified:Sun, 11 Feb 2018 01:46:16 GMT 
server:Caddy 
status:200 
vary:Accept-Encoding`
which mean that Caddy support QUIC_VERSION_38,37,36,35, and chrome shuld use QUIC to access the server.
But finally, chrome still use HTTP2 to access the server.

**Comment by luminais** [comment] 2018-02-13 12:50
@midzer
I start chrome with switch --quic-version=QUIC_VERSION_38 and it works.
The current version of QUIC which chrome supported is 38.

The response headers from Caddy are :
**accept-ranges:bytes 
alt-svc:quic=":443"; ma=2592000; v="38,37,36,35" 
content-encoding:gzip 
content-length:389 
content-type:text/html; charset=utf-8 
date:Tue, 13 Feb 2018 12:30:20 GMT 
etag:W/"p3yq94h0" 
last-modified:Sun, 11 Feb 2018 01:46:16 GMT 
server:Caddy 
status:200 
vary:Accept-Encoding**
which mean that Caddy support QUIC_VERSION_38,37,36,35, and chrome shuld use QUIC to access the server.
But finally, chrome still use HTTP2 to access the server.

**Comment by mholt** [comment] 2018-02-13 15:36
Please wait until the next release (0.10.11) for the latest QUIC support.
