### ISSUE TITLE
HTTPS serving halts after cert renewal fails for some hosts (although it shouldn't)

### ISSUE THREAD

**Issue by radomirml** [mholt/caddy#1279] opened 2016-11-29 22:01 UTC
### 1. What version of Caddy are you running (`caddy -version`)?

Own build with a custom plugin. The same issue experienced merged with today's master but also with 0.9.3.

### 2. What are you trying to do?

The server runs as a transparent proxy with a custom plugin implementing some content filtering.

### 3. What is your entire Caddyfile?

Caddyfile is generated (registered CaddyfileLoader) with a list of hosts for proxying.
Hosts resolve to server using CNAME of the service. A typical host definition in Caddyfile looks like this:

```
https://host1.client1.com, http://host1.client1.com, https://host2.client1.com, http://host2.client1.com {

  myplugin {
    client 	"client_id"
  }

  header / Server "MyService"

  proxy / https://upstream.example.net/ {
    header_upstream Host upstream.example.net
    header_downstream -Server ""
  }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Running service on Google Container Engine (Kubernetes) with a Docker file that starts the server with:

```/app/myservice-proxy -agree -email support@example.com -log stdout```

### 5. What did you expect to see?

Automatic https with certificates for hosts obtained from Let's Encrypt worked so I expected renewals to work as well.

### 6. What did you see instead (give full error messages and/or log)?

After weeks of working correctly, the last few days the service would hang after 6-12 hours. The last logged messages were:

```
2016/11/28 20:26:50 in RenewManagedCertificates
2016/11/28 20:26:50 [DEBUG] RenewManagedCertificates - check expiration for myservice.example.com (expires in 1533h27m9.144888136s)
2016/11/28 20:26:50 [DEBUG] RenewManagedCertificates - check expiration for (expires in 1179h56m9.144822329s)
2016/11/28 20:26:50 [DEBUG] RenewManagedCertificates - check expiration for host2.client1.com (expires in 678h24m9.144817546s)
2016/11/28 20:26:50 [INFO] Certificate for [host2.client1.com] expires in 678h24m9.144817546s; attempting renewal
2016/11/28 20:26:51 [INFO][host2.client1.com] acme: Trying renewal with 678 hours remaining
2016/11/28 20:26:51 [INFO][host2.client1.com] acme: Obtaining bundled SAN certificate
2016/11/28 20:26:51 [INFO][host2.client1.com] acme: Trying to solve HTTP-01
2016/11/28 20:26:52 [INFO][host2.client1.com] Served key authentication
2016/11/28 20:26:53 [ERROR] Renewing: acme: Error 400 - urn:acme:error:connection - DNS problem: networking error looking up CAA for com
Error Detail:
Validation for host2.client1.com:80
Resolved to:
104.111.111.111
Used: 104.111.111.111

; trying again in 10s
2016/11/28 20:27:03 [INFO][host2.client1.com] acme: Trying renewal with 678 hours remaining
2016/11/28 20:27:03 [INFO][host2.client1.com] acme: Obtaining bundled SAN certificate
2016/11/28 20:27:04 [INFO][host2.client1.com] acme: Trying to solve TLS-SNI-01
```

(I obfuscated real host names and IP addresses.) The host name it was failing on was properly resolving to the service. Some of the  messages are not logged by the original Caddy, I added them to code trying to troubleshoot this.

Some observations about the service in hanged state:

* HTTP requests were handled fine, HTTPS not. HTTPS requests would time out.
* Chrome instance that was accessing hosted/proxied site before the service hanged, could still use the host via HTTPS. (I guess it was using cached cert info or reusing already open connection.)
* Other browsers could not access any of hosted sites via HTTPS nor did the above mentioned Chrome instance in Incognito mode.

After restart, the service would eventually start after failing on cert renewal again (although somewhat differrent error messages) and finally giving up for some time.

Now, I added http handler to trigger _caddytls.RenewManagedCertificates(false)_ manually. **Although Caddy failed to renew certs on server start, when invoked manually (triggering handler via URL) renewal worked**:

```
Triggering certs renewal
2016/11/29 17:55:58 in RenewManagedCertificates
2016/11/29 17:55:58 [DEBUG] RenewManagedCertificates - check expiration for myservice.example.com (expires in 1158h27m1.094100987s)
2016/11/29 17:55:58 [DEBUG] RenewManagedCertificates - check expiration for host1.client1.com (expires in 663h21m1.094062916s)
2016/11/29 17:55:58 [INFO] Certificate for [host1.client1.com] expires in 663h21m1.094062916s; attempting renewal
2016/11/29 17:55:59 [INFO][host1.client1.com] acme: Trying renewal with 663 hours remaining
2016/11/29 17:55:59 [INFO][host1.client1.com] acme: Obtaining bundled SAN certificate
2016/11/29 17:55:59 [INFO][host1.client1.com] acme: Trying to solve HTTP-01
2016/11/29 17:55:59 [INFO][host1.client1.com] Served key authentication
2016/11/29 17:56:00 [INFO][host1.client1.com] The server validated our request
2016/11/29 17:56:00 [INFO][host1.client1.com] acme: Validations succeeded; requesting certificates
2016/11/29 17:56:00 [INFO] acme: Requesting issuer cert from https://acme-v01.api.letsencrypt.org/acme/issuer-cert
2016/11/29 17:56:00 [INFO][host1.client1.com] Server responded with a certificate.
2016/11/29 17:56:00 [DEBUG] RenewManagedCertificates - check expiration for host2.client1.com (expires in 656h54m59.132948753s)
2016/11/29 17:56:00 [INFO] Certificate for [host2.client1.com] expires in 656h54m59.132948753s; attempting renewal
2016/11/29 17:56:00 [INFO][host2.client1.com] acme: Trying renewal with 656 hours remaining
2016/11/29 17:56:00 [INFO][host2.client1.com] acme: Obtaining bundled SAN certificate
2016/11/29 17:56:01 [INFO][host2.client1.com] acme: Trying to solve HTTP-01
2016/11/29 17:56:01 [INFO][host2.client1.com] Served key authentication
2016/11/29 17:56:02 [INFO][host2.client1.com] The server validated our request
2016/11/29 17:56:02 [INFO][host2.client1.com] acme: Validations succeeded; requesting certificates
2016/11/29 17:56:02 [INFO] acme: Requesting issuer cert from https://acme-v01.api.letsencrypt.org/acme/issuer-cert
2016/11/29 17:56:02 [INFO][host2.client1.com] Server responded with a certificate.
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Not sure. For now I'm sending my findings in case anyone has an idea what could be wrong.

**Comment by ktkaushik** [comment] 2016-11-30 05:48
+1 I got the same error last night. @shubhamsoni92

**Comment by mholt** [comment] 2016-11-30 06:04
@ktkaushik You need to upgrade. :wink:

@radomirml You have a lot of layers to your infrastructure. It could be any number of things causing it, and I don't suspect Caddy at this point.

**Comment by ktkaushik** [comment] 2016-11-30 06:45
@mholt can you please point me in the right direction for upgrading ? I remember when i installed on my ubuntu server, i had to google quite a bit. :)

**Comment by mholt** [comment] 2016-11-30 06:48
@ktkaushik [Download the latest version](https://caddyserver.com/download), replace binary, restart process. Easy. :)

**Comment by ktkaushik** [comment] 2016-11-30 09:40
Thanks @mholt

**Comment by radomirml** [comment] 2016-11-30 13:35
@mholt I agree, many layers although I find it strange that renewal doesn't work from Caddy's maintenance loop but it does when invoked from http handler. I'll try to isolate and reproduce the issue in dev environment.

Do you possibly have a dependency list of vendor packages (like a glide lock file or equivalent)? It would be useful to know versions of dependency packages the official Caddy is built and tested against.

**Comment by mholt** [comment] 2016-11-30 15:19
No, but I don't think you have a dependency problem either. I'm almost sure it's networking or infrastructure or system environment-related.

**Comment by mholt** [comment] 2017-01-08 07:17
Hmm. The `Error 400 - urn:acme:error:connection - DNS problem: networking error looking up CAA for com` error sounds like a DNS problem, or some network issue between LE and your DNS. The challenges it succeeded on used the HTTP challenge, not the TLS-SNI challenge, which makes me wonder if something is up with that. (Does your Caddyfile have any wildcard characters in the site addresses that are defined?)

I'm going to close this issue for now, unless it can be pinpointed as a problem with Caddy -- as right now I'm not really convinced that it is. If it is, and it is caused by #1157, then the discussion could continue in that issue instead. Hope that's okay. :)

**Closed by mholt** 2017-01-08 07:17 UTC
