### ISSUE TITLE
Reverse Proxy Caches Host Headers

### ISSUE THREAD

**Issue by martindale** [mholt/caddy#944] opened 2016-07-19 20:32 UTC
#### 1. What version of Caddy are you running (`caddy -version`)?
0.9.0

#### 2. What are you trying to do?
Run a reverse proxy

#### 3. What is your entire Caddyfile?
```text

soundtrack.io:443 {
  tls /somepath/soundtrack.io.crt /somepath/soundtrack.io.key
  proxy / localhost:13000 {
    websocket
    header_upstream Host soundtrack.io
  }
}

*.soundtrack.io:443  {
  tls /somepath/soundtrack.io.crt /somepath/soundtrack.io.key
  proxy / localhost:13000 {
    websocket
    header_upstream Host {hostonly}
    proxy_header Host {hostonly}
  }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy`, run directly.  Orchestration via `pm2 run caddy`, but not relevant.

#### 5. What did you expect to see?
Requests to `soundtrack.io` should serve our index page (a list of available subdomains), and then accessing each individual subdomain (i.e., `coding.soundtrack.io` vs. `chill.soundtrack.io`) should pass the appropriate header to the backend.

#### 6. What did you see instead (give full error messages and/or log)?
All subdomains are routed to whatever the _first_ subdomain is routed to.  If `coding.soundtrack.io` is requested first, all subsequent requests to _any_ subdomain (including `chill.soundtrack.io`) will pass the `coding.soundtrack.io` header.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
See above config.

**Comment by mholt** [comment] 2016-07-19 20:57
Hmm, duplicate of #916. @pedronasser we really gotta find a better (working) fix for that. :smile:

**Closed by mholt** 2016-07-19 20:57 UTC
