### ISSUE TITLE
Caddy uses wrong certificate when combining wildcard and non-wilcard certs

### ISSUE THREAD

**Issue by thorstenkramm** [mholt/caddy#1791] opened 2017-07-29 10:44 UTC
### version of Caddy 
Caddy 0.10.6 but happens with Caddy 0.10.5 too. Other versions not tested.

### Trying to setup virtual hosts using wildcard certs for some and none-wildcard certs for others

I've some subdomains like 
* blog.example.com
* my.example.com
* login.example.com

They are setup properly all using the same wildcard ssl cert bought from AlphaSSL.

There is also the top level domain example.com using a separated ssl certificate.
The setup is split into four files, one for each domain. 

The main Caddyfile `/etc/caddy/Caddyfile` includes them all via
 ```
import conf.d/*.conf
```

#### Problem
When the last file inside `conf.d` uses a wildcard certificate this certificate is used for all subdomains. The `tls`section of all the other configuration files is ignored.

If the `conf.d` folder looks like this:
```
example.com.conf
login.example.com.conf
my.example.com.conf
```

then the last file is loaded last and even for example.com the certificates from my.example.com is taken.

When I rename `example.com.conf` to `z-example.com.conf` everything works as expected. 

### 4. How did you run Caddy?
```
su - www-data -s /bin/sh -c \
  "ulimit -n 8192; /usr/bin/nohup /usr/local/bin/caddy \
  -log /tmp/caddy-start.log \
  -email info@cloudradar.io \
  -agree=true \
  -conf=/etc/caddy/Caddyfile \
  -root=/var/tmp \
  -pidfile=/var/run/caddy/caddy.pid >> /tmp/caddy-start.log 2>&1 &" >>/tmp/caddy-start.log
```
Using Ubuntu Linux 16.04 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### reproduce the bug
Have at least two commercial ssl certificates. One is a wildcard certificate and one is a standard certificate for a single hostname of the same domain the wildcard certificate covers, like `domain.tld` and `*.domain.tld`.

Put this as the first tls-line:
```
tls domain.tld.crt domain.tld.key
```
Put this as the last tls-line in your configuration:
```
tls wildcard.domain.tld.crt wildcard.domain.tld.key
```

The whole configuration can look like this
```
https://domain.tld {
    root /var/www/domain.tld
    tls domain.tld.crt domain.tld.key
}

https://sub.domain.tld {
    root /var/www/sub.domain.tld
    tls wildcard.domain.tld.crt wildcard.domain.tld.key
}
```

You will notice, for domain.tld the wildcard certificate will be used.
Change the order of the two blocks, which means load the wildcard first.
Then everything works as expected. doamain.tld uses the proper certificate.

**Comment by mholt** [comment] 2017-07-29 22:59
Hi @thorstenkramm - thanks for the report. Unfortunately, I'm not able to verify/recreate this bug.

This is my config:

```
test.dev:4443 {
	root test1/html
	tls test.dev.crt test.dev.key
}

sub1.test.dev:4443 {
	root test2/html
	tls wildcard.test.dev.crt test.dev.key
}
```

And it loads the proper certificates:

![screen shot 2017-07-29 at 4 56 05 pm](https://user-images.githubusercontent.com/1128849/28749273-21bcb576-747f-11e7-8759-27658bdc06a6.png)


![screen shot 2017-07-29 at 4 56 30 pm](https://user-images.githubusercontent.com/1128849/28749279-28d59ee0-747f-11e7-931d-6f7d58c425a4.png)

(I have test.dev and sub1.test.dev routed to 127.0.0.1 in my hosts file.)

Is this setup different from what you have, as far as you can tell?

If you post the actual domains where this is happening maybe we can verify it from our machines.

**Comment by thorstenkramm** [comment] 2017-08-07 18:18
I'll describe exactly what happens to me.

My whole configuration looks like this:
```bash
root@web-cloudradar-io:/etc/caddy/conf.d# ls -l
total 24
-rw-r--r-- 1 root www-data 338 Jul 29 09:19 bitbucket-deploy.conf
-rw-r--r-- 1 root www-data 436 Jul 29 09:03 blog.cloudradar.io.conf
-rw-r--r-- 1 root root     116 Apr 13 07:51 default.conf
-rw-r--r-- 1 root www-data 423 Jul 29 09:04 downloads.cloudradar.io.conf
-rw-r--r-- 1 root www-data 569 Jul 28 13:55 y-cloudradar.info.conf
-rw-r--r-- 1 root www-data 654 Jul 29 09:37 z-cloudradar.io.conf
```
The content of all these files is the following:
```bash
root@web-cloudradar-io:/etc/caddy/conf.d# for file in *;do echo "## $file ##";cat $file;done
## bitbucket-deploy.conf ##
https://cloudradar.info:8443/deploy {
    tls /etc/ssl/certs/cloudradar.info/cloudradar.info.chained.crt /etc/ssl/certs/cloudradar.info/cloudradar.info.key
    root /var/www/deploy/
    fastcgi / /run/php/php7.0-fpm.sock php
    log /var/log/caddy/deploy-access.log
    errors /var/log/caddy/deploy-error.log
    basicauth / git rjf44
}

## blog.cloudradar.io.conf ##
https://blog.cloudradar.io {
    proxy / http://localhost:2368 {
        header_upstream Host {host}
        header_upstream X-Real-IP {remote}
        header_upstream X-Forwarded-For {remote}
        header_upstream X-Forwarded-Proto {scheme}
    }
    tls /etc/ssl/certs/cloudradar.io/_wildcard.cloudradar.io.chained.crt /etc/ssl/certs/cloudradar.io/privkey.pem
}

http://blog.cloudradar.io {
    redir / https://blog.cloudradar.io
}
## default.conf ##
http://0.0.0.0:80 {
    root /var/www/caddy
    log /var/log/caddy/access.log
    errors /var/log/caddy/error.log
}
## downloads.cloudradar.io.conf ##
https://downloads.cloudradar.io {
    root /var/www/downloads.cloudradar.io/
    tls /etc/ssl/certs/cloudradar.io/_wildcard.cloudradar.io.chained.crt /etc/ssl/certs/cloudradar.io/privkey.pem
    basicauth /admin admin izeeBahW9pee
    browse /
    filemanager /admin {
    	show           ./downloads.cloudradar.io
    	allow_commands true
    	allow_command  rm
    	allow_command  mv
    	allow          dotfiles
    }
}
## y-cloudradar.info.conf ##
# This file is maintened by salstack and was build dynamically using jinja
# Do not edit. All changes will be overwritten
https://cloudradar.info:443 {
   root /var/www/cloudradar.info/pub/
   fastcgi / /run/php/php7.0-fpm.sock php
   log /var/log/caddy/cloudradar.info-access.log
   errors /var/log/caddy/cloudradar.info-error.log
   tls /etc/ssl/certs/cloudradar.info/cloudradar.info.chained.crt /etc/ssl/certs/cloudradar.info/cloudradar.info.key
   rewrite / {
     ext !.png !.css !.js !.otf !.ttf !.woff !.woff2 !.svg !.ico !.gif !.jpg
     to /router.php
    }
}
## z-cloudradar.io.conf ##
https://cloudradar.io {
    root /var/www/cloudradar.io/pub/
    fastcgi / /run/php/php7.0-fpm.sock php
    log /var/log/caddy/access.log
    errors /var/log/caddy/error.log
    #tls /etc/ssl/certs/cloudradar.io/thawte/cloudradar.io.chained.crt /etc/ssl/certs/cloudradar.io/thawte/server.key
    tls /etc/ssl/certs/cloudradar.io/cloudradar.io.chained.crt /etc/ssl/certs/cloudradar.io/privkey.pem
    rewrite / {
      ext !.png !.css !.js !.otf !.ttf !.woff !.woff2 !.svg !.ico !.gif !.jpg
      to /router.php
    }
}

http://www.cloudradar.io {
    redir / https://cloudradar.io{uri}
}

http://cloudradar.io {
    redir / https://cloudradar.io{uri}
}
``` 

With this configuration, all works fine. For the domain cloudradar.io the correct certificate is used, which can be verified with the following command, for example
```bash
curl -v -I https://cloudradar.io
* Rebuilt URL to: https://cloudradar.io/
*   Trying 52.166.127.179...
* TCP_NODELAY set
* Connected to cloudradar.io (52.166.127.179) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: cloudradar.io
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> HEAD / HTTP/1.1
> Host: cloudradar.io
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: no-store, no-cache, must-revalidate
< Content-Type: text/html; charset=UTF-8
Content-Type: text/html; charset=UTF-8
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Pragma: no-cache
Pragma: no-cache
< Server: Caddy
Server: Caddy
< Set-Cookie: PHPSESSID=dv3so1if7bko79crgm24lukr97; path=/
Set-Cookie: PHPSESSID=dv3so1if7bko79crgm24lukr97; path=/
< Date: Mon, 07 Aug 2017 18:06:24 GMT
Date: Mon, 07 Aug 2017 18:06:24 GMT

< 
* Connection #0 to host cloudradar.io left intact
``` 

### Now the problem
When I change the order of the files in the `conf.d` folder using
```
mv z-cloudradar.io.conf a-cloudradar.io.conf
``` 
which makes `a-cloudradar.io.conf` the first file, the wrong certificate is used:
```bash
curl -v -I https://cloudradar.io
* Rebuilt URL to: https://cloudradar.io/
*   Trying 52.166.127.179...
* TCP_NODELAY set
* Connected to cloudradar.io (52.166.127.179) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.cloudradar.io
* Server certificate: AlphaSSL CA - SHA256 - G2
* Server certificate: GlobalSign Root CA
> HEAD / HTTP/1.1
> Host: cloudradar.io
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: no-store, no-cache, must-revalidate
< Content-Type: text/html; charset=UTF-8
Content-Type: text/html; charset=UTF-8
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Pragma: no-cache
Pragma: no-cache
< Server: Caddy
Server: Caddy
< Set-Cookie: PHPSESSID=i4e230ri7kj3kvl9kdamed10d2; path=/
Set-Cookie: PHPSESSID=i4e230ri7kj3kvl9kdamed10d2; path=/
< Date: Mon, 07 Aug 2017 18:05:49 GMT
Date: Mon, 07 Aug 2017 18:05:49 GMT

< 
* Connection #0 to host cloudradar.io left intact
```

**Comment by mholt** [comment] 2017-08-07 23:34
Unfortunately, I still can't reproduce it.

Using this Caddyfile:

```
import issue1791/*.conf
```

And:

```bash
$ ls -l issue1791/
total 24
-rw-r--r--@ 1 matt  staff  70 Aug  7 17:19 a-test.dev.conf
-rw-r--r--@ 1 matt  staff  83 Aug  7 17:20 sub1.test.dev.conf
-rw-r--r--@ 1 matt  staff  83 Aug  7 17:20 sub2.test.dev.conf
```

And:

```bash
$ for file in issue1791/*;do echo "## $file ##";cat $file;echo;done
## issue1791/a-test.dev.conf ##
test.dev:4443 {
	browse
	root ../../
	tls test.dev.crt test.dev.key
}

## issue1791/sub1.test.dev.conf ##
sub1.test.dev:4443 {
	browse
	root ../../
	tls wildcard.test.dev.crt test.dev.key
}
## issue1791/test2.test.dev.conf ##
sub2.test.dev:4443 {
	browse
	root ../../
	tls wildcard.test.dev.crt test.dev.key
}
```

Obviously my self-signed certs are not trusted, but Chrome says it's seeing the right one:

![screen shot 2017-08-07 at 5 30 22 pm](https://user-images.githubusercontent.com/1128849/29049957-2ff9d92a-7b96-11e7-9462-337e796b1c6b.png)

I haven't used curl because my self-signed certs aren't trusted, and -k reminds me that "disabling hostname validation also disables SNI" and SNI is required in this situation. (I assume your curl is using SNI? Have you been able to verify that it is?)

Do you have any other ideas for reproducing this? Can you set this up on another domain where I can see it?

**Comment by mholt** [comment] 2017-09-12 04:15
I haven't been able to replicate this behavior, unfortunately. Until someone else does _or_ new details surface, I think the only thing I can really do is close the issue. Feel free to reopen if there's anything to add!

**Closed by mholt** 2017-09-12 04:15 UTC
Labels: help wanted
