### ISSUE TITLE
URL case sensitivity

### ISSUE THREAD

**Issue by alexxkn** [mholt/caddy#2023] opened 2018-02-14 13:59 UTC
### 1. What version of Caddy are you using (`caddy -version`)?
go get from master 07.02.2018. I think it is version 0.10.10+ :)

### 2. What are you trying to do?
I'm trying to configure two identical URLs with different case
```
site.tld/autodiscover
site.tld/Autodiscover
```

### 3. What is your entire Caddyfile?
```
site.ltd/autodiscover, site.ltd/Autodiscover {
   
    rewrite / {
        regexp /(?:a|A)utodiscover.xml
        to /autodiscover.xml
    }

    root /var/www/autodiscover
}

site.ltd {
    root /var/www/site.ltd

    rewrite {
        to {path} {path}/ /
    }
}
```
### 6. What did you expect to see?
Since these are two different addresses (/autodiscover, /Autodiscover) I want to get content from both of them

### 7. What did you see instead (give full error messages and/or log)?
duplicate site address: site.ltd/autodiscover

**Comment by mholt** [comment] 2018-02-14 17:20
Hi, thanks for following the issue template! I think this is a duplicate of #1517. Closing in favor of that one.

**Closed by mholt** 2018-02-14 17:20 UTC

**Comment by alexxkn** [comment] 2018-02-15 06:46
oh, I was not careful enough :)
Thanks for your reply. I'll wait for a solution!

**Comment by mholt** [comment] 2018-02-15 07:06
@alehano Feel free to submit one! We take PRs. :)

**Comment by alexxkn** [comment] 2018-02-15 07:29
Well, yep, we can do it. We will try to provide changes in the near future.
