### ISSUE TITLE
Windows: factcgi /php php Bad Gateway 502

### ISSUE THREAD

**Issue by Alber70g** [mholt/caddy#52] opened 2015-05-05 09:21 UTC
I've tried to get a php Hello World running but all I get is a 502 Bad Gateway. Markdown does actually work. 

Caddyfile
```
localhost:2020
markdown /md
fastcgi /php php
log access.log
errors error.log
```

Inside /php I have `index.php` with html and php.

Access log is filling nice when navigating to `/md`. 
Error log is empty when the 502 occurs.

[edit]
Or am I understanding it wrong and Caddy is only the proxy to the fastcgi server?
[/edit]

**Comment by abiosoft** [comment] 2015-05-05 11:14
According to your Caddyfile.

navigating to `/md` will be handled by markdown
navigating to `/php` will be handled by fastcgi with php.

On which path are you getting 502 ?

**Comment by Alber70g** [comment] 2015-05-05 11:28
@abiosoft I'm getting the error on `/php`.

**Comment by abiosoft** [comment] 2015-05-05 11:33
@Alber70g What port is fastcgi running on ? You need to have php-cgi.exe running.
Then modify you Caddyfile to include the port.
```
localhost:2020
markdown /md
fastcgi /php 127.0.0.1:9000 php 
log access.log
errors error.log
```

**Comment by Alber70g** [comment] 2015-05-05 12:03
@abiosoft Thank you! I've got it running now. I din't have a port specified when starting `php-cgi`: `php-cgi -b 127.0.0.1:9000`.

**Comment by abiosoft** [comment] 2015-05-05 12:09
Glad its working now.

**Comment by mholt** [comment] 2015-05-05 14:21
Pro tip:

```
startup "php-cgi -b 127.0.0.1:9000"
```

In your Caddyfile will launch php-cgi when Caddy starts. You can also turn it off in a similar way with the `shutdown` directive.

**Comment by Alber70g** [comment] 2015-05-05 15:17
@mholt Yes, thats what I thought aswell, but that isn't working. It totally doesn't do what it should. It seems like it stops sending requests anywhere, or it stops starting. 

Current config:

```
127.0.0.1:2020
startup "php-cgi.exe -b 127.0.0.1:9000"
fastcgi / 127.0.0.1:9000 php {
    ext .php
    index index.example.php
}
markdown /md
log access.log
errors error.log
```

What I see is the following:

- php-cgi starts (is visible in the task manager: `php-cgi -b 127.0.0.1:9000`

So php-cgi starts seemingly correct. But after that nothing works. I get `ERR_CONNECTION_REFUSED` in Chrome on both `localhost:2020` and `localhost:2020/md/test.md`.

**Comment by mholt** [comment] 2015-05-05 15:39
What does your error log say?

(Also, you don't need `ext .php` in the fastcgi block - that's already set when you specified the `php` preset)

**Comment by Alber70g** [comment] 2015-05-05 16:04
The error log is empty. And I've downloaded it from the website.

**Comment by mholt** [comment] 2015-05-05 16:15
Okay. Are you loading "localhost:2020" or "127.0.0.1:2020"  in the browser? Try both and let me know.

**Comment by Alber70g** [comment] 2015-05-05 16:39
I'm trying both. They don't show anythign and give no errors in the error log

**Comment by mholt** [comment] 2015-05-05 16:41
Phooey. Can you strip everything out of your Caddyfile (except the first line) and try it? Then add in one line at a time, retrying each time. And report back which line causes it to stop working? This will help us track down where I need to add some trace statements for a verbose/debug mode.

**Comment by Alber70g** [comment] 2015-05-05 16:45
Only
```
127.0.0.1:2020
```
*Gives:* `No such host at 127.0.0.1:2020`

```
startup "php-cgi -b 127.0.0.1:9000"
127.0.0.1:2020
```
*Gives:* `ERR_CONNECTION_REFUSED`. 

I'd say this should be enough. Everything I add after will result in `ERR_CONNECTION_REFUSED`.

When I start it separately it runs. Maybe because the `startup` is blocking, it just stops after running that command. Is there a way to start `php-cgi` silently/non-blocking?

**Comment by Alber70g** [comment] 2015-05-05 16:57
I was thinking that would be the problem. So I found a small tool to start php-cgi non-blocking. http://wiki.nginx.org/PHPFastCGIOnWindows here is a tool mentioned called `RunHiddenConsole.exe` which can be used. Config looks like this now

```
localhost:2020, 127.0.0.1:2020
#startup "runhiddenconsole.exe php-cgi -b 127.0.0.1:9000"
fastcgi / 127.0.0.1:9000 php {
    index index.example.php
}
markdown /md
log access.log
errors error.log
```

**Comment by mholt** [comment] 2015-05-05 16:59
That would do it, indeed. There isn't currently a way to run a command in the background, but there needs to be. I'm working on that right now, so you don't have to use an external tool.

When this is done today, you can suffix the command with `&` (like in Linux) to run it in the background, for example:

```
startup php-cgi -b 127.0.0.1:9000 &
```

(I'm also eliminating the need for the quotes)

**Comment by Alber70g** [comment] 2015-05-05 17:02
Ah that would be awesome indeed. If you want I can do further testing when it's finished :+1:

**Comment by mholt** [comment] 2015-05-05 17:03
Excellent. Would you like me to send you an updated binary or do you have Go installed?

Thanks for your help, by the way.

**Comment by Alber70g** [comment] 2015-05-05 17:04
I can install Go and create my own binary for Windows. It shouldn't be too much hassle. If you can easily provide a birnary that is also nice.

**Comment by mholt** [comment] 2015-05-05 17:12
I've just pushed the fix. Here's a modified binary for you (I will delete it after today): https://drive.google.com/file/d/0B-OxZ0LoeTvGR2NpWDNNVk1pN0U/view?usp=sharing

**Comment by Alber70g** [comment] 2015-05-05 17:16
```
localhost:2020, 127.0.0.1:2020
startup php-cgi -b 127.0.0.1:9000 &
fastcgi / 127.0.0.1:9000 php {
    index index.example.php
}
markdown /md
log access.log
errors error.log
```
2015/05/05 19:15:04 GetFileInformationByHandle /dev/stdin: The handle is invalid.

**Comment by mholt** [comment] 2015-05-05 17:23
Okay, I've added stdin: https://drive.google.com/file/d/0B-OxZ0LoeTvGUndfTTNfNG93ckE/view?usp=sharing

**Comment by Alber70g** [comment] 2015-05-05 17:27
I'm getting the same error now.

**Comment by Alber70g** [comment] 2015-05-05 17:33
I got it running from source now so you can just push changes. I assume I need to do `go get github.com/mholt/caddy` to get the latest version? Is that correct?

And then `go install` and run the `caddy.exe`.

**Comment by mholt** [comment] 2015-05-05 17:47
@Alber70g Can you replace [this line](https://github.com/mholt/caddy/blob/33786408f0b1490ed20b867f123b6415312fae30/config/setup/startupshutdown.go#L43) with:

```go
cmd.Stdin = strings.NewReader("")
```

Then you can just do `go run main.go` from the project directory to build and run it right away. Does that fix it?

**Comment by Alber70g** [comment] 2015-05-05 17:52
Nope, doesn't fix it. Get the same error.

**Comment by mholt** [comment] 2015-05-05 17:54
Geez. What if you put a string in there like "Hello world" or something? I'm trying to determine why Windows thinks it's being given an invalid Stdin...

**Comment by Alber70g** [comment] 2015-05-05 17:58
Could it have to be something like this (it's Python but has to do Windows handles Stdin: https://bugs.python.org/issue3905)

**Comment by Alber70g** [comment] 2015-05-05 18:20
String in there doesn't gives an error. If you ment to do just `cmd.Stdin = "sdf"`: 
```
config\setup\startupshutdown.go:43: cannot use "sdf" (type string) as type io.Reader in assignment:
        string does not implement io.Reader (missing Read method)
```

**Comment by mholt** [comment] 2015-05-05 18:24
Sorry, I meant inside `strings.NewReader("")`

Like this: `strings.NewReader("Hello world")` - and that works, you say?

**Comment by Alber70g** [comment] 2015-05-05 18:28
In the `strings.NewReader("Hello world")` gives the same `The handle is invalid`. 

Maybe this will give some sort of a solution: http://stackoverflow.com/questions/23166468/how-can-i-get-stdin-to-exec-cmd-in-golang

**Comment by mholt** [comment] 2015-05-06 03:45
Okay, so the bug is not coming from the startup directive. I was able to reproduce this with help from a friend who has Windows and even without a Caddyfile, the same error was printed at startup. The error is actually coming from [here in main.go](https://github.com/mholt/caddy/blob/70d6caf95bc501fe8579097365eba23f557c9a12/main.go#L108-L111).

On Windows, when there is no data piped to Caddy, it brings up that error. When data is piped to Caddy, the error goes away, but then the application hangs on the ioutil.ReadAll call a few lines below, presumably because no EOF is reached. (That was tested by doing `echo "localhost:1234" | caddy` on Windows - I imagine echo is appending a line break?)

I need to do more research about how to tame stdin on Windows.

**Comment by Alber70g** [comment] 2015-05-06 06:45
Nice that you found that out. I'll just wait until you have a new version ;). I'm not good enough in Go to try things out myself. I really appreciate that you are so fast responding. Thanks a lot.

**Comment by mholt** [comment] 2015-05-06 15:28
@Alber70g No problem - I got a Windows VM running and was able to, I think, find a cross-platform solution to the problem. Would you please pull the latest (`go get -u github.com/mholt/caddy` should do it) and see if it works?

If not, ensure that lines 106-108 of main.go look exactly like this:

```go
// stdin
fi, err := os.Stdin.Stat()
if err == nil && fi.Mode()&os.ModeCharDevice == 0 {
```

**Comment by Alber70g** [comment] 2015-05-07 07:38
I'm currently not on my own machine where I have go installed. So could you send me the binary?

**Comment by Alber70g** [comment] 2015-05-07 09:32
Awesome! It's working fluently now :) Thanks a lot. I really appreciate your fast response!! Awesome!

**Comment by mholt** [comment] 2015-05-07 12:46
Cool - thank you so much for your help and patience!

**Closed** 2015-05-07 12:45 UTC
Labels: bug

**Comment by tobya** [comment] 2017-09-21 17:55
Thanks for the issue. Glad to hear your using docto. What happens if you save the html doc to disk from your browser then open in word and save as docx? Does it show then?
