### ISSUE TITLE
Reverse proxy unpredictable behavior

### ISSUE THREAD

**Issue by piotrkowalczuk** [mholt/caddy#1024] opened 2016-08-10 16:13 UTC
#### 1. What version of Caddy are you running (`caddy -version`)?

0.9.0

#### 2. What are you trying to do?

setup multiple virtual hosts that will work like reverse proxy to other containers

#### 3. What is your entire Caddyfile?
```text
# here because other it does not parse
localhost:80 {
}

prometheus.local.tld:8080, prometheus.stage.example.com:8080 {
	log stdout
	errors stdout
	gzip
	tls off

	proxy / prometheus:8080 {
		max_fails 0
		header_upstream X-Forwarded-For {remote}
		header_upstream X-Real-IP {remote}
		header_upstream X-Forwarded-Proto {scheme}
		header_upstream Host {host}
	}
}

sentry.local.tld:8080, sentry.stage.example.com:8080  {
	log stdout
	errors stdout
	gzip
	tls off

	proxy / sentry:8080 {
		max_fails 0
		header_upstream X-Forwarded-For {remote}
		header_upstream X-Real-IP {remote}
		header_upstream X-Forwarded-Proto {scheme}
		header_upstream Host {host}
	}
}

grafana.local.tld:8080, grafana.stage.example.com:8080  {
    log stdout
    errors stdout
    gzip
    tls off
    
	proxy / grafana:8080 {
		max_fails 0
		header_upstream X-Forwarded-For {remote}
		header_upstream X-Real-IP {remote}
		header_upstream X-Forwarded-Proto {scheme}
		header_upstream Host {host}
	}
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy -http2=false`

#### 5. What did you expect to see?

Being able to reach each virtual host through the browser.

#### 6. What did you see instead (give full error messages and/or log)?
__log:__
```
217.92.130.112 - [10/Aug/2016:15:44:21 +0000] "GET / HTTP/1.1" 502 40
10/Aug/2016:15:45:21 +0000 [ERROR 502 /] unreachable backend
```

__browser:__
```
502 Bad Gateway
```
browser hangs until timeout hits 10s and then shows error page. Single request does not hit `prometheus` or `grafana`. `sentry` works.

Each services knows its external address, through configuration.
Funny part is that it works locally but not on staging ;p

When i try to visit each website using corresponding port (defined in `docker-compose`) it works fine.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

it's not that easy ;)

**Comment by mholt** [comment] 2016-08-10 18:18
This is [expected](https://caddyserver.com/docs/proxy), since your first request returns a 502:

>  If a backend returns a status code of 200-399, then that backend is considered healthy. If it doesn't, the backend is marked as unhealthy for at least interval_duration and no requests are routed to it.

By setting max_fails to 0, you're telling Caddy that no matter how many times it gets a failure response, it should never mark that backend as down. Which, I admit, is a problem, but I don't know a good way to handle it yet. See https://github.com/mholt/caddy/issues/812#issuecomment-217690551. In fact, I think this is a duplicate of #754 so I will close this if that's alright.

Also:

> ```
> # here because other it does not parse
> localhost:80 {
> }
> ```

What's that all about?

**Closed by mholt** 2016-08-10 18:18 UTC

**Comment by piotrkowalczuk** [comment] 2016-08-10 21:04
Setting `max_fails` to `10` change nothing.

```
# here because other it does not parse
localhost:80 {
}
```

It has it roots in the past when i had problems when Caddyfile starts with `http://`

**Comment by kaihendry** [comment] 2016-09-07 05:53
I have a docker container [count](https://github.com/kaihendry/count) running like so behind Caddy:

    count.dabase.com {
            proxy / count:9000 {
                transparent
            }
    }

When I **hold down ctrl+r** upon https://count.dabase.com/ I get a **502 Bad Gateway** as if it was being throttled. If I pause for a few seconds, service resumes.

I'm confident it's a problem with caddy since I can ctrl+r upon http://count.dabase.com:9000/ with no issues.

**Comment by piotrkowalczuk** [comment] 2016-09-07 07:24
#### 1. What version of Caddy are you running (`caddy -version`)?

0.9.1

#### 3. What is your entire Caddyfile?

__Cadyfile__
```text
import ./Caddyfile.local
import ./Caddyfile.stage
```

__Cadyfile.stage__
```text
https://grafana.example.com  {
	tls <email>

	import ./Caddyfile.grafana
}

https://prometheus.example.com {
	tls <email>

	import ./Caddyfile.prometheus
}

https://sentry.example.com {
	tls <email>

	import ./Caddyfile.sentry
}

https://swagger.example.com  {
	tls <email>

	import ./Caddyfile.swagger
}
```

__Caddyfile.grafana__
```text
import ./Caddyfile.common

proxy / grafana:3000 {
	max_fails 100
	transparent
}
```

__Caddyfile.prometheus__
```text
import ./Caddyfile.common

proxy / prometheus:9090 {
	max_fails 100
	transparent
}
```

__Caddyfile.common__
```text
log stdout
errors stdout
gzip
root dist
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy -agree`


---------------

After update nothing changed.

**Comment by mholt** [comment] 2016-09-07 16:41
Hi, could you please open new issues and be sure to fill out all parts of the issue template? Thanks, that way we won't lose track of it in an older, closed, and duplicated issue.

**Comment by kaihendry** [comment] 2016-09-09 05:05
Without jumping hoops here, why not just re-open this issue? Your solution I think wasn't the answer for this issue.

**Comment by mholt** [comment] 2016-09-09 05:09
Because it's a duplicate and a new version of Caddy has been released since it was opened?
