### ISSUE TITLE
error with quic

### ISSUE THREAD

**Issue by zuohuadong** [mholt/caddy#2371] opened 2018-11-29 11:38 UTC
![image](https://user-images.githubusercontent.com/11203929/49219311-d8920300-f40d-11e8-8be0-2ce2b0b71481.png)

FROM abiosoft/caddy:0.11.1

WORKDIR /var/www

EXPOSE 80 443 2015

ENTRYPOINT ["/bin/parent", "caddy"]

# CMD ["--quic","--conf", "/etc/Caddyfile", "--log", "stdout", "--agree=$ACME_AGREE"]
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout", "--agree", "--quic"]

**Comment by francislavoie** [comment] 2018-11-29 16:45
Closing as a duplicate of #2346.

**Closed by francislavoie** 2018-11-29 16:45 UTC
