### ISSUE TITLE
[Feature] Implement public-key pinning 

### ISSUE THREAD

**Issue by HazCod** [mholt/caddy#1072] opened 2016-08-26 07:57 UTC
As caddy uses letsencrypt and so knows what certificates are fetched, it can implement public-key pinning.

https://scotthelme.co.uk/hpkp-http-public-key-pinning/

**Comment by mholt** [comment] 2016-08-26 15:15
Thanks for the request! Unfortunately, I don't feel comfortable implementing it at this time since I believe the site owner must be aware what is going on, even when the server automates pinning entirely, because they still could easily break it and DoS their site. See #720 which this is a duplicate of.

**Closed by mholt** 2016-08-26 15:15 UTC
Labels: duplicate, feature request
