### ISSUE TITLE
Hash breaks rewrite

### ISSUE THREAD

**Issue by tewe** [mholt/caddy#659] opened 2016-03-06 22:25 UTC
I replaced Apache's mod_userdir with Caddy, for a single user:

	rewrite /~tewe {
		r  (.*)
		to /{1}
	}

This works fine unless file names contain the # character. Those are only accessible using the actual path.

I confirmed that the regex matched by replacing it with "(#.*)".

If the filename starts with #, I get served a directory listing (browse is on), so somewhere the string seems to get split at that character.

**Comment by mholt** [comment] 2016-03-06 22:33
`#` is a hierarchical identifier (see [RFC 3986](https://tools.ietf.org/html/rfc3986), section 1.2.3); it indicates the beginning of the fragment, and as such, is not part of the path. To use a `#` in the file name you need to URL-encode it.

**Comment by tewe** [comment] 2016-03-06 22:36
The `#` always were encoded. In fact the URLs I used were copied from the HTML output by `browse`. And they worked just fine if I removed the `/~tewe` by hand instead of using `rewrite`.

**Comment by mholt** [comment] 2016-03-06 22:40
I don't follow... I'm going to need more details: what is your entire Caddyfile, what's the file/folder structure of the site, what's the full request URL, what's the expected results, and what's the actual results?

**Comment by tewe** [comment] 2016-03-06 22:55
```
$ mkdir sandbox
$ cd sandbox
$ cat > Caddyfile
:8080
browse
rewrite /~tewe {
    r  (.*)
    to /{1}
}
$ touch 'a @ test'
$ touch 'a # test'
$ caddy &
$ curl http://localhost:8080
<a href="./a%20%23%20test">
<a href="./a%20@%20test">
$ wget --spider http://localhost:8080/a%20@%20test
HTTP request sent, awaiting response... 200 OK
$ wget --spider http://localhost:8080/~tewe/a%20@%20test
HTTP request sent, awaiting response... 200 OK
$ wget --spider http://localhost:8080/a%20%23%20test
HTTP request sent, awaiting response... 200 OK
$ wget --spider http://localhost:8080/~tewe/a%20%23%20test
HTTP request sent, awaiting response... 404 Not Found
```

**Comment by mholt** [comment] 2016-03-06 23:01
Perfect, thanks! I was able to reproduce the behavior. Will look into this soon. /cc @abiosoft - the rewrite middleware doesn't handle encoded `#` characters very well.

**Comment by abiosoft** [comment] 2016-03-07 07:24
Oops. Having a look.

**Comment by abiosoft** [comment] 2016-03-17 09:16
The issue is caused by Go's regex. It decodes it back to `#` which then causes it to be treated as fragment and omitted later on.

A way out could be handling `#` and encoding it back if required but that looks hacky.

**Comment by abiosoft** [comment] 2016-03-18 06:08
This should be fixed now. 

Thanks.

**Closed by abiosoft** 2016-03-18 06:08 UTC
Labels: bug
