### ISSUE TITLE
QUIC server doesn't get a working TLS config

### ISSUE THREAD

**Issue by bprodoehl** [mholt/caddy#1483] opened 2017-02-28 17:10 UTC
### 1. What version of Caddy are you running (`caddy -version`)?
master, with golang 1.8.

### 2. What are you trying to do?
Run a HTTP/2 and QUIC proxy.  Using the 0.9.5 binary, it works, but runs into the common panic with POSTs and QUIC that has been fixed since 0.9.5. Swapping out the 0.9.5 binary with a build of master, produced by running build.bash, the QUIC portion listens on port 443 but just doesn't work. Debugging it further, it appears that the QUIC server doesn't get any certificate info in its config.

### 3. What is your entire Caddyfile?
```text
https://subdomain.mydomain.com {
      gzip
      tls /etc/caddy/certs/mydomain.com.crt /etc/caddy/certs/mydomain.com.key
      
      proxy / 172.17.0.3:80 {
        header_upstream Host {host}
        header_upstream X-Real-IP {remote}
        header_upstream X-Forwarded-For {remote}
        header_upstream X-Forwarded-Proto {scheme}
      }
}
```

Those are valid wildcard certs that work with HTTP/2, and work with HTTP/2+QUIC using the 0.9.5 binary.  Switching it to use Auto HTTPS with Lets Encrypt, the problem remains the same.

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```/usr/bin/caddy -quic --conf /etc/caddy/conf/Caddyfile --log stdout```

### 5. What did you expect to see?
Chrome and the quic_client in the chromium source should be able to talk to the server via QUIC.  With the 0.9.5 binary, they are.

### 6. What did you see instead (give full error messages and/or log)?
With a build of master, and QUIC debug logging enabled, I get this when trying to do a QUIC request:
```text
Internal error: no matching certificate found
Closing session with error: no matching certificate found
```
I added more debugging in lucas-clemente/quic-go around that certificate error, and it appears that there is just no certificate info in the config that it gets.  It still works over HTTP/2, and browsers are happy with the certs they get, but no QUIC.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Try to run a QUIC config that was working with 0.9.5, using a build of master.  Try to make a request with a QUIC client, and it will probably fail.

**Comment by bprodoehl** [comment] 2017-02-28 20:58
Building the v0.9.5 tag and latest quic-go with golang 1.8, I get the problem, but building the v0.9.5 tag and latest quic-go with golang 1.7, it works.  With the rework for golang 1.8 in master, it can't be built with golang 1.7, as you'd probably expect, but I figured it might be an interesting data point.

**Comment by MisssRain** [comment] 2017-03-01 03:39
caddy version, 0.9.5
my caddyfile
`localhost:443 {
		tls CertificateGenerator/out/leaf_cert.pem CertificateGenerator/out/leaf_cert.key 
        root example
        log ../access.log
}`
it is a self-signed CA following [https://github.com/GaetanoCarlucci/CertificateGenerator](url)

I run caddy on my OS X 10.12.3 `sudo ./caddy -quic`
when I browse https://localhost on chrome 56.0.2924.87 (64-bit), chrome://net-internals shows that it is running HTTP2, but **not quic**.
The response header is as follows,
`accept-ranges:bytes
alt-svc:quic=":443"; ma=2592000; v="36,35,34"
alternate-protocol:443:quic
content-length:176
content-type:text/html; charset=utf-8
date:Wed, 01 Mar 2017 03:35:29 GMT
etag:W/"58b5465e-b0"
last-modified:Tue, 28 Feb 2017 09:43:58 GMT
server:Caddy
status:200`

I am new for quic, I want to apply quic with the help of Caddy and do some tests comparing performances between HTTP/TCPs and QUIC. Would you please help me?~

**Comment by ssut** [comment] 2017-03-01 13:07
Same here with the latest version of caddy, quic-go, and Go(1.8). Here's the full log:

```
<- Reading packet 0x1 (1350 bytes) for connection 5345e346855c5e1d, unencrypted @ 22:04:47.781
	<- &frames.StreamFrame{StreamID: 1, FinBit: false, Offset: 0x0, Data length: 0x514, Offset + Data length: 0x514}
-> Sending packet 0x1 (29 bytes), unencrypted, @ 22:04:47.781
	-> &frames.AckFrame{LargestAcked: 0x1, LowestAcked: 0x1, AckRanges: []frames.AckRange(nil), DelayTime: 35.785µs}
Got CHLO:
	TCID: "\x00\x00\x00\x00"
	SRBF: "\x00\x00\x10\x00"
	MIDS: "d\x00\x00\x00"
	CFCW: "\x00\x00\xf0\x00"
	SFCW: "\x00\x00`\x00"
	VER : "Q035"
	ICSL: "\x1e\x00\x00\x00"
	CSCT: ""
	UAID: "Chrome/56.0.2924.87 Windows NT 10.0; Win64; x64"
	PDMD: "X509"
	CTIM: "\x8aƶX\x00\x00\x00\x00"
	SCLS: "\x01\x00\x00\x00"
	SNI : "ssut.me"
	CCS : "\x01\xe8\x81`\x92\x92\x1a\xe8~퀆\xa2\x15\x82\x91"
	MSPC: "d\x00\x00\x00"
	NONP: "\xd5%\x96\x04\xea\xf8\xcb\n\xb4\xb6\xa0\xf3\xe37\xc3\xe1\x8d\xc8\xccM@\xf7\xa3\x9e\x8b<@\x8b\xb8\xa8\x87\xdd"
	COPT: ""
	PAD : (998 bytes)

Internal error: no matching certificate found
Closing session with error: no matching certificate found
-> Sending packet 0x2 (59 bytes), unencrypted, @ 22:04:47.781
	-> &frames.ConnectionCloseFrame{ErrorCode:0x1, ReasonPhrase:"no matching certificate found"}

```

**Comment by mholt** [comment] 2017-03-01 16:18
I haven't seen this before... @marten-seemann: do you recognize this error? I don't recall any recent changes to our QUIC usage, but maybe I missed something.

**Comment by lucas-clemente** [comment] 2017-03-01 16:34
In quic-go we're emulating the way the Go net/tls package reads the certificate from the tls.Config. There might have been a change in Go 1.8 concerning that, we're investigating.

**Comment by mholt** [comment] 2017-03-01 16:53
We did change / refactor the way we prepare TLS configs for the servers since 0.9.5, so I'm not sure if that has something to do with it. But it shouldn't have changed the final tls.Config structs as far as certificates go... I'll see if I can play with this later today, but I'm still playing catch-up after an exam this week.

**Comment by lucas-clemente** [comment] 2017-03-01 17:50
I don't have a setup to reproduce this issue right now, but I fixed an issue in our tls.Config interpretation. Could you please try the branch from the [PR](https://github.com/lucas-clemente/quic-go/pull/459), fix-458, to check whether that resolves it?

**Comment by bprodoehl** [comment] 2017-03-01 18:14
Thanks so much for looking into this.  Unfortunately, the behavior looks the same with golang 1.8, caddy master (0a0d2cc) and quic-go fix-458 branch (1bb4a26).  Let me know if there's anything I can provide to get you a setup that reproduces this.

**Comment by lucas-clemente** [comment] 2017-03-01 20:04
I found the issue. There's a new field in the tls.Config, GetConfigForClient which we currently ignore. Fix is coming.

**Comment by lucas-clemente** [comment] 2017-03-01 20:15
@bprodoehl: I pushed one more commit into the branch, could you try again?

Also, we're just filling the ClientHelloInfo.ServerName for now, as it's the [only thing caddy currently needs](https://github.com/mholt/caddy/blob/73794f2a2c54e201384290b38beeacbd7e1a15da/caddytls/handshake.go#L69). I made a new issue for that (linked) with us. @mholt: please let us know if you plan to change that part of your code soon :)

**Comment by bprodoehl** [comment] 2017-03-01 20:27
@lucas-clemente that did the trick!  Looks like its working now.

When I was digging through commits, I noticed that quic-go was reworked to take a net.PacketConn instead of net.UDPConn, but caddy still gives it a net.UDPConn, far as I can tell.  Is that worthy of an issue?

**Comment by mholt** [comment] 2017-03-01 20:31
@lucas-clemente Ah! Yes, sorry, we did add support for GetConfigForClient since that allows each site to have its own TLS config, which is _awesome_ 🕺 

Anyway, I will let you know if we end up using more from the ClientHelloInfo than just the server name. I think it is unlikely in the foreseeable future!

**Comment by lucas-clemente** [comment] 2017-03-01 20:33
Cool! :) Will merge the PR tomorrow.

Yes, we spent some time reworking our quic API, and it now takes a net.PacketConn (which is an interface that net.UDPConn implements). The http-over-quic API (from the `h2quic` package) did not change so far, so Caddy is not affected. We will definitely send a PR if we decide to update that API in the future, but it's certainly not as pressing as the other changes were.

**Comment by mholt** [comment] 2017-03-01 20:33
@bprodoehl net.UDPConn implements the net.PacketConn interface. Returning a concrete type is usually better as it can still be used as interfaces that it implements. I think it should be fine.

**Comment by lucas-clemente** [comment] 2017-03-02 11:41
The PR is merged, so I think this issue can be closed :)

**Closed** 2017-03-02 12:34 UTC

**Comment by ssut** [comment] 2017-03-03 13:39
Used the latest commit of go-quic and caddy.

It seems this patch makes the caddy server to do not work properly with fastcgi when I try to post any data. Non-quic requests(h2) are okay, it will just affect requests over QUIC. This problem is not only with the screenshot below but also with other php executions as I tested. Anyway, I'm not sure this bug is related to the issue named "Fill ClientHelloInfo in GetConfigForClient properly".

![caddy02](https://cloud.githubusercontent.com/assets/2366668/23552608/22c158fc-0060-11e7-982a-93dace4e9ed0.png)
![caddy00](https://cloud.githubusercontent.com/assets/2366668/23552604/1ec41d34-0060-11e7-996b-8c3d1aafba24.png)
![caddy01](https://cloud.githubusercontent.com/assets/2366668/23552606/205db218-0060-11e7-970f-6dc8d693336c.PNG)

**Comment by mholt** [comment] 2017-03-04 21:54
@ssut Please open a new issue because I think this is a different problem. Make sure to answer all the questions so it can be easily reproduced.
