### ISSUE TITLE
Panic when proxying with QUIC: not a Flusher

### ISSUE THREAD

**Issue by kseistrup** [mholt/caddy#1083] opened 2016-08-31 08:57 UTC
### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.9.1 (+e8e5595 Thu Aug 18 14:21:02 UTC 2016)
### 2. What are you trying to do?

Run Caddy as proxy in front of a ZeroNet instance that runs on http://127.0.0.1:43110/
### 3. What is your entire Caddyfile?

``` text
zero.example.net {
  header / Strict-Transport-Security "max-age=31556926"
  tls {
    key_type p384
  }
  proxy /          http://127.0.0.1:43110 {
    transparent
  }
  proxy /Websocket http://127.0.0.1:43110 {
    websocket
  }
  basicauth myUsername myPassword {
    /
  }
}
```
### 4. How did you run Caddy (give the full command and describe the execution environment)?

Via a systemd service file:

``` ini
[Unit]
Description=Caddy HTTP/2 web server
Documentation=https://caddyserver.com/docs
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service

[Service]
Restart=on-failure

; User and group the process will run as.
User=www-data
Group=www-data

; Letsencrypt-issued certificates will be written to this directory.
Environment=HOME=/etc/ssl/caddy

; Always set "-root" to something safe in case it gets forgotten in the Caddyfile.
ExecStart=/usr/local/bin/caddy -log stdout -email=undisclosed@example.com -agree=true -quic -conf=/etc/caddy/caddy.conf -root=/srv/http/empty
ExecReload=/bin/kill -USR1 $MAINPID

; Limit the number of file descriptors; see `man systemd.exec` for more limit settings.
LimitNOFILE=1048576
; Unmodified caddy is not expected to use more than that.
LimitNPROC=64

; Use private /tmp and /var/tmp, which are discarded after caddy stops.
PrivateTmp=true
; Use a minimal /dev
PrivateDevices=true
; Hide /home, /root, and /run/user. Nobody will steal your SSH-keys.
ProtectHome=true
; Make /usr, /boot, /etc and possibly some more folders read-only.
ProtectSystem=full
; … except /etc/ssl/caddy, because we want Letsencrypt-certificates there.
;   This merely retains r/w access rights, it does not add any new. Must still be writable on the host!
ReadWriteDirectories=/etc/ssl/caddy

; Drop all other capabilities. Important if you run caddy as privileged user (which you should not).
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
; … but permit caddy to open ports reserved for system services.
;   This could be redundant here, but is needed in case caddy runs as nobody:nogroup.
AmbientCapabilities=CAP_NET_BIND_SERVICE
; … and prevent gaining any new privileges.
NoNewPrivileges=true

; Caveat: Some plugins need additional capabilities. Add them to both above lines.
; - plugin "upload" needs: CAP_LEASE

[Install]
WantedBy=multi-user.target
```
### 5. What did you expect to see?

No errors
### 6. What did you see instead (give full error messages and/or log)?

From syslog:

``` txt
Aug 31 10:15:06 danlu caddy[20251]: panic: not a Flusher
Aug 31 10:15:06 danlu caddy[20251]: goroutine 106 [running]:
Aug 31 10:15:06 danlu caddy[20251]: panic(0xcac000, 0xc420495e30)
Aug 31 10:15:06 danlu caddy[20251]:     /usr/local/go/src/runtime/panic.go:500 +0x1a1
Aug 31 10:15:06 danlu caddy[20251]: github.com/mholt/caddy/caddyhttp/httpserver.(*ResponseRecorder).Flush(0xc4205e54f0)
Aug 31 10:15:06 danlu caddy[20251]:     /tmp/custombuild_6580_159870072/src/github.com/mholt/caddy/caddyhttp/httpserver/recorder.go:87 +0xda
Aug 31 10:15:06 danlu caddy[20251]: github.com/mholt/caddy/caddyhttp/proxy.(*maxLatencyWriter).flushLoop(0xc420612540)
Aug 31 10:15:06 danlu caddy[20251]:     /tmp/custombuild_6580_159870072/src/github.com/mholt/caddy/caddyhttp/proxy/reverseproxy.go:378 +0x156
Aug 31 10:15:06 danlu caddy[20251]: created by github.com/mholt/caddy/caddyhttp/proxy.(*ReverseProxy).copyResponse
Aug 31 10:15:06 danlu caddy[20251]:     /tmp/custombuild_6580_159870072/src/github.com/mholt/caddy/caddyhttp/proxy/reverseproxy.go:247 +0x2e1
Aug 31 10:15:06 danlu systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 31 10:15:06 danlu systemd[1]: caddy.service: Unit entered failed state.
Aug 31 10:15:06 danlu systemd[1]: caddy.service: Failed with result 'exit-code'.
Aug 31 10:15:07 danlu systemd[1]: caddy.service: Service hold-off time over, scheduling restart.
Aug 31 10:15:07 danlu systemd[1]: Stopped Caddy HTTP/2 web server.
Aug 31 10:15:07 danlu systemd[1]: Started Caddy HTTP/2 web server.
Aug 31 10:15:09 danlu caddy[20344]: Activating privacy features... done.
```
### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
1. install [Zeronet](https://zeronet.io/) (runs out of the box on Python2 when requirements (gevent and msgpack-python modules) are installed.
2. use above mentioned caddyfile
3. access Zeronet via HTTPS and click around on a few sites

**Comment by mholt** [comment] 2016-08-31 13:37
I suspect this is an experimental QUIC issue. If you disable QUIC does this error still occur?

**Comment by kseistrup** [comment] 2016-08-31 13:54
I will disable it and let you know.

However, I haven't seen this issue on a plain site (i.e., non-proxy, non-websocket) yet.

I'll be back.

**Comment by kseistrup** [comment] 2016-08-31 14:37
Disabling QUIC seemed to help. I should probably change the issue title.

**Comment by tw4452852** [comment] 2016-09-28 07:57
@mholt , Maybe we could just skip if it doesn't implement `http.Flusher` instead of firing a panic.

**Comment by mholt** [comment] 2016-10-14 05:20
@tw4452852 Isn't flushing kind of important? Will skipping it result in unwanted consequences?

At this point I'd rather we fix the QUIC-based ResponseWriter instead by adding a Flush method.

**Comment by mholt** [comment] 2016-10-14 13:58
I _believe_ this should be fixed upstream in the quic-go library now, I'll have a chance to test it later unless somebody wants to verify before then that it's working and close this.

**Comment by serussell** [comment] 2016-10-21 14:32
I'm seeing this on Caddy 0.9.3, whereas it wasn't happening on 0.9.0.  I do not enable QUIC (have never); the only change is upgrading from 0.9.0 to 0.9.3.

```
14:23:49  caddy | panic: not a Flusher
14:23:49  caddy | goroutine 500 [running
14:23:49  caddy | ]:
14:23:49  caddy | panic(0x9d7620, 0xc4201f50b0)
14:23:49  caddy |       /usr/local/go/src/runtime/panic.go:500 +0x1a1
14:23:49  caddy | github.com/mholt/caddy/caddyhttp/httpserver.(*ResponseRecorder).Flush(0xc420405a90)
14:23:49  caddy |       /tmp/custombuild_3235_340432801/src/github.com/mholt/caddy/caddyhttp/httpserver/recorder.go:87 +0xda
14:23:49  caddy | github.com/mholt/caddy/caddyhttp/proxy.(*maxLatencyWriter).flushLoop(0xc420367da0)
14:23:49  caddy |       /tmp/custombuild_3235_340432801/src/github.com/mholt/caddy/caddyhttp/proxy/reverseproxy.go:400 +0x156
14:23:49  caddy | created by github.com/mholt/caddy/caddyhttp/proxy.(*ReverseProxy).copyResponse
14:23:49  caddy |       /tmp/custombuild_3235_340432801/src/github.com/mholt/caddy/caddyhttp/proxy/reverseproxy.go:247 +0x2e1
14:23:49  caddy | time="2016-10-21T14:23:49Z" level=error msg="unexpected exit from subprocess (2)"
```

caddy -version:
`Caddy 0.9.3`

caddy was fetched with this:
`https://caddyserver.com/download/build?os=linux&arch=amd64&features=ipfilter%2Cjwt%2Cprometheus`

(which is shorter than posting the output of caddy -plugins)

**Comment by mholt** [comment] 2016-10-21 14:39
@serussell Do you have the ability to build from source? I think it was fixed it upstream recently and I haven't seen the problem since. Can you confirm? When somebody confirms I will close this issue.

**Comment by serussell** [comment] 2016-10-21 14:44
P.S.  I'm happy to bisect to find the breakage; is there a way to download specific builds of Caddy, or do I need to learn how to compile caddy with plugins?

**Comment by mholt** [comment] 2016-10-21 14:59
@serussell Just for the purposes of bisecting this, you won't need plugins (QUIC comes standard). So just a `go get github.com/mholt/caddy/caddy`, then subsequent builds with `go build` should do the trick. (Process for building with plugins is the same but you just add the plugin's import to run.go.)

**Comment by elcore** [comment] 2016-10-21 15:15
I am allowed to close this issue? It's working --(build from source, latest packages)

**Comment by serussell** [comment] 2016-10-22 12:02
QUIC isn't enabled by default, is it? Because my crashes are happening even though I've never turned it on 

Reverting to 0.9.0 absolutely resolves the issue as well. I haven't had a chance to test with tip.

**Comment by elcore** [comment] 2016-10-22 12:22
> QUIC isn't enabled by default, is it? Because my crashes are happening even though I've never turned it on

No, you need to enable it

**Comment by mholt** [comment] 2016-10-22 14:21
@serussell Ohhh, hey if you take out the `header` directive, does the error still occur? That might be one more thing we need to consider...

**Comment by serussell** [comment] 2016-10-24 00:17
@mholt I'll try, thanks.  Since it shouldn't be related to QUIC, should I open a separate ticket?  Anything else I can do to help debug?

**Comment by mholt** [comment] 2016-10-24 05:00
@serussell Sure, once you confirm that taking out the `header` directive fixes the problem, open a new issue so we don't forget about it. I think this issue with regards to QUIC support is fixed -- so we can close this once you've confirmed my hypothesis.

**Comment by mholt** [comment] 2016-11-09 22:33
@serussell Any progress on this? I can't remember :smile:

**Comment by ulrichSchreiner** [comment] 2016-11-10 16:01
hi,
i have the same error every few days on my server. anything i can do? my version is 0.9.3

**Comment by mholt** [comment] 2016-11-11 05:26
@ulrichSchreiner Sounds like something different -- could you please open a new issue, and answer all the questions in detail so that people who look at the issue can reproduce the same behavior? Try to minimize your configuration as much as possible to eliminate any extra, unnecessary complexity. Thanks

**Comment by ulrichSchreiner** [comment] 2016-11-11 06:40
ok, new ticket #1252 created.

**Comment by mholt** [comment] 2016-11-19 16:06
Closing unless this can be confirmed to still be a problem on master.

**Closed by mholt** 2016-11-19 16:06 UTC
Labels: bug

**Comment by serussell** [comment] 2016-12-09 18:45
@mholt -- sorry for the huge gaps between comments.  Is there a change set you can reference that you believe fixes the issue?  I assume the header directive is still valid, and the fix isn't removing header from the config.

This is challenging to reproduce, and I haven't had time to test with master.  I also assume you do not recommend running master (or any other non-release version) in production -- right?

**Comment by mholt** [comment] 2016-12-10 05:42
@serussell It might be the upstream quic library that was updated to fix this, as well: https://github.com/lucas-clemente/quic-go/commit/ef977ee0591f72543f8323cd12a585f5406ff971

I don't "recommend" running master in production, but it's usually okay (because we have automated tests) as long as you know what changes have been made and act accordingly, but that's true for any released version too.

Anyway, I suspect that between that change and this one, it's been fixed -- I haven't seen the issue myself since them either.
