### ISSUE TITLE
Caddy Build Faluire

### ISSUE THREAD

**Issue by herohamp** [mholt/caddy#2606] opened 2019-05-11 09:24 UTC
I tried building caddy on the website using this link `https://caddyserver.com/download/linux/amd64?plugins=hook.service,http.cache,http.cors,http.expires,http.filebrowser,http.filter,http.geoip,http.git,http.locale,http.login,http.minify,http.nobots,http.proxyprotocol,http.ratelimit,http.realip,http.reauth,http.upload,tls.dns.cloudflare&license=personal&telemetry=off` and got `provisioning build environment: go get: exit status 1`

```
root@server:~# curl https://getcaddy.com | bash -s personal hook.service,http.cors,http.filebrowser,http.filter,http.git,http.ipfilter,http.jwt,http.login,http.minify,http.prometheus,http.realip,http.reauth,http.upload,tls.dns.cloudflare
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7380  100  7380    0     0   5475      0  0:00:01  0:00:01 --:--:--  5474
Downloading Caddy for linux/amd64 (personal license)...
curl: (22) The requested URL returned error: 500 Internal Server Error
Aborted, error 22 in command: curl -fsSL "$caddy_url" -u "$CADDY_ACCOUNT_ID:$CADDY_API_KEY" -o "$dl"
```

Then I did the same thing with curl and got an error

**Comment by Mohammed90** [comment] 2019-05-11 09:49
Duplicate of #2583

**Closed** 2019-05-11 18:22 UTC
Labels: duplicate
