### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by vladbondarenko** [mholt/caddy#1519] opened 2017-03-15 17:19 UTC
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.5

### 2. What are you trying to do?
run caddy as proxy server for varnish->nginx backend

### 3. What is your entire Caddyfile?
```text
(Put Caddyfile here)
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
/usr/bin/caddy -quic -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/www

### 6. What did you see instead (give full error messages and/or log)?

very often i got 

panic: interface conversion: io.ReadCloser is struct { io.Reader; io.Closer }, not *h2quic.requestBody
goroutine 62 [running]:
panic(0x9ca1c0, 0xc4203c2c40)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest.func1(0xc420190e40, 0xc4203c44b0, 0xc420327e00, 0x0, 0xd1e3a0, 0xc420157520)
        /home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:193 +0x17c
created by github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest
        /home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:202 +0x628

**Comment by mholt** [comment] 2017-03-15 17:53
Hi @vladbondarenko , thanks for your report, although it's basically impossible to inspect because you didn't put your Caddyfile in the issue. I think this might already be fixed though, you didn't specify which system you're running on either so I can't be sure. Probably a duplicate of #1393 and #1496 and #1413.

**Closed by mholt** 2017-03-15 17:53 UTC
