### ISSUE TITLE
Caddy 0.11.5 500 Internal Server Error

### ISSUE THREAD

**Issue by simplemice** [mholt/caddy#2534] opened 2019-03-21 10:30 UTC
## 1. Which version of Caddy are you using (`caddy -version`)?

Caddy 0.11.5

## 2. What are you trying to do?

after update to 0.11.5 1 site still working, 2 site get error

## 3. What is your Caddyfile?
```
 site.com {
     root /var/www/html/site
     tls {
         dns cloudflare
     }
      log /var/log/caddy/site.log
      errors /var/log/caddy/site_errors.log
      gzip
      # PHP-FPM Configuration for Caddy
      fastcgi / /run/php/php7.2-fpm.sock php {
          ext .php
          split .php
          index index.php
     }
      rewrite {
          if {path} not_match ^\/wp-admin
          to {path} {path}/ /index.php?_url={uri}
     }
 }
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

install from "One-step installer script"

## 5. Please paste any relevant HTTP request(s) here.

```
curl -Iv https://site.com/
*   Trying xxx.xxx.xxx.200...
* TCP_NODELAY set
* Connected to rsite.com (xxx.xxx.xxx.200) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=site.com
*  start date: Mar 20 08:35:46 2019 GMT
*  expire date: Jun 18 08:35:46 2019 GMT
*  subjectAltName: host "site.com" matched cert's "site.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55e01b030840)
> HEAD / HTTP/2
> Host: site.com
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 500 
HTTP/2 500 
< content-type: text/html; charset=UTF-8
content-type: text/html; charset=UTF-8
< server: Caddy
server: Caddy
< status: 500 Internal Server Error
status: 500 Internal Server Error
< date: Wed, 20 Mar 2019 09:53:15 GMT
date: Wed, 20 Mar 2019 09:53:15 GMT

```
## 6. What did you expect to see?

worked site

## 7. What did you see instead (give full error messages and/or log)?

```
2001:xxx:xxxx:xxx:440b:a8ff:fe49:2d01 - - [20/Mar/2019:21:22:16 +0300] "GET / HTTP/2.0" 500 23
xxx.xxx.xxx.108 - - [21/Mar/2019:01:29:52 +0300] "GET / HTTP/1.1" 500 23
```

## Bonus: What do you use Caddy for? Why did you choose Caddy?

test dev

**Comment by mholt** [comment] 2019-03-21 15:55
What is in your error logs?

**Comment by simplemice** [comment] 2019-03-21 16:00
> What is in your error logs?

no errors in logs... i receive only that i wrote in clause 7 

and in browser i see

site.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by francislavoie** [comment] 2019-03-21 16:58
Regarding the `client offered only unsupported versions` error, this is because the ciphers for older clients have been removed in 0.11.5 ([see here](https://github.com/mholt/caddy/releases/tag/v0.11.5))

**Comment by mholt** [comment] 2019-03-21 17:04
@francislavoie Are we sure of that? `[301 300]` is TLS 1.0 and SSL 3.0 which are not enabled in Caddy. Protocol version != cipher suites, and this client didn't even use a protocol version that was supported (and TLS 1.2 is the default minimum for like a year already).

Hmm, well the error is definitely obscure then. Do you have a way for us to reproduce it? Unfortunately you changed the name of the site, even though the bug report instructions ask you not to (unless you actually own site.com), so we are not able to get more information. ☹️

**Comment by simplemice** [comment] 2019-03-21 17:10
> @simplemice
> 
> Hmm, well the error is definitely obscure then. Do you have a way for us to reproduce it? Unfortunately you changed the name of the site, even though the bug report instructions ask you not to (unless you actually own site.com), so we are not able to get more information. 
> 
> Edit: What happens when you remove the fastcgi directive?

sorry for remove name of site....

after remove fastcgi i get in browser 404 Not Found
and in logs (caddy.log)
```
2019/03/21 20:06:56 [INFO][FileStorage:/etc/caddy] Started certificate maintenance routine
2019/03/21 20:07:16 http: TLS handshake error from [2001:470:1f15:6d6:440b:a8ff:fe49:2d01]:55790: EOF
```
and site.log
`xxxx:xxx:xxxx:xxx:440b:a8ff:fe49:2d01 - - [21/Mar/2019:20:07:06 +0300] "GET /favicon.ico HTTP/2.0" 200 1406`

thats all :(

**Comment by francislavoie** [comment] 2019-03-21 17:11
@mholt You're right, my bad. I was going off our earlier discussion from memory but misrememebered. Thanks for clarifying that.

**Comment by mholt** [comment] 2019-03-21 17:13
That's a good sign. I don't think this is a bug in Caddy then -- the backend that fastcgi is connecting to is returning a 500 error, or something about that connection is failing. So I would look into your fastcgi process/configuration and make sure that everything is correct. It _might_ be a bug _if_ Caddy is eating the error details, but I'm not sure if that's the case yet.

> http: TLS handshake error from [xxxx:xxx:xxxx:xxx:440b:a8ff:fe49:2d01]:55790: EOF

That just means the client closed the connection. Most TLS errors are benign.

**Comment by simplemice** [comment] 2019-03-21 17:36
> That's a good sign. I don't think this is a bug in Caddy then -- the backend that fastcgi is connecting to is returning a 500 error, or something about that connection is failing. So I would look into your fastcgi process/configuration and make sure that everything is correct. It _might_ be a bug _if_ Caddy is eating the error details, but I'm not sure if that's the case yet.
> 
> > http: TLS handshake error from [xxxx:xxx:xxxx:xxx:440b:a8ff:fe49:2d01]:55790: EOF
> 
> That just means the client closed the connection. Most TLS errors are benign.

my mistake, i'm not attentive, you pointed out the correct mistake
after change versions of fastcgi i get this
21/Mar/2019:20:30:16 +0300 [ERROR 502 /] dial unix /run/php/php7.2-fpm.sock: connect: no such file or directory
21/Mar/2019:20:28:24 +0300 [ERROR 502 /] dial unix /var/run/php/php7.0-fpm.sock: connect: no such file or directory

but! with this simulation config second site works good.... it's magic :(
i think... i'l take mistake in fastcgi 
tnx

**Comment by mholt** [comment] 2019-03-22 04:17
Sounds like you've figured it out then? If so, great! Feel free to close the issue. :)

**Comment by simplemice** [comment] 2019-03-22 06:56
> Sounds like you've figured it out then? If so, great! Feel free to close the issue. :)

no, but i fixed for me - i moved all to docker ;)

**Closed** 2019-03-22 17:00 UTC
