### ISSUE TITLE
need only bind udp, work with nginx

### ISSUE THREAD

**Issue by longbai** [mholt/caddy#1671] opened 2017-05-15 16:49 UTC
(Are you asking for help with using Caddy? Please use our forum instead: https://caddy.community. If you are filing a bug report, please take a few minutes to carefully answer the following questions. If your issue is not a bug report, you do not need to use this template. Thanks!)

### 1. What version of Caddy are you using (`caddy -version`)?

0.10.2
### 2. What are you trying to do?

I need only bind udp quic port, and nginx bind tcp port
### 3. What is your entire Caddyfile?
```text
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy
### 5. Please paste any relevant HTTP request(s) here.

(paste curl command, or full HTTP request including headers and body, here)

--
### 6. What did you expect to see?

nginx and caddy work together
### 7. What did you see instead (give full error messages and/or log)?

...
### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

yes

**Comment by francislavoie** [comment] 2017-05-15 17:14
Duplicate of https://github.com/mholt/caddy/issues/1614

**Closed by francislavoie** 2017-05-15 17:14 UTC
Labels: duplicate

**Comment by mholt** [comment] 2017-05-16 01:00
Hey @longbai -- thanks for the request, but why is this needed? Your request is a bit bare-bones, and doesn't explain anything. Why not just use Caddy?

**Comment by SunRunAway** [comment] 2017-05-16 03:16
hi, @mholt .
We have hundreds of servers running in production and nginx on those listening on 80 tcp port are shared by many department in out company. We cannot simply change this situation but want to test caddy with quic on udp 80 port.

**Comment by mholt** [comment] 2017-05-16 03:35
@SunRunAway Why the insistence of running on the same machines, though? If you already have hundreds of servers running nginx, wouldn't it be a better idea to run a new experiment on a separate machine that's _not_ super important?

**Comment by SunRunAway** [comment] 2017-05-16 04:59
@mholt 
After the test, we would like to run nginx listening on tcp 80 and caddy on udp 80 on every hundreds of servers in production. If this happened, we can both support tcp and quic protocal for our clients. Clients would have the ability to connect using tcp or quic via every ip address to our servers.

**Comment by mholt** [comment] 2017-05-16 06:14
@SunRunAway Fair enough. I'll reopen the first issue then.
