### ISSUE TITLE
Scheme and transparent proxy don't use X-Forwarded-Proto

### ISSUE THREAD

**Issue by dimitrovskif** [mholt/caddy#2382] opened 2018-12-07 15:59 UTC
### What version of Caddy are you using (`caddy -version`)?

0.11.1

###  What is your entire Caddyfile?
```
# cat Caddyfile
somedomain:80 {
   log / stdout "Scheme: {scheme}"
}
# caddy
Scheme: http
Scheme: http
Scheme: http
Scheme: http
```

When performing a request to `https://somedomain` (which is an external TLS proxy to `somedomain:80` with `X-Forwarded-Proto` set to `https`).

You should clarify what the `{scheme}` placeholder does. At the moment it reads the caddyfile scheme, maybe there should be a `{request_scheme}` that takes into account `X-Forwarded-Proto`?

---

P.S. this issue affects `http.proxy` with the `transparent` option, since it uses the `{scheme}` placeholder for upstream headers. Getting an `https` request and proxying it as `http` *is not* transparent.

**Comment by dimitrovskif** [comment] 2018-12-07 17:55
The simplest way to reproduce this:
```
# cat Caddyfile
somedomain:80 {
   log / stdout "{scheme}"
}
# caddy
http
http
http
http
```
While running `curl https://somedomain` with a Cloudflare server sending `X-Forwarded-Proto: https`.

**Comment by dimitrovskif** [comment] 2018-12-08 11:32
@francislavoie I know how to fix it, but the default behaviour is problematic.

**Comment by francislavoie** [comment] 2018-12-08 15:47
As-is, I disagree. It seems to be working as intended. Since you're listening on port 80 with no TLS, then that means the scheme is `http`. It would be lying if Caddy passed along `https` to the backend.

Maybe I don't understand what you're trying to do?

**Comment by tobya** [comment] 2019-02-03 22:18
I'm going to close this but feel free to continue the discussion

**Closed by tobya** 2019-02-03 22:18 UTC
