### ISSUE TITLE
Proxy and Follow Redirects

### ISSUE THREAD

**Issue by ckeeney** [mholt/caddy#1620] opened 2017-04-25 17:44 UTC
I'm trying to proxy traffic to Wordpress.  Wordpress lives on `foo.bar.com`, and caddy is listening on `fizz.buzz.com`.  A request comes in for `fizz.buzz.com/feed`.  I can just proxy this to wordpress with 
`proxy /feed fizz.buzz.com`, but wordpress will serve a redirect to add a trailing slash, `/feed/`.  Caddy does not follow this redirect, but instead serves the 301 to the client.

The end result is that now the client is on `fizz.buzz.com/feed`, but I wanted to serve that content from `foo.bar.com/feed`.

**Comment by mholt** [comment] 2017-04-25 18:40
This is easy, change your proxy so that it proxies `/feed/` instead of `/feed`, and then only `/feed/` requests will be proxied. You can also change the Host header that you're sending upstream depending on how the backend app is requested.

Thanks for your issue -- I do not think this is a bug in Caddy though, so I will close this. If you have further questions about using Caddy's proxy with WordPress, try our forum https://caddy.community - where more people will be able to help you.

**Closed by mholt** 2017-04-25 18:40 UTC

**Comment by ckeeney** [comment] 2017-04-25 19:00
Hi Matt.  I actually do have that for my `proxy` directive.  Sorry for not including my Caddyfile in the original report.  I was just lazy.

In my Caddyfile, I have to do a lot of silly rewriting just to try to catch all the rewrites WordPress might serve.  For example:

- WordPress redirects `/feed` to `/feed/`
- WordPress redirects `/feed/?paged=1` to `/feed/`
- WordPress redirects if the host of the request is not what it expects.

```
:80
root /srv/build/
log stdout
gzip

rewrite /feed /feed/?{query}

rewrite /feed {
    if {query} not ?paged=1
    to /feed/?{query}
}

rewrite /feed {
    if {query} is ?paged=1
    to /feed/
}

# send article rss feed request to wordpress
proxy /feed/ https://<redacted> {
  transparent
  header_upstream Host <redacted>
}

# send other requests to backend
proxy / localhost:81 {
    except /static favicon.ico favicon.png index.html asset-manifest.json
    transparent
}

startup node server &
```
And the corresponding curl request:
```
$ curl localhost:3000/feed?paged=2 -v
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /feed?paged=2 HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.50.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Access-Control-Allow-Origin: *
< Content-Type: application/rss+xml; charset=UTF-8
< Date: Tue, 25 Apr 2017 18:56:59 GMT
< Etag: "7d5c6c1e88c3c3dd43bd1964cb02e567"
< Last-Modified: Tue, 25 Apr 2017 13:32:46 GMT
< Location: https://<redacted>/feed/?paged=2
< Server: Caddy
< Vary: Accept-Encoding
< Content-Length: 0
< 
* Connection #0 to host localhost left intact

```

As you can see, I have 3 lines in my Caddyfile trying to catch redirects for different reasons and I'm failing.  If Caddy followed redirects this would all just work.  Maybe adding a `follow_redirect` option to the `proxy` directive is useful?

**Comment by francislavoie** [comment] 2017-04-25 20:53
Why not do `rewrite /feed/ /feed/?{query}` and do `redir /feed /feed/` at the Caddy level?

**Comment by ckeeney** [comment] 2017-04-25 21:18
Won't the `redir /feed /feed/` lose query params for a request to example `foo.com/feed?paged=2`?

**Comment by francislavoie** [comment] 2017-04-26 05:11
Looking here: https://github.com/mholt/caddy/issues/180 it seems like the intended behaviour is that it keeps the query. I can't test right now but it might be worth a shot

**Comment by mholt** [comment] 2017-04-26 06:30
Are the `<redacted>` values all the same hostname? If so, proxying to `https://redacted` and setting `header_upstream Host <redacted>` is redundant -- `transparent` does the opposite of `header_upstream Host <redacted>` -- so I'm not sure what exactly you're trying to do.
