### ISSUE TITLE
[0.9.2] fcgi: invalid header version

### ISSUE THREAD

**Issue by binarious** [mholt/caddy#1146] opened 2016-09-28 15:24 UTC
### 1. What version of Caddy are you running (`caddy -version`)?
0.9.2 (it works with 0.9.1)

### 2. What are you trying to do?
Accessing fpm through caddy.

### 3. What is your entire Caddyfile?
```text
http://localhost:8001
root /home/myuser/projects/smt/web
gzip

rewrite {
  to {path} {path}/ /app_dev.php?{query}
}

fastcgi / 127.0.0.1:9000 php {
  index app_dev.php
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
- PHP 7
- Linux Mint 17.3 Cinnamon 64-bit
- run `caddy`
- open url

### 5. What did you expect to see?
Running website without errors

### 6. What did you see instead (give full error messages and/or log)?
- in browser: 502 Bad Request
- in console: [ERROR 502 /] fcgi: invalid header version

**Comment by mholt** [comment] 2016-09-28 15:54
Hi, thanks for the report. This is fixed on master and is a duplicate of #1128 and #1138. Expect a new release soon!

**Closed by mholt** 2016-09-28 15:54 UTC
