### ISSUE TITLE
Allow to extract fields from client cert (to set header for example)

### ISSUE THREAD

**Issue by Alex131089** [mholt/caddy#1905] opened 2017-10-04 12:31 UTC
This might be the same situation as #1904, duplicate of #1375, but I couldn't find an explicit issue about this. https://caddy.community/t/tls-authentication-with-client-cert/1074/7 eventually mention it.

Could it be possible to extract client certificate fields ?
To set them in a header, pass them to the underlying server for example, allowing simple authentification (but filtering this header for upstream, using header_upstream I suppose).

**Comment by francislavoie** [comment] 2017-10-04 13:39
Out of curiosity, are other servers like nginx able to do this?

**Comment by Alex131089** [comment] 2017-10-04 15:22
Yes, see the linked forum thread : https://nginx.org/en/docs/http/ngx_http_ssl_module.html#variables
Or https://httpd.apache.org/docs/2.4/ssl/ssl_howto.html#accesscontrol

**Comment by virtualdxs** [comment] 2018-10-11 17:36
Has there been any progress on this? I had assumed at first that there was already a way to get the client's cert info, based on the 'verify_if_given' parameter (otherwise this parameter seems no better than not authenticating clients at all), but it seems this is not the case.

**Comment by virtualdxs** [comment] 2018-10-11 18:31
It looks like this has actually been fixed in master. Can somebody confirm that this is a duplicate of #2115?

**Comment by francislavoie** [comment] 2018-10-11 19:49
Yup, I think you're right @virtualdxs looks like a duplicate. Thanks for spotting that!

**Closed by francislavoie** 2018-10-11 19:49 UTC
Labels: feature request
