### ISSUE TITLE
Reverse proxys not working for Netdata and Glances

### ISSUE THREAD

**Issue by Dedsec1** [mholt/caddy#1634] opened 2017-04-29 23:34 UTC
(Are you asking for help with using Caddy? Please use our forum instead: https://caddy.community. If you are filing a bug report, please take a few minutes to carefully answer the following questions. If your issue is not a bug report, you do not need to use this template. Thanks!)

### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.0

### 2. What are you trying to do?
iam trying to setup reverse proxy's for netdata and glances but currently in the latest version both netdata and glances will not load their UI's. even with the current rules setup caddy does not properly allow the proxys to work.  

### 3. What is your entire Caddyfile?
```text
netdata.domain.com {
    proxy / localhost:19999
}

 rewrite {
        if {>Referer} has /glances
        to /glances/{path}
    }

        # The code below gives you a tiny level of security requiring a username/password before Caddy will let you connect to it

        basicauth /glances Username Password

        proxy /glances 127.0.0.1:61208 {                # https://github.com/nicolargo/glances
        without /glances
                transparent
        }


```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -log stdout -agree=true -catimeout 15m -conf=/etc/caddy/Caddyfile -root=/var/tmp

### 5. Please paste any relevant HTTP request(s) here.
<a href="https://netdata.chmuranet.io/">Moved Permanently</a>.

<a href="https://chmuranet.io/glances">Moved Permanently</a>.

(paste curl command, or full HTTP request including headers and body, here)

curl chmuranet.io/glances

curl netdata.chmuranet.io

### 6. What did you expect to see?
ether an 200 ok response or at least some html

### 7. What did you see instead (give full error messages and/or log)?
<a href="https://netdata.chmuranet.io/">Moved Permanently</a>.

<a href="https://chmuranet.io/glances">Moved Permanently</a>.

Netdata: for the web interface all i see is the splash screen when netdata loads up. 

Glances:  ether get 404 not found or no such file exists

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
1. install the latest version of caddy.
2. ether install glances or netdata
3. then try creating an reverse proxy rule for your domain for ether netdata or glances.
4. Done

**Comment by mholt** [comment] 2017-04-29 23:41
Hey, thanks for filling out the issue template. This is probably a duplicate of #1604 - if you think it is different, feel free to re-open this!

Fix should be going out next week sometime.

**Closed by mholt** 2017-04-29 23:41 UTC

**Comment by Dedsec1** [comment] 2017-04-29 23:57
its mostly the same issue but i was seeing if their was an current workaround, but oh well it can wait for now i guess.
