### ISSUE TITLE
502 Errors fairly frequently

### ISSUE THREAD

**Issue by Magic815** [mholt/caddy#1722] opened 2017-06-18 14:40 UTC
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.3

### 2. What are you trying to do?
I'm trying to use [Organizr](https://github.com/causefx/Organizr) with Caddy Server, but have been seeing a fairly frequent 502 error that requires a Caddy restart to fix.

### 3. What is your entire Caddyfile?
[Caddyfile](https://pastebin.com/mF8urqk6)
[Common.conf file](https://pastebin.com/vZ2f4E92)

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Caddy is installed as a Windows service (via NSSM).

### 7. What did you see instead (give full error messages and/or log)?
Some items I noticed in the error log that may or may not be related:
```
::1 - - [12/Jun/2017:22:32:49 -0400] "GET /ajax.php?a=emby-streams HTTP/2.0" 502 40
::1 - - [14/Jun/2017:23:21:25 -0400] "POST /deluge/json HTTP/1.1" 502 40
::1 - - [15/Jun/2017:02:35:14 -0400] "GET /ajax.php?a=nzbget-update&list=listgroups HTTP/2.0" 502 40
::1 - - [15/Jun/2017:02:37:15 -0400] "GET /ajax.php?a=nzbget-update&list=history HTTP/2.0" 502 40
::1 - - [15/Jun/2017:09:53:42 -0400] "GET / HTTP/2.0" 502 40
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Install Organizr into the www folder inside Caddy, and wait a day to see if the 502 errors show up.

**Comment by mholt** [comment] 2017-06-26 05:48
Linking to the [relevant forum thread](https://caddy.community/t/getting-fairly-frequent-502-bad-gateway-errors/2194?u=matt) for reference.

I do strongly suspect a bug in the FastCGI middleware, though it is difficult to pinpoint and I'm not sure if it would cause behavior you're describing. But it might. I dunno...

**Comment by tht** [comment] 2017-06-29 17:19
I do have the same issues on a few different backends. I assume it's independent of the backend.

My environment:

* Debian 8 running Docker Community Edition (17.03.1)
* Docker Container abiosoft/caddy:0.10.3-php as reverse proxy
* Docker Container owncloud:9.1.6 as backend
* Docker Container drupal:8.3.4 as backend

Caddyfile:

```
owncloud.xyz.org {
  tls me@myself

  proxy / http://owncloud:80 {
    fail_timeout 30s
    try_duration 1s
    keepalive 0
    transparent
    header_upstream X-Forwarded-Ssl on
  }
}
```

Most of these configuration parameters I've added since the first time I got the `502 BAD GATEWAY` error but nothing helps. Every now and then I see this error.

As proposed above, restarting Caddy does solve the issue. But I do not have to restart it. Press reload, wait a few seconds, repeat – and after some cycles (2-5) it works again.

I do have the exact same issues on owncloud and drupal, so I don't think it's a backend issue. Before I switched to Caddy I had an `nginx` container running with the same backends. This 502 error never occurred while I was using nginx.

My clients are using http/2 and Caddy is translating to http/1.1. Btw… I've seen the same behavior on all kind of clients from Apple Safari to Microsoft Edge or Google Chrome.

I'm not sure if this is the same issue but maybe it helps if I report my problem here too. For me it does not seem to be related to the backend. It *feels* like there are some stale connections to the backend. The backend closed the Connection but Caddy is still trying to use them.

**Comment by tobya** [comment] 2017-07-14 08:07
@tht Are you restarting the php fastcgi server on a regular basis? There is an env variable  PHP_FCGI_MAX_REQUESTS  which defaults to 500.  PHP fastcgi will terminate when it reaches this number of requests.  On linux systems this seem to then respawn, this doesnt happen on windows.  

You need some mechanism to restart fast-cgi server reguarily - this is not a caddy issue.

I'm not sure if this is the issue you are encountering, but it is worth looking at.

**Comment by tht** [comment] 2017-07-17 15:24
Thanks for your feedback @tobya. I don't think a fastcpi server is involved in my system. I forward http requests to OwnCloud 10 running in a docker container. 

My issue seems related to http/2 as I can't reproduce it using a browser behind a corporate proxy which only talks http/1.1. I often receive a 502 error when connecting using Safari, Chrome oder Edge. Pressing reload in the browser repeatedly shows 502 errors. If I wait for a few (>10 seconds) before pressing reload it will work again.

The errors don't show up all the time which makes it hard to debug. I hope #1375 will solve my issue too.

**Comment by mholt** [comment] 2017-07-17 16:21
@tht Can you open a separate issue? I think it's probably different if yours isn't a fastcgi problem. (And issue 1375 doesn't have anything to do with proxying, really.)

**Comment by tobya** [comment] 2017-07-17 16:57
@tht your common.conf includes the fast-cgi directive so I thought it might be one possible issue.  It may not be relevant

**Comment by tht** [comment] 2017-07-18 06:28
Thanks guys, I'll try to reproduce this issue and open a separate issue.

**Comment by mholt** [comment] 2017-07-24 22:18
If this _is_ a bug in fastcgi, then it might very well be fixed by the revert we merged recently (see linked issue above). Closing for now!

**Closed by mholt** 2017-07-24 22:18 UTC
