### ISSUE TITLE
Readme link to Caddy website repo is broken - where can I contribute to the docs?

### ISSUE THREAD

**Issue by ripdog** [mholt/caddy#2088] opened 2018-03-27 22:58 UTC
The title basically says it all. This repo's readme links to https://github.com/caddyserver/website, but that doesn't exist. I want to fill a gap in the docs which I recently fell into. How can I do so?

**Comment by francislavoie** [comment] 2018-03-27 23:09
Duplicate of https://github.com/mholt/caddy/issues/1940

**Closed by francislavoie** 2018-03-27 23:09 UTC

**Comment by francislavoie** [comment] 2018-03-27 23:16
I removed the reference in the README to that repo in #2089, thanks for pointing it out

**Comment by mholt** [comment] 2018-03-27 23:22
Thanks, I missed that one a while ago.

**Comment by ripdog** [comment] 2018-03-27 23:43
Ok, thanks for the context. Since you're here, I'll just write out the problem I had:

I was using caddy to proxy to a buggy backend service (subsonic) which only uses https links to its resources when it is accessed via https (it ignores the proxy headers). This meant I had to tell caddy to proxy to localhost:8443, but this is an https-only port so failed to connect entirely because caddy would try only http when connecting to the backend.

The solution is simply to add https:// to the backend specifier. The fact that this is possible is not mentioned at all in the docs for `proxy`. An example would be an excellent way to indicate this. Perhaps something like this:
```
proxy / https://127.0.0.1:8443 {
            transparent
            insecure_skip_verify
}
```
?

**Comment by mholt** [comment] 2018-03-28 00:44
I'll take a look at it. Thanks!

**Comment by ripdog** [comment] 2018-03-28 00:58
No, thank YOU! Caddy is fantastic.
