### ISSUE TITLE
bind, and: unknown port tcp/https

### ISSUE THREAD

**Issue by wmark** [mholt/caddy#136] opened 2015-06-12 19:15 UTC
Please excuse the preliminary title.

A configuration file like this:
```
# Caddyfile
https://site.local {
    bind 5.1.1.1
    tls /etc/ssl/slocal.crt /etc/ssl/private/slocal.key
}
```

… results in this error:
```2015/06/12 19:11:52 Could not serve 5.1.1.1:https - unknown port tcp/https```

I didn't expect any error.

**Comment by wmark** [comment] 2015-06-12 19:17
```
# Caddyfile
https://site.local {
    bind 5.1.1.1:443
    tls /etc/ssl/slocal.crt /etc/ssl/private/slocal.key
}
```

… will yield:
```2015/06/12 19:16:13 Could not serve [5.1.1.1:443]:https - unknown port tcp/https```

(Correct ISO notation would be 2015-06-12, by the way.)

**Comment by mholt** [comment] 2015-06-12 20:55
The bind directive takes a hostname only, so that explains the second error. I cannot reproduce the first, though. (I replaced 5.1.1.1 with 0.0.0.0 since I can't bind to 5.1.1.1.) What is 5.1.1.1 assigned to?

**Comment by wmark** [comment] 2015-06-12 21:57
Thank you for looking into this!

0.0.0.0 triggers a special case. Please use one »usual« IPv4 address that is available to your machine (e.g. 192.168.1.1) in order to reproduce the first error.

----

http://caddyserver.com/docs/bind says:

    bind <host>
    <host> is the hostname (or IP address) to bind to

The example on that page does use an IPv4 address (0.0.0.0) and not the wildcard-host (»*«).

And indeed, it works with a hostname which resolves to a single IP address. I didn't test it with one that has more backends.

**Comment by mholt** [comment] 2015-06-13 01:26
Unfortunately, I still do not have the same problem. Caddy runs with this Caddyfile:

https://site.local {
    bind 192.168.1.100
    tls cert.pem key.pem
}

(The wildcard host in Go is 0.0.0.0.)

**Comment by mholt** [comment] 2015-06-18 20:46
Is this still an issue? If not, we can close it.

**Comment by wmark** [comment] 2015-06-19 12:07
Reproducing it using v0.7.1:

```bash
/opt/caddyserver/caddy --version

ip addr add 10.10.10.10/32 dev lo
/opt/caddyserver/caddy
ip addr del 10.10.10.10/32 dev lo
```

… will result in this output:

    Caddy 0.7.1
    2015/06/19 12:05:33 Could not serve 10.10.10.10:https - unknown port tcp/https

… having used this file:

```
https://site.local {
        bind 10.10.10.10
        tls cert.pem key.pem
}
```

**Comment by mholt** [comment] 2015-06-19 16:42
On a linux box, I was still unable to reproduce the error. Caddy runs with that Caddyfile and output is:

```
10.10.10.10:https
```

Using same version.

**Comment by wmark** [comment] 2015-06-19 16:59
I really hope you still believe me, because I doubt myself now. In order to get to the cause I've written a test:

```bash
mkdir -p /tmp/caddtest
openssl req -newkey 2048 -keyout key.pem -nodes -x509 -out cert.pem -batch &
curl -fLRO -# https://github.com/mholt/caddy/releases/download/v0.7.1/caddy_linux_amd64.zip &
wait
unzip caddy_linux_amd64.zip

cat <<EOF >Caddyfile
https://site.local {
        bind 10.10.10.10
        tls /tmp/cert.pem /tmp/key.pem
}
EOF

ip addr add 10.10.10.10/32 dev lo
./caddy
ip addr del 10.10.10.10/32 dev lo
```

… and ran it:

 * CoreOS 709.0.0 — :-1: error
 * Gentoo — :+1: works

Both have Linux 4.0.5.

**Comment by wmark** [comment] 2015-06-19 17:28
That's the cause: *Golang* needs a file ```/etc/services```:
https://github.com/golang/go/blob/release-branch.go1.4/src/net/port_unix.go#L24

**Comment by wmark** [comment] 2015-06-19 17:34
https://github.com/mholt/caddy/blob/41e1f1ffa5c3c7a427357a0e7fd61d4f8b49e377/config/config.go#L101-L104
http://golang.org/pkg/net/#TCPAddr

In case of ```https``` the port is well-known, and directive ```bind``` already narrows down the IP address. That could be used for a workaround.

**Comment by mholt** [comment] 2015-06-19 17:41
Of course I still believe you. The OS info helps a lot - I was running Ubuntu, and unaware that it was (so far) only broken in CoreOS. Thanks for looking into it some more! I wouldn't have discovered that on my own.

That seems like a decent workaround for now. In the meantime, I wonder if a patch/issue should be submitted to CoreOS.

(I also wonder why https isn't in [this list](https://github.com/golang/go/blob/883bc6ed0ea815293fe6309d66f967ea60630e87/src/net/port_unix.go#L17) in the std lib.)

**Comment by wmark** [comment] 2015-06-19 18:04
I've checked some major distributions, and most of them have that file. ›Most‹ means: some don't have it. Our in-house distros don't have it.

I didn't find anything on the with regards to LSB other than the inclusion is controversial.
https://lists.linux-foundation.org/pipermail/lsb-discuss/2006-August/002841.html

As *caddy* will most probably not need more than ```http``` and ```https``` I guess we don't need to delve into that further.

**Comment by mholt** [comment] 2015-06-19 18:11
@wmark Does it only happen when you use the `bind` directive and with an IP address?

**Comment by wmark** [comment] 2015-06-19 18:19
```https://``` being the start of the key triggers that.

**Comment by mholt** [comment] 2015-06-25 04:31
@wmark When you have a chance, let me know if that PR fixes it for you.

**Comment by wmark** [comment] 2015-06-25 09:35
caddy/graceful-resolve@47d1f5eecf60eb10de8a942dbee10a51c474737d works

You rock, Matthew!

**Comment by mholt** [comment] 2015-06-25 14:19
Glad to hear it - thanks again for the report.

**Closed** 2015-06-25 14:18 UTC
Labels: in progress
