### ISSUE TITLE
doesn't handle Pending Authorizations rate limit super great

### ISSUE THREAD

**Issue by jmhodges** [mholt/caddy#523] opened 2016-01-20 23:05 UTC
We've had some folks forget they were running caddy, hit a rate limit, and then keep hitting that rate limit over and over again. One user was something around 30% of all rate limit violations until we emailed them and they found the process they'd forgot they were running.

Specifically, caddy doesn't handle the rate limit on the number of pending authorizations per registration key. The [Let's Encrypt rate limit docs](https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769) say a little more.

I think what's happening was that caddy has an internet connection out, but is not actually getting traffic for the domains in question. So, it was running and trying over and over again to get validated and failing.

Does that sound plausible?

**Comment by mholt** [comment] 2016-01-20 23:44
This is news to me. I think I need more information though. Challenges involve multiple requests to the server, so what I understand is that Caddy is making the first request but not subsequent requests?  Do you have any more information on this so I can pinpoint the cause?

You may reply here or [email me](https://matt.chat) -- either way is fine.

> So, it was running and trying over and over again to get validated and failing.

The only time Caddy tries to obtain a certificate is initially at startup, or upon renewals, which currently only happen once per day. Upon renewal failure, Caddy tries again 10 seconds, but then waits until the next day. So I doubt this is the cause of the problem.

I'd like to know more about the user who accounted for 30% of the violations... I want to know more about what programs he had listening on what ports, what the Caddyfile was, etc.

**Comment by jmhodges** [comment] 2016-01-20 23:50
Hmm, maybe I misread the email or they miswrote! I, unfortunately, don't have that data for you. 

If we run into this something like this again, I'll re-open this ticket and try to get the user in here. Thanks!

**Comment by mholt** [comment] 2016-01-20 23:57
Phooey, I do want to fix this. If what you're describing is an "infinite loop" of initiations, I would find that very surprising, but like I said, I don't want to rule out Caddy. There's a lot of configuration magic happening that has never been done before in networking software, so it's quite likely there's still a lurking problem. (Automatic HTTPS is hard.)

Let me know when you have more information or when I can be of assistance!

**Comment by mholt** [comment] 2016-01-21 04:12
For reference in case any other LE team members want to investigate...

Currently there is only one place `acme.ObtainCertificate()` is called: https://github.com/mholt/caddy/blob/4b6e0e936902ed23a5d22013f8e7fb168eac7b7a/caddy/letsencrypt/letsencrypt.go#L131 - and the parent function ObtainCerts is only called twice, once at restart and once at initial start: https://github.com/mholt/caddy/search?utf8=%E2%9C%93&q=ObtainCerts

In the first link, you'll see there is a label on the line above and there's a `goto Obtain` below. That goto is only reached if there's an error *and* it's a ToS error - which should only happen once because the client re-negotiates agreement before calling the goto. I suppose, theoretically, it is possible for that to be a constant loop if the error returned is always a ToS error.

As for renewing, [these are the only lines](https://github.com/mholt/caddy/blob/9453224639747b2a7a4908da6bff410c5f656517/caddy/letsencrypt/maintain.go#L150-L167) that initiate renewals.

**Comment by jmhodges** [comment] 2016-01-21 18:16
This user started back up again. I've directed them here to help figure it out.

**Comment by jmhodges** [comment] 2016-01-28 19:55
Okay, so this is showing up again. By the user agent, it's definitely a caddy server doing it.

The `goto Obtain` and `goto Renew` definitely look suspicious. Both are unbounded.

**Comment by jmhodges** [comment] 2016-01-28 19:55
(And it's caddy 0.8.1 server)

**Comment by mholt** [comment] 2016-01-28 21:37
Phooey. Okay, I can add restrict to the gotos to just happen once, but it should only happen once anyway unless the error it gets back from the ACME server is a terms agreement error *again* - which would probably be an error in the ACME server. Caddy process logs would show an error if terms agreement failed (in which case it does not try again).

Also, these currently only happen at startup or on restarts, so some Caddy user somewhere should be scratching their heads as to why the program is hanging/looping - unless they misconfigured their process manager and it just keeps restarting the process and nobody is checking systemd logs or something.

Is this being caused by that user you were in contact with? I'd probably need to talk with one to figure it out for sure.

**Comment by mholt** [comment] 2016-01-29 21:26
I just learned that if Caddy is run inside a Docker container and Caddy restarts either to reload config, renew a certificate, or update OCSP stapling, Docker might stop the container and delete any of the files that were created while it was running (including certificates).

I just need more information from an actual user having the rate limit problem -- I strongly suspect a system misconfiguration or some very obscure corner case in the Caddy code.

**Comment by jmhodges** [comment] 2016-01-29 23:03
So, given the code linked above, it could happen if the caddy server is run on a machine with a connecting out, but is not actually at the domain given to validate, yeah? That infinite `goto RenewCertificiate` could just keep firing, right?

**Comment by stephens2424** [comment] 2016-01-29 23:29
Just pinging this thread. I've got a few domains pointed at the server, mostly getting reverse proxied with nginx at the moment. I was experimenting transitioning one domain to caddy, to get better http2 support, and had paused until I was informed I was contributing to this problem. Because of that setup, I had configured the problematic domain to listen on a high port number, but didn't finish setting up forwarding for the domain. I'm not exactly sure where it went awry, but here was the configuration I had left running:

```
cs.stephensearles.com:2222 {
        proxy / localhost:3179 {
                websocket
        }
}
```

**Comment by mholt** [comment] 2016-01-30 06:13
> So, given the code linked above, it could happen if the caddy server is run on a machine with a connecting out, but is not actually at the domain given to validate, yeah? That infinite goto RenewCertificiate could just keep firing, right?

@jmhodges I don't think so, since the goto is only called if the error returned is specifically an error indicating that the user has not agreed to the updated ToS:

```go
if tosErr, ok := obtainErr.(acme.TOSError); ok {
						// Terms of Service agreement error; we can probably deal with this
						// ... lines removed for brevity
							goto Obtain
```

**Comment by rowdypixel** [comment] 2016-01-30 23:49
@mholt I'm the one that Jeff was referring to earlier. I will follow up with you on Monday evening EST when I have a chance to answer questions and dig into it more. For now I've just shut down the server in the mean time to prevent the issue.

**Comment by mholt** [comment] 2016-01-31 00:18
@rowdypixel Thanks! Specifically, I'd like to get a better idea of what kind of environment you're running Caddy in (network/firewall/LB/proxy/whatever, VM?, Docker?), how you're running it (process manager? and the actual command) and what your Caddyfile looks like (can strip out private info, but please leave entire file intact). Also if you run with `-log stderr` (or replace stderr with some filename) then it would be helpful to know the log output, since every certificate request is logged.

**Comment by rowdypixel** [comment] 2016-02-01 21:35
@mholt:

I'm running  caddy directly on Windows Server 2012R2 VM. I'm attempting to use it as a reverse proxy to get to a separate VM on my network from the public internet.

**Comment by jmhodges** [comment] 2016-02-01 21:44
(Both of these folks had the same issue. We had the second show up after I posted this ticket.)

**Comment by rowdypixel** [comment] 2016-02-01 21:55
@mholt:

I'm running  caddy directly on Windows Server 2012R2 VM. I'm attempting to use it as a reverse proxy to get to a separate VM on my network from the public internet.

@jmhodges  Currently, I don't even have caddy running on the server and the issue is still happening, so I'm confused as to what is going on.

**Comment by mholt** [comment] 2016-02-01 22:01
@rowdypixel 
> the issue is still happening

What issue is still happening, exactly -- just lots of failed authorizations in the LE access logs? What is happening on your server though? Also please take a look at my comment above and answer with all the information so I can know more about how you're running Caddy, etc.

**Comment by jmhodges** [comment] 2016-02-01 22:07
@rowdypixel talking to you over email where I can be more detailed.

@mholt the issue is the rate limiting discussed in this thread. An IP he controls is still trying to get a cert for a domain that he controls and failing to satisfy the validations and then running into this rate limit.

**Comment by jmhodges** [comment] 2016-02-01 22:10
@mholt Also, per stephens2424 post, the problem seems to be people misconfiguring at boot. It's probably the other goto referenced above. Caddy needs to stop retrying and throw an error up at some point.

**Comment by rowdypixel** [comment] 2016-02-01 22:11
@mholt As far as I can tell, nothing is happening on my server. Caddy doesn't even start on my server, and the process is not currently running. This is why I'm unsure how to shut down the requests.

Caddyfile:
`git.rowdypixeltools.com:80 {
	proxy / gitlab.localdomain
}`

It's unable to bind to port 80  on startup(presumably because I'm running IIS on there, and have been for quite some time). I have only ever tried to use Let's Encrypt with caddy.

**Comment by mholt** [comment] 2016-02-01 22:16
@jmhodges 

>  Also, per stephens2424 post, the problem seems to be people misconfiguring at boot. It's probably the other goto referenced above. Caddy needs to stop retrying and throw an error up at some point.

At boot of their server or at boot of Caddy? 

> It's probably the other goto referenced above.

You mean the one I inlined? That only happens if there's a ToS error -- is that what your logs are showing?

> Caddy needs to stop retrying and throw an error up at some point.

It only retries once at boot and once every day if a renewal is needed.

@rowdypixel 
> As far as I can tell, nothing is happening on my server. Caddy doesn't even start on my server, and the process is not currently running.

If that's true, then it seems obvious to me that Caddy is not making the requests from that machine.

> It's unable to bind to port 80 on startup(presumably because I'm running IIS on there, and have been for quite some time). I have only ever tried to use Let's Encrypt with caddy.

Yes, Caddy will need port 80 since that's the port you're trying to listen on. You can change the bind *host* using the [bind](https://caddyserver.com/docs/bind) directive.

**Comment by jmhodges** [comment] 2016-02-01 22:21
At the first boot of caddy.

Could it be that caddy is getting shutdown because of this error and then restarted immediately, causing the retries?

Or maybe if a port was unable to be bound to, this code would get called again?

**Comment by mholt** [comment] 2016-02-01 22:25
> Could it be that caddy is getting shutdown because of this error and then restarted immediately, causing the retries?

Yes, indeed. We've seen this before when process managers are misconfigured or Docker is used incorrectly. Process managers see the process exit and immediately try to restart Caddy. (But if the certificate stays on disk, it will re-use it.) Docker containers are even worse because, unless configured properly, they also delete files--including certificates--each time the process quits.

> Or maybe if a port was unable to be bound to, this code would get called again?

No, if the listener can't bind then it's a fatal failure -- no retries are performed in that case.

**Comment by jmhodges** [comment] 2016-02-01 22:30
Is there a chance caddy could write out some of that info, esp in the rate limit case? Folks keep spamming and not getting in.

**Comment by jmhodges** [comment] 2016-02-01 22:36
Hm, if it was only the restart, then how did @stephens2424 get hit by this?

**Comment by rowdypixel** [comment] 2016-02-01 22:47
@mholt I think I found the offending process on a different server. The logs lets us astray for awhile, but @jmhodges has confirmed that was the issue.

Here is the caddyfile that I have on that instance. @jmhodges @mholt  I will run it with logging enabled for a couple minutes and attach the results shortly.

**Comment by jmhodges** [comment] 2016-02-01 22:48
@rowdypixel For clarity, the machine it was running on wasn't receiving traffic (or, at least, not all of the traffic) for the domain in question, yeah?

**Comment by rowdypixel** [comment] 2016-02-01 22:49
@jmhodges Correct. I had reconfigured my NAT a couple weeks back so nobody can get to that machine from the domain.

**Comment by jmhodges** [comment] 2016-02-01 22:49
@rowdypixel Thanks!

**Comment by jmhodges** [comment] 2016-02-01 22:50
Btw, rowdypixel's caddy might be a bit older; it didn't include the version number in the User-Agent.

Stephens2424, however, did include the caddy 0.8.1 part of the User-Agent and, from his comments, doesn't seem to have been getting restarted.

**Comment by rowdypixel** [comment] 2016-02-01 22:53
@mholt In my instance, I don't believe this to be a caddy issue. Upon failure, caddy would exit and upstart would restart it infinitely trying its best to keep the server running. It takes about 5 seconds for the failure to occur, so my config of killing it permanently if it failed 5 times in 10 seconds did not apply for this particular failure. 

@jmhodges I am running caddy 0.8.

The log contains the following:
`2016/02/01 17:46:50 [INFO] acme: Obtaining bundled certificates for git.rowdypi$
2016/02/01 17:46:50 [INFO] acme: Trying to solve TLS-SNI-01`

**Comment by jmhodges** [comment] 2016-02-01 22:56
@rowdypixel Yeah, it'll take a bit to hit the rate limit now. Per the let's encrypt rate limit docs, you get 300 per account, per week and your restart of caddy gave you a new account. So, we wait for it to fail 300 times now.

**Comment by mholt** [comment] 2016-02-01 22:57
@stephens2424 I'll need some more info from you (see above) -- thanks.

@rowdypixel Glad you figured it out. Also you should upgrade to Caddy 0.8.1 :wink:

@jmhodges Thanks for being persistent -- one down, one to go...

**Comment by jmhodges** [comment] 2016-02-01 22:58
Not sure one's down! Both of them seem to have the same bug and aren't getting restarted, so it has to be somewhere else? Maybe in the acme client?

**Comment by mholt** [comment] 2016-02-01 22:59
Wait, I'm confused. @rowdypixel said his was being restarted infinitely by upstart -- that's not a Caddy issue.

**Comment by jmhodges** [comment] 2016-02-01 23:00
Oh, I totally missed that. Sorry!

**Comment by jmhodges** [comment] 2016-02-01 23:02
(I mean, also it would be nice for caddy to not spam LE whenever folks misconfigure their server and have it in a reboot loop, yeah?)

**Comment by mholt** [comment] 2016-02-01 23:08
> (I mean, also it would be nice for caddy to not spam LE whenever folks misconfigure their server and have it in a reboot loop, yeah?)

I guess, but I need more information. Still nobody has given me what I've asked for to start with.

**Comment by mholt** [comment] 2016-02-06 07:11
It seems that misconfigured environments/Docker/process managers are a common cause for hitting rate limits, here's another instance: https://community.letsencrypt.org/t/hitting-rate-limit/7996

Going to close this issue unless it's confirmed to be a problem with Caddy and I actually get the information I'm asking for so I can diagnose it.

**Closed by mholt** 2016-02-06 07:11 UTC
