### ISSUE TITLE
tls self_signed produces SSL error in browser with hosts other than localhost on windows

### ISSUE THREAD

**Issue by a1martin** [mholt/caddy#912] opened 2016-07-01 08:01 UTC
#### 1. What version of Caddy are you running (`caddy -version`)?
 Caddy 0.9-beta.2

#### 2. What are you trying to do?
I'm trying to host mydomain.com from local machine for development purposes on Win 10 machine. For that I changed the C:\Windows\System32\drivers\etc\hosts file to:
```text
127.0.0.1 mydomain.com
```
PS! seems to run on linux and mac. Also localhost:443 works ok as well.

#### 3. What is your entire Caddyfile?
```text
mydomain.com:443 {
	tls self_signed
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
just caddy command on dev folder. Caddyfile in same folder. caddy responds "https://mydomain.com"

#### 5. What did you expect to see?
I expected to see https://mydomain.com in my browser

#### 6. What did you see instead (give full error messages and/or log)?
ERR_SSL_PROTOCOL_ERROR(Chrome) or "SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG" (Firefox) 

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
On windows machine (Win 10 in this case)
a)Change hosts file as described in point 2. 
b)Create a folder with index.html containing a sample data
c)Create caddyfile as described in point 3.
d)run caddy
e)open https://mydomain.com in browser

**Comment by mholt** [comment] 2016-07-01 13:36
Hmm, I dusted off my Win7 VM and things work just fine there, let met try with Windows 10...

**Comment by mholt** [comment] 2016-07-02 15:08
I've got some bad news: On Windows 10 using these instructions I can't see the same problem. I bypass the certificate warning (as expected) and the page loads fine. Any other details you can provide to make the problem appear? Have you tried another machine maybe?

**Comment by tomasdeml** [comment] 2016-07-08 12:00
I'm having the same problem on Win 10 (Version 1511) for requests from both local machine and other machines. I tried Caddy 0.8 and 0.9-beta.2 and latest versions of FF and Chrome. It seems to be resolved by adding `bind 127.0.0.1` directive under the site entry, but this is undesirable. The issue does not appear under Windows Server 2012 R2.

Caddyfile:
```text
https:// {
    bind 127.0.0.1	
    gzip {
        ext "" .htm .html .css .js .csv .json
            level 1
    }
    header / {
        -Server
    }
}
```

hosts:
```text
127.0.0.1	xxx.local.net
127.0.0.1	yyy.xxx.local.net
```

Don't know if it is important but I the machine has virtual network adapters for Hyper-V and VirtualBox and is also joined to a domain.

**Comment by mholt** [comment] 2016-07-08 13:41
@tomasdeml Hmm, self_signed doesn't exist in Caddy 0.8 versions -- it would be treating that as your email address when obtaining a certificate from Let's Encrypt.

I still have not been able to replicate this... very odd.

**Comment by elcore** [comment] 2016-07-08 15:46
Hello @a1martin / @tomasdeml,

I am not able to replicate this!

WIN+R -> winver `Version 1511 (Build 105864.420)`

Caddyfile:

```
eldin.hadzic:443 {
	tls self_signed
}

eldin.com {
	tls self_signed
}
```

**Comment by tomasdeml** [comment] 2016-07-09 09:51
> Hmm, self_signed doesn't exist in Caddy 0.8 versions -- it would be treating that as your email address when obtaining a certificate from Let's Encrypt.

@mholt Yep, I used my own self signed cert with v0.8, should have made it clearer.

Anyway I did some research with Rawcap and Wireshark and it seems the issue may be caused by some interaction with IPv6.

When I test caddyfile with `bind 127.0.0.1` or `bind <my_intranet_ip>`, Wireshark showns complete handshake and the page loads fine on my Win 10 machine with IE 11. The screen below shows the Rawcap capture for IPv4:

![ok](https://cloud.githubusercontent.com/assets/5622086/16707337/1f1a10b4-45ca-11e6-90b9-45a8e1dec935.PNG)

When I test caddyfile _without_ `bind` on Win 2012 R2 machine (Azure VM), it completes as well. 

However when I test caddyfile _without_ `bind` on my Win 10 machine, the server does not respond to any `Client Hello` message with different TLS versions so the handshake does not complete. See the Rawcap capture for IPv4:

![notok1](https://cloud.githubusercontent.com/assets/5622086/16707352/5a29a28c-45ca-11e6-9c27-1d13736ba304.PNG)

![notok2](https://cloud.githubusercontent.com/assets/5622086/16707355/5f20629e-45ca-11e6-9fe6-35c66796c73c.PNG)

I may be wrong but it seems that Caddy does not respond to IPv4 requests on some Windows versions or network configurations. And that would be weird because `netstat` on all the machines shows that it is listening there:
```text
 λ netstat -bqn | grep -B1 caddy
  TCP    0.0.0.0:443            0.0.0.0:0              LISTENING
 [caddy.exe]
--
  TCP    [::]:443               [::]:0                 LISTENING
 [caddy.exe]
```

Could this behaviour be somehow similar to issue #864?

**Comment by mholt** [comment] 2016-07-09 14:20
Nice detective work! I'm stumped without doing further research, so I'll invite others to participate if they know anything about Windows networking.

It would be really great to narrow down "some Windows versions or network configurations" to something concrete so we can identify the cause and fix it. I think you've made a great start; I won't have a chance to look at it this weekend...

**Comment by tomasdeml** [comment] 2016-10-18 08:37
Another piece of the puzzle: the problem suddenly started appearing on tester's computer with Win 8 after installing the following Windows Updates:

![updates](https://cloud.githubusercontent.com/assets/5622086/19470164/a6e3affc-951e-11e6-8f4c-76b66efd552f.png)

So it may be dependent on Windows patch level as well :-/

**Comment by elcore** [comment] 2016-10-18 11:07
> Another piece of the puzzle: the problem suddenly started appearing on tester's computer with Win 8 after installing the following Windows Updates

What happens

**Comment by tomasdeml** [comment] 2016-10-19 06:34
@elcore Unfortunately it is tester's main workstation so we cannot risk wrecking her station by uninstalling the updates right now :(

**Comment by tomasdeml** [comment] 2016-10-20 10:19
Sigh, Windows Update was just a red herring. `curl -v` finally gave me the answer - it was the friggin' Skype all along! Skype binds to address `0.0.0.0` on ports 80/443 [by default](https://support.skype.com/en/faq/FA148/which-ports-need-to-be-open-to-use-skype-for-windows-desktop):

```text
λ netstat -bqn | grep -B1 Skype
  TCP    0.0.0.0:80             0.0.0.0:0              LISTENING
 [Skype.exe]
--
  TCP    0.0.0.0:443            0.0.0.0:0              LISTENING
 [Skype.exe]
```

Caddy does not report any errors on startup so I guess that's why nobody noticed.
```text
λ netstat -bqn | grep -B1 caddy
  TCP    0.0.0.0:80             0.0.0.0:0              LISTENING
 [caddy.exe]
--
  TCP    0.0.0.0:443            0.0.0.0:0              LISTENING
 [caddy.exe]
--
  TCP    [::]:80                [::]:0                 LISTENING
 [caddy.exe]
--
  TCP    [::]:443               [::]:0                 LISTENING
 [caddy.exe]
```

It seems that Skype's binding is created first so it takes precedence when matching sockets (? or maybe it is more specific). Then for every request to port 443, Skype returns plain text (!) response with `HTTP/1.0 404 Not Found`. This causes the SSL errors. When I configured caddy to bind to `127.0.0.1`, caddy took precedence and everything worked correctly.

I disabled this lovely "feature" of Skype's and in my case, all is well...

**Comment by mholt** [comment] 2016-10-20 11:21
WOW. That's amazingly awful, thanks for looking into that! I'll close the issue and if anyone else has the problem they can search for it here. Thanks again for your effort!

**Closed by mholt** 2016-10-20 11:21 UTC
Labels: help wanted
